VT Linear Algebra Library: vt::numeric_matrix_static_t< T, Row, Col > Class Template Reference
vt::numeric_matrix_static_t< T, Row, Col > Class Template Reference
#include <numeric_matrix.h>
Public Member Functions
constexpr numeric_matrix_static_t ()=default
constexpr numeric_matrix_static_t (const T &fill)
constexpr numeric_matrix_static_t (const numeric_matrix_static_t &other)=default
constexpr numeric_matrix_static_t (numeric_matrix_static_t &&other) noexcept=default
constexpr numeric_matrix_static_t (const T(&array)[Row][Col])
numeric_matrix_static_t (const numeric_vector_static_t< T, Col >(&vectors)[Row])
constexpr numeric_matrix_static_t (const numeric_vector_static_t< numeric_vector_static_t< T, Col >, Row > &nested)
template<size_t ORow, size_t OCol, size_t M, size_t N>
numeric_matrix_static_t (const numeric_matrix_static_t< T, ORow, OCol >(&blocks)[M][N])
template<size_t R1, size_t C1>
numeric_matrix_static_t (const numeric_matrix_static_t< T, R1, C1 > &M11, const numeric_matrix_static_t< T, R1, Col - C1 > &M12, const numeric_matrix_static_t< T, Row - R1, C1 > &M21, const numeric_matrix_static_t< T, Row - R1, Col - C1 > &M22)
template<size_t C1>
numeric_matrix_static_t (const numeric_matrix_static_t< T, Row, C1 > &A, const numeric_matrix_static_t< T, Row, Col - C1 > &B)
__attribute__ ((always_inline)) numeric_vector_static_t< T
Col & operator[] (size_t index)
__attribute__ ((always_inline)) const expr const numeric_vector_static_t< T
Col & operator[] (size_t index) const
__attribute__ ((always_inline)) T &at(size_t r_index
__attribute__ ((always_inline)) const expr const T &at(size_t r_index
__attribute__ ((always_inline)) T &operator()(size_t r_index
__attribute__ ((always_inline)) const expr const T &operator()(size_t r_index
numeric_matrix_static_t & operator= (const numeric_matrix_static_t &other)
numeric_matrix_static_t & operator= (numeric_matrix_static_t &&other) noexcept
numeric_matrix_static_t & operator= (const T(&array)[Row][Col])
numeric_matrix_static_t & operator= (const numeric_vector_static_t< T, Col >(&vectors)[Row])
numeric_matrix_static_t & operator+= (const numeric_matrix_static_t &other)
numeric_matrix_static_t operator+ (const numeric_matrix_static_t &other) const
constexpr numeric_matrix_static_t add (const numeric_matrix_static_t &other) const
numeric_matrix_static_t & operator-= (const numeric_matrix_static_t &other)
numeric_matrix_static_t operator- (const numeric_matrix_static_t &other) const
constexpr numeric_matrix_static_t sub (const numeric_matrix_static_t &other) const
numeric_matrix_static_t< T, Order, Order > & operator*= (const numeric_matrix_static_t< T, Order, Order > &other)
template<size_t ORow, size_t OCol>
numeric_matrix_static_t< T, Row, OCol > operator* (const numeric_matrix_static_t< T, ORow, OCol > &other) const
numeric_matrix_static_t & operator*= (T rhs)
numeric_matrix_static_t operator* (T rhs) const
numeric_vector_static_t< T, Row > operator* (const numeric_vector_static_t< T, Col > &other) const
template<size_t ORow, size_t OCol>
numeric_matrix_static_t< T, Row, OCol > matmul_naive (const numeric_matrix_static_t< T, ORow, OCol > &other) const
constexpr numeric_vector_static_t< T, Row > transform (const numeric_vector_static_t< T, Col > &other) const
numeric_matrix_static_t< T, Order, Order > & operator^= (size_t n)
numeric_matrix_static_t< T, Order, Order > operator^ (size_t n)
numeric_matrix_static_t< T, Order, Order > matpow (size_t n)
numeric_matrix_static_t< T, Order, Order > matpow_naive (size_t n)
template<size_t pos_row = 0, size_t pos_col = 0, size_t ORow, size_t OCol>
numeric_matrix_static_t & insert (const numeric_matrix_static_t< T, ORow, OCol > &M)
template<size_t pos_row = 0, size_t pos_col = 0, size_t ORow, size_t OCol>
numeric_matrix_static_t & insert (const T(&array)[ORow][OCol])
template<size_t r1, size_t c1, size_t r2, size_t c2>
numeric_matrix_static_t< T, r2 - r1, c2 - c1 > slice () const
constexpr numeric_vector_static_t< T, Col > row (size_t r_index) const
numeric_vector_static_t< T, Row > col (size_t c_index) const
numeric_vector_static_t< T, Order > diag () const
numeric_matrix_static_t< T, Col, Row > transpose () const
T det () const
T tr () const
numeric_matrix_static_t inv () const
constexpr numeric_matrix_static_t inverse () const
numeric_matrix_static_lu_t< T, Order > LU () const
numeric_matrix_static_t RRE () const
template<size_t ORow, size_t OCol>
bool operator== (const numeric_matrix_static_t< T, ORow, OCol > &other) const
template<size_t ORow, size_t OCol>
bool operator== (const T(&array)[ORow][OCol]) const
template<size_t ORow, size_t OCol>
constexpr bool operator!= (const numeric_matrix_static_t< T, ORow, OCol > &other) const
template<size_t ORow, size_t OCol>
constexpr bool operator!= (const T(&array)[ORow][OCol]) const
template<size_t ORow, size_t OCol>
constexpr bool equals (const numeric_matrix_static_t< T, ORow, OCol > &other) const
template<size_t ORow, size_t OCol>
bool float_equals (const numeric_matrix_static_t< T, ORow, OCol > &other) const
template<size_t ORow, size_t OCol>
constexpr bool equals (const T(&array)[ORow][OCol]) const
iterator< numeric_vector_static_t< T, Col > > begin ()
constexpr iterator< numeric_vector_static_t< T, Col > > begin () const
iterator< numeric_vector_static_t< T, Col > > end ()
constexpr iterator< numeric_vector_static_t< T, Col > > end () const
constexpr size_t r () const
constexpr size_t c () const
constexpr size_t n () const
constexpr size_t order () const
constexpr bool is_square () const
void swap (numeric_matrix_static_t &other)
constexpr numeric_matrix_static_t copy () const
Static Public Member Functions
static numeric_matrix_static_t & iadd (numeric_matrix_static_t &C, const numeric_matrix_static_t &A, const numeric_matrix_static_t &B)
static numeric_matrix_static_t & isub (numeric_matrix_static_t &C, const numeric_matrix_static_t &A, const numeric_matrix_static_t &B)
template<size_t ORow, size_t X, size_t OCol>
static constexpr numeric_matrix_static_t< T, ORow, OCol > imatmul (numeric_matrix_static_t< T, ORow, OCol > &C, const numeric_matrix_static_t< T, ORow, X > &A, const numeric_matrix_static_t< T, X, OCol > &B)
static constexpr numeric_matrix_static_t zeros ()
static constexpr numeric_matrix_static_t ones ()
static constexpr numeric_matrix_static_t identity ()
static constexpr numeric_matrix_static_t id ()
static numeric_matrix_static_t diagonals (T value)
static numeric_matrix_static_t diagonals (const T(&array)[Order])
template<size_t ORow, size_t OCol>
static numeric_matrix_static_t constexpr quad (const numeric_matrix_static_t< T, ORow, OCol > M)
Data Fields
size_t c_index { return vector_[r_index][c_index]
size_t c_index const { return vector_[r_index][c_index]
Private Member Functions
void fix_zero ()
void allocate_zero ()
void allocate_fill (T fill)
void allocate_from (const numeric_matrix_static_t &other)
void allocate_from (const T(&array)[Row][Col])
void allocate_from (const numeric_vector_static_t< T, Col >(&vectors)[Row])
void steal (numeric_matrix_static_t &&other)
template<size_t ORow, size_t OCol, size_t M, size_t N>
void helper_insert_major (size_t pos_row, const numeric_matrix_static_t< T, ORow, OCol >(&blocks)[M][N])
template<size_t ORow, size_t OCol, size_t M, size_t N>
void helper_insert_minor (size_t pos_row, size_t pos_col, const numeric_matrix_static_t< T, ORow, OCol >(&blocks)[M][N])
template<size_t ORow, size_t OCol>
void helper_insert_unsafe (size_t pos_row, size_t pos_col, const numeric_matrix_static_t< T, ORow, OCol > &M)
Static Private Member Functions
static constexpr bool static_is_a_square_matrix ()
static constexpr bool is_multiple_of_2 (size_t x)
static size_t closest_2 (size_t x)
template<size_t ORow, size_t X, size_t OCol>
static numeric_matrix_static_t< T, ORow, OCol > & mm_naive (numeric_matrix_static_t< T, ORow, OCol > &C, const numeric_matrix_static_t< T, ORow, X > &A, const numeric_matrix_static_t< T, X, OCol > &B)
template<size_t ORow, size_t X, size_t OCol>
static constexpr numeric_matrix_static_t< T, ORow, OCol > & mm_strassen (numeric_matrix_static_t< T, ORow, OCol > &C, const numeric_matrix_static_t< T, ORow, X > &A, const numeric_matrix_static_t< T, X, OCol > &B)
template<size_t OSize>
static numeric_matrix_static_t< T, OSize, OSize > inv_lt (numeric_matrix_static_t< T, OSize, OSize > &L)
template<size_t OSize>
static numeric_matrix_static_t< T, OSize, OSize > inv_ut (numeric_matrix_static_t< T, OSize, OSize > &U)
Private Attributes
numeric_vector_static_t< numeric_vector_static_t< T, Col >, Row > vector_ = {}
Static Private Attributes
static constexpr size_t Order = (Row < Col) ? Row : Col
Friends
template<typename U , size_t V>
class numeric_vector_static_t
Detailed Description
template<typename T, size_t Row, size_t Col>
class vt::numeric_matrix_static_t< T, Row, Col >
Numeric matrix template class where the dimension must be known at compile-time and can't be changed by any ways during runtime to prevent unexpected behavior or errors. This avoid heap usages for safety-critical and performance-critical systems.
Template Parameters
T data type
Row row dimension
Col column dimension
Definition at line 31 of file numeric_matrix.h.
Constructor & Destructor Documentation
numeric_matrix_static_t() [1/10]
template<typename T , size_t Row, size_t Col> constexpr vt::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t () constexpr default
Default constructor, initializes to zero
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::copy(), vt::numeric_matrix_static_t< T, Row, Col >::ones(), vt::numeric_matrix_static_t< T, Row, Col >::operator^(), vt::numeric_matrix_static_t< T, Row, Col >::quad(), and vt::numeric_matrix_static_t< T, Row, Col >::zeros().
numeric_matrix_static_t() [2/10]
template<typename T , size_t Row, size_t Col> constexpr vt::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t (const T & fill) inline explicit constexpr
Fill constructor, initializes to fill value
Parameters
fill Fill value
Definition at line 57 of file numeric_matrix.h.
                : vector_(
                numeric_vector_static_t<numeric_vector_static_t<T, Col>, Row>(numeric_vector_static_t<T, Col>(fill))
        ) {}
numeric_matrix_static_t() [3/10]
template<typename T , size_t Row, size_t Col> constexpr vt::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t (const numeric_matrix_static_t< T, Row, Col > & other) constexpr default
Copy constructor
Parameters
other Other matrix
numeric_matrix_static_t() [4/10]
template<typename T , size_t Row, size_t Col> constexpr vt::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t (numeric_matrix_static_t< T, Row, Col > && other) constexpr default noexcept
Move constructor
Parameters
other Other vector
numeric_matrix_static_t() [5/10]
template<typename T , size_t Row, size_t Col> constexpr vt::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t (const T(&) array[Row][Col]) inline explicit constexpr
Array constructor, construct from array
Parameters
array Array of entries
Definition at line 81 of file numeric_matrix.h.
                : vector_(vt::detail::make_nested(array)) {}
numeric_matrix_static_t() [6/10]
template<typename T , size_t Row, size_t Col> vt::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t (const numeric_vector_static_t< T, Col >(&) vectors[Row]) inline explicit
Array of vectors as rows constructor, construct from array
Parameters
vectors Array of rows
Definition at line 89 of file numeric_matrix.h.
{
            allocate_from(vectors);
        }
References vt::numeric_matrix_static_t< T, Row, Col >::allocate_from().
numeric_matrix_static_t() [7/10]
template<typename T , size_t Row, size_t Col> constexpr vt::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t (const numeric_vector_static_t< numeric_vector_static_t< T, Col >, Row > & nested) inline explicit constexpr
Nested vector constructor
Parameters
nested Nested vector
Definition at line 98 of file numeric_matrix.h.
        : vector_(nested) {}
numeric_matrix_static_t() [8/10]
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol, size_t M, size_t N> vt::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t (const numeric_matrix_static_t< T, ORow, OCol >(&) blocks[M][N]) inline explicit
Block matrix constructor
Template Parameters
ORow
OCol
M
N
Parameters
blocks Array of blocks
Definition at line 111 of file numeric_matrix.h.
{
            helper_insert_major(0, blocks);
        }
References vt::numeric_matrix_static_t< T, Row, Col >::helper_insert_major().
numeric_matrix_static_t() [9/10]
template<typename T , size_t Row, size_t Col> template<size_t R1, size_t C1> vt::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t (const numeric_matrix_static_t< T, R1, C1 > & M11, const numeric_matrix_static_t< T, R1, Col - C1 > & M12, const numeric_matrix_static_t< T, Row - R1, C1 > & M21, const numeric_matrix_static_t< T, Row - R1, Col - C1 > & M22) inline
Quad-matrix constructor, construct M from M11, M12, M21, M22
Template Parameters
R1
C1
Parameters
M11 Upper-left matrix
M12 Upper-right matrix
M21 Lower-left matrix
M22 Lower-right matrix
Definition at line 126 of file numeric_matrix.h.
{
            insert<0, 0>(M11);
            insert<0, C1>(M12);
            insert<R1, 0>(M21);
            insert<R1, C1>(M22);
        }
numeric_matrix_static_t() [10/10]
template<typename T , size_t Row, size_t Col> template<size_t C1> vt::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t (const numeric_matrix_static_t< T, Row, C1 > & A, const numeric_matrix_static_t< T, Row, Col - C1 > & B) inline
B matrix constructor, construct M from [A | B]
Template Parameters
C1 Main column
Parameters
A Main matrix
B Augment part
Definition at line 144 of file numeric_matrix.h.
{
            insert<0, 0>(A);
            insert<0, C1>(B);
        }
Member Function Documentation
__attribute__() [1/6]
template<typename T , size_t Row, size_t Col> vt::numeric_matrix_static_t< T, Row, Col >::__attribute__ ((always_inline)) const
__attribute__() [2/6]
template<typename T , size_t Row, size_t Col> vt::numeric_matrix_static_t< T, Row, Col >::__attribute__ ((always_inline)) const &
__attribute__() [3/6]
template<typename T , size_t Row, size_t Col> vt::numeric_matrix_static_t< T, Row, Col >::__attribute__ ((always_inline)) const &
References vt::numeric_matrix_static_t< T, Row, Col >::c_index.
__attribute__() [4/6]
template<typename T , size_t Row, size_t Col> vt::numeric_matrix_static_t< T, Row, Col >::__attribute__ ((always_inline))
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
__attribute__() [5/6]
template<typename T , size_t Row, size_t Col> vt::numeric_matrix_static_t< T, Row, Col >::__attribute__ ((always_inline)) &
References vt::numeric_matrix_static_t< T, Row, Col >::c_index, and vt::numeric_matrix_static_t< T, Row, Col >::vector_.
__attribute__() [6/6]
template<typename T , size_t Row, size_t Col> vt::numeric_matrix_static_t< T, Row, Col >::__attribute__ ((always_inline)) &
References vt::numeric_matrix_static_t< T, Row, Col >::c_index.
add()
template<typename T , size_t Row, size_t Col> constexpr numeric_matrix_static_t vt::numeric_matrix_static_t< T, Row, Col >::add (const numeric_matrix_static_t< T, Row, Col > & other) const inline constexpr
Definition at line 194 of file numeric_matrix.h.
{ return operator+(other); }
References vt::numeric_matrix_static_t< T, Row, Col >::operator+().
allocate_fill()
template<typename T , size_t Row, size_t Col> void vt::numeric_matrix_static_t< T, Row, Col >::allocate_fill (T fill) inline private
Definition at line 771 of file numeric_matrix.h.
{
            vector_ = vt::move(
                    numeric_vector_static_t<numeric_vector_static_t<T, Col>, Row>(numeric_vector_static_t<T, Col>(fill))
            );
        }
References vt::fill(), and vt::numeric_matrix_static_t< T, Row, Col >::vector_.
allocate_from() [1/3]
template<typename T , size_t Row, size_t Col> void vt::numeric_matrix_static_t< T, Row, Col >::allocate_from (const numeric_matrix_static_t< T, Row, Col > & other) inline private
Definition at line 777 of file numeric_matrix.h.
{ vector_ = other.vector_; }
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t(), vt::numeric_matrix_static_t< T, Row, Col >::operator=(), vt::numeric_matrix_static_t< T, Row, Col >::operator=(), and vt::numeric_matrix_static_t< T, Row, Col >::operator=().
allocate_from() [2/3]
template<typename T , size_t Row, size_t Col> void vt::numeric_matrix_static_t< T, Row, Col >::allocate_from (const numeric_vector_static_t< T, Col >(&) vectors[Row]) inline private
Definition at line 785 of file numeric_matrix.h.
{
            for (size_t i = 0; i < Row; ++i)
                for (size_t j = 0; j < Col; ++j)
                    vector_[i][j] = vectors[i][j];
        }
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
allocate_from() [3/3]
template<typename T , size_t Row, size_t Col> void vt::numeric_matrix_static_t< T, Row, Col >::allocate_from (const T(&) array[Row][Col]) inline private
Definition at line 779 of file numeric_matrix.h.
{
            for (size_t i = 0; i < Row; ++i)
                for (size_t j = 0; j < Col; ++j)
                    vector_[i][j] = array[i][j];
        }
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
allocate_zero()
template<typename T , size_t Row, size_t Col> void vt::numeric_matrix_static_t< T, Row, Col >::allocate_zero () inline private
Definition at line 769 of file numeric_matrix.h.
{ vector_ = vt::move(numeric_vector_static_t<numeric_vector_static_t<T, Col>, Row>()); }
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
begin() [1/2]
template<typename T , size_t Row, size_t Col> iterator< numeric_vector_static_t< T, Col > > vt::numeric_matrix_static_t< T, Row, Col >::begin () inline
Returns an iterator to matrix's first row.
Returns
An iterator to matrix's first row
Definition at line 687 of file numeric_matrix.h.
{ return vector_.begin(); }
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
begin() [2/2]
template<typename T , size_t Row, size_t Col> constexpr iterator< numeric_vector_static_t< T, Col > > vt::numeric_matrix_static_t< T, Row, Col >::begin () const inline constexpr
Returns an iterator to matrix's first row.
Returns
An iterator to matrix's first row
Definition at line 694 of file numeric_matrix.h.
{ return vector_.begin(); }
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
c()
template<typename T , size_t Row, size_t Col> constexpr size_t vt::numeric_matrix_static_t< T, Row, Col >::c () const inline constexpr
Returns number of columns.
Returns
Number of columns
Definition at line 722 of file numeric_matrix.h.
{ return Col; }
closest_2()
template<typename T , size_t Row, size_t Col> static size_t vt::numeric_matrix_static_t< T, Row, Col >::closest_2 (size_t x) inline static private
Definition at line 819 of file numeric_matrix.h.
{
            if (is_multiple_of_2(x)) return x;
            size_t result = 1;
            while (x != 0) {
                x >>= 1;
                result <<= 1;
            }
            return result;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::is_multiple_of_2().
col()
template<typename T , size_t Row, size_t Col> numeric_vector_static_t< T, Row > vt::numeric_matrix_static_t< T, Row, Col >::col (size_t c_index) const inline
Returns column at index as vector.
WARNING: Doesn't have out of range check!
Parameters
c_index Column index
Returns
Column at index as vector
Definition at line 443 of file numeric_matrix.h.
{
            numeric_vector_static_t<T, Row> result;
            for (size_t i = 0; i < Row; ++i) result[i] = vector_[i][c_index];
            return result;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::c_index, and vt::numeric_matrix_static_t< T, Row, Col >::vector_.
copy()
template<typename T , size_t Row, size_t Col> constexpr numeric_matrix_static_t vt::numeric_matrix_static_t< T, Row, Col >::copy () const inline constexpr
Creates a copy of this matrix.
Returns
A copy of this matrix
Definition at line 759 of file numeric_matrix.h.
{ return numeric_matrix_static_t(*this); }
References vt::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t().
det()
template<typename T , size_t Row, size_t Col> T vt::numeric_matrix_static_t< T, Row, Col >::det () const inline
Finds determinant of this matrix.
If this matrix is not square, the compile-time error is thrown.
Returns
Determinant of this matrix
Definition at line 479 of file numeric_matrix.h.
                      {
            static_assert(static_is_a_square_matrix(), "Can only find determinant of a square matrix.");
            numeric_matrix_static_lu_t<T, Order> lu = vt::move(LU());
            T det = 1;
            size_t r_swaps = 0;
            for (size_t i = 0; i < Order; ++i) {
                det *= lu.u()[i][i];
                if (lu.u()[i][i] == 0) return 0;
                if (lu.l()[i][i] != 1) r_swaps++;
            }
            return (r_swaps % 2 == 0) ? det : -det;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::det(), vt::numeric_matrix_static_lu_t< T, OSize >::l(), vt::numeric_matrix_static_t< T, Row, Col >::LU(), vt::numeric_matrix_static_t< T, Row, Col >::Order, vt::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix(), and vt::numeric_matrix_static_lu_t< T, OSize >::u().
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::det(), and vt::det().
diag()
template<typename T , size_t Row, size_t Col> numeric_vector_static_t< T, Order > vt::numeric_matrix_static_t< T, Row, Col >::diag () const inline
Returns main diagonal entries as vector.
Returns
Main diagonal entries as vector
Definition at line 454 of file numeric_matrix.h.
{
            numeric_vector_static_t<T, Order> result;
            for (size_t i = 0; i < Order; ++i) result[i] = vector_[i][i];
            return result;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::Order, and vt::numeric_matrix_static_t< T, Row, Col >::vector_.
diagonals() [1/2]
template<typename T , size_t Row, size_t Col> static numeric_matrix_static_t vt::numeric_matrix_static_t< T, Row, Col >::diagonals (const T(&) array[Order]) inline static
Returns a matrix where the main diagonal is filled with fill values from array.
Parameters
array Fill array
Returns
Filled diagonal matrix
Definition at line 930 of file numeric_matrix.h.
{
            numeric_matrix_static_t tmp;
            for (size_t i = 0; i < Order; ++i) tmp[i][i] = array[i];
            return tmp;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::Order.
diagonals() [2/2]
template<typename T , size_t Row, size_t Col> static numeric_matrix_static_t vt::numeric_matrix_static_t< T, Row, Col >::diagonals (T value) inline static
Returns a matrix where the main diagonal is filled with fill value.
Parameters
value Fill value
Returns
Filled diagonal matrix
Definition at line 918 of file numeric_matrix.h.
{
            numeric_matrix_static_t tmp;
            for (size_t i = 0; i < Order; ++i) tmp[i][i] = value;
            return tmp;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::Order.
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::identity().
end() [1/2]
template<typename T , size_t Row, size_t Col> iterator< numeric_vector_static_t< T, Col > > vt::numeric_matrix_static_t< T, Row, Col >::end () inline
Returns an iterator to matrix's last row.
Returns
An iterator to matrix's last row
Definition at line 701 of file numeric_matrix.h.
{ return vector_.end(); }
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
end() [2/2]
template<typename T , size_t Row, size_t Col> constexpr iterator< numeric_vector_static_t< T, Col > > vt::numeric_matrix_static_t< T, Row, Col >::end () const inline constexpr
Returns an iterator to matrix's last row.
Returns
An iterator to matrix's last row
Definition at line 708 of file numeric_matrix.h.
{ return vector_.end(); }
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
equals() [1/2]
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> constexpr bool vt::numeric_matrix_static_t< T, Row, Col >::equals (const numeric_matrix_static_t< T, ORow, OCol > & other) const inline constexpr
Checks equality of this matrix and the other matrix.
Template Parameters
ORow
OCol
Parameters
other Other matrix
Returns
Definition at line 653 of file numeric_matrix.h.
{ return operator==(other); }
References vt::numeric_matrix_static_t< T, Row, Col >::operator==().
equals() [2/2]
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> constexpr bool vt::numeric_matrix_static_t< T, Row, Col >::equals (const T(&) array[ORow][OCol]) const inline constexpr
Checks equality of this matrix and the other matrix.
Template Parameters
ORow
OCol
Parameters
array Other matrix as array
Returns
Definition at line 680 of file numeric_matrix.h.
{ return operator==(array); }
References vt::numeric_matrix_static_t< T, Row, Col >::operator==().
fix_zero()
template<typename T , size_t Row, size_t Col> void vt::numeric_matrix_static_t< T, Row, Col >::fix_zero () inline private
Definition at line 762 of file numeric_matrix.h.
{
            for (size_t i = 0; i < Row; ++i)
                for (size_t j = 0; j < Col; ++j)
                    if (vector_[i][j] == 0.0)
                        vector_[i][j] = 0.0;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::RRE().
float_equals()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> bool vt::numeric_matrix_static_t< T, Row, Col >::float_equals (const numeric_matrix_static_t< T, ORow, OCol > & other) const inline
Checks equality of this matrix and the other matrix with float/double threshold using equation abs(x_ - y) < threshold for equality.
Template Parameters
ORow
OCol
Parameters
other Other matrix
Returns
Definition at line 664 of file numeric_matrix.h.
{
            if (this == &other) return true;
            if (Row != ORow || Col != OCol) return false;
            for (size_t i = 0; i < Row; ++i) if (!vector_[i].float_equals(other.vector_[i])) return false;
            return true;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::float_equals(), and vt::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::float_equals().
helper_insert_major()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol, size_t M, size_t N> void vt::numeric_matrix_static_t< T, Row, Col >::helper_insert_major (size_t pos_row, const numeric_matrix_static_t< T, ORow, OCol >(&) blocks[M][N]) inline private
Definition at line 794 of file numeric_matrix.h.
{
            if (pos_row < M) {
                helper_insert_minor(pos_row, 0, blocks);
                helper_insert_major(pos_row + 1, blocks);
            }
        }
References vt::numeric_matrix_static_t< T, Row, Col >::helper_insert_major(), and vt::numeric_matrix_static_t< T, Row, Col >::helper_insert_minor().
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::helper_insert_major(), and vt::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t().
helper_insert_minor()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol, size_t M, size_t N> void vt::numeric_matrix_static_t< T, Row, Col >::helper_insert_minor (size_t pos_row, size_t pos_col, const numeric_matrix_static_t< T, ORow, OCol >(&) blocks[M][N]) inline private
Definition at line 802 of file numeric_matrix.h.
{
            helper_insert_unsafe(ORow * pos_row, OCol * pos_col, blocks[pos_row][pos_col]);
            if (pos_col < N - 1) helper_insert_minor(pos_row, pos_col + 1, blocks);
        }
References vt::numeric_matrix_static_t< T, Row, Col >::helper_insert_minor(), and vt::numeric_matrix_static_t< T, Row, Col >::helper_insert_unsafe().
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::helper_insert_major(), and vt::numeric_matrix_static_t< T, Row, Col >::helper_insert_minor().
helper_insert_unsafe()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> void vt::numeric_matrix_static_t< T, Row, Col >::helper_insert_unsafe (size_t pos_row, size_t pos_col, const numeric_matrix_static_t< T, ORow, OCol > & M) inline private
Definition at line 809 of file numeric_matrix.h.
{
            for (size_t i = 0; i < ORow; ++i)
                for (size_t j = 0; j < OCol; ++j)
                    vector_[pos_row + i][pos_col + j] = M[i][j];
        }
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::helper_insert_minor().
iadd()
template<typename T , size_t Row, size_t Col> static numeric_matrix_static_t & vt::numeric_matrix_static_t< T, Row, Col >::iadd (numeric_matrix_static_t< T, Row, Col > & C, const numeric_matrix_static_t< T, Row, Col > & A, const numeric_matrix_static_t< T, Row, Col > & B) inline static
In-place C = A + B_ tools
Parameters
C
A
B
Returns
C
Definition at line 204 of file numeric_matrix.h.
{
            for (size_t i = 0; i < Row; ++i)
                for (size_t j = 0; j < Col; ++j)
                    C[i][j] = A[i][j] + B[i][j];
            return C;
        }
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::operator+=().
id()
template<typename T , size_t Row, size_t Col> static constexpr numeric_matrix_static_t vt::numeric_matrix_static_t< T, Row, Col >::id () inline static constexpr
Returns an identity matrix of current dimension.
If this matrix is not square, the compile-time error is thrown.
Returns
Identity matrix
Definition at line 910 of file numeric_matrix.h.
{ return identity(); }
References vt::numeric_matrix_static_t< T, Row, Col >::identity().
identity()
template<typename T , size_t Row, size_t Col> static constexpr numeric_matrix_static_t vt::numeric_matrix_static_t< T, Row, Col >::identity () inline static constexpr
Returns an identity matrix of current dimension.
If this matrix is not square, the compile-time error is thrown.
Returns
Identity matrix
Definition at line 899 of file numeric_matrix.h.
{
            static_assert(static_is_a_square_matrix(), "Identity matrix must be a square matrix.");
            return diagonals(1);
        }
References vt::numeric_matrix_static_t< T, Row, Col >::diagonals(), and vt::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix().
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::id(), and vt::numeric_matrix_static_t< T, Row, Col >::operator^().
imatmul()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t X, size_t OCol> static constexpr numeric_matrix_static_t< T, ORow, OCol > vt::numeric_matrix_static_t< T, Row, Col >::imatmul (numeric_matrix_static_t< T, ORow, OCol > & C, const numeric_matrix_static_t< T, ORow, X > & A, const numeric_matrix_static_t< T, X, OCol > & B) inline static constexpr
In-place C = AB tools
Template Parameters
ORow
X
OCol
Parameters
C
A
B
Returns
C
Definition at line 280 of file numeric_matrix.h.
{
            return mm_naive(C, A, B);
        }
References vt::numeric_matrix_static_t< T, Row, Col >::mm_naive().
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::operator*().
insert() [1/2]
template<typename T , size_t Row, size_t Col> template<size_t pos_row = 0, size_t pos_col = 0, size_t ORow, size_t OCol> numeric_matrix_static_t & vt::numeric_matrix_static_t< T, Row, Col >::insert (const numeric_matrix_static_t< T, ORow, OCol > & M) inline
Insert the other matrix into current matrix, returning reference to the current matrix.
If insertion is not valid, the compile-time error is thrown.
Template Parameters
pos_row Row position to insert, default to 0
pos_col Column position to insert, default to 0
ORow Other matrix's row size
OCol Other matrix's column size
Parameters
M Other matrix
Returns
Reference to this matrix
Definition at line 369 of file numeric_matrix.h.
{
            static_assert(pos_row < Row, "Insertion failed! Start row is out of range.");
            static_assert(pos_col < Col, "Insertion failed! Start column is out of range.");
            static_assert(pos_row + ORow <= Row, "Insertion failed! Stop row is out of range.");
            static_assert(pos_col + OCol <= Col, "Insertion failed! Stop column is out of range.");
            for (size_t i = 0; i < ORow; ++i)
                for (size_t j = 0; j < OCol; ++j)
                    vector_[pos_row + i][pos_col + j] = M[i][j];
            return *this;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
insert() [2/2]
template<typename T , size_t Row, size_t Col> template<size_t pos_row = 0, size_t pos_col = 0, size_t ORow, size_t OCol> numeric_matrix_static_t & vt::numeric_matrix_static_t< T, Row, Col >::insert (const T(&) array[ORow][OCol]) inline
Insert the other matrix into current matrix, returning reference to the current matrix.
If insertion is not valid, the compile-time error is thrown.
Template Parameters
pos_row Row position to insert, default to 0
pos_col Column position to insert, default to 0
ORow Other matrix's row size
OCol Other matrix's column size
Parameters
array Other matrix as 2D array
Returns
Reference to this matrix
Definition at line 392 of file numeric_matrix.h.
{
            static_assert(pos_row < Row, "Insertion failed! Start row is out of range.");
            static_assert(pos_col < Col, "Insertion failed! Start column is out of range.");
            static_assert(pos_row + ORow <= Row, "Insertion failed! Stop row is out of range.");
            static_assert(pos_col + OCol <= Col, "Insertion failed! Stop column is out of range.");
            for (size_t i = 0; i < ORow; ++i)
                for (size_t j = 0; j < OCol; ++j)
                    vector_[pos_row + i][pos_col + j] = array[i][j];
            return *this;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
inv()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t vt::numeric_matrix_static_t< T, Row, Col >::inv () const inline
Finds inverse of this matrix.
If this matrix is not square, the compile-time error is thrown.
Returns
Inverse of this matrix
Definition at line 511 of file numeric_matrix.h.
{
            static_assert(static_is_a_square_matrix(), "Can only find inverse of a square matrix.");
            numeric_matrix_static_lu_t<T, Order> lu = vt::move(LU());
            return inv_ut(lu.u()) * inv_lt(lu.l());
        }
References vt::numeric_matrix_static_t< T, Row, Col >::inv_lt(), vt::numeric_matrix_static_t< T, Row, Col >::inv_ut(), vt::numeric_matrix_static_lu_t< T, OSize >::l(), vt::numeric_matrix_static_t< T, Row, Col >::LU(), vt::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix(), and vt::numeric_matrix_static_lu_t< T, OSize >::u().
Referenced by vt::inv(), and vt::numeric_matrix_static_t< T, Row, Col >::inverse().
inv_lt()
template<typename T , size_t Row, size_t Col> template<size_t OSize> static numeric_matrix_static_t< T, OSize, OSize > vt::numeric_matrix_static_t< T, Row, Col >::inv_lt (numeric_matrix_static_t< T, OSize, OSize > & L) inline static private
Definition at line 855 of file numeric_matrix.h.
{
            static_assert(static_is_a_square_matrix(), "Can only inverse a square matrix.");
            numeric_matrix_static_t<T, OSize, OSize> X;
            for (size_t k = 0; k < OSize; ++k) {
                X[k][k] = 1 / L[k][k];
                for (size_t i = k + 1; i < OSize; ++i) {
                    T acc = 0;
                    for (size_t j = k; j < i; ++j)
                        acc -= L[i][j] * X[j][k];
                    X[i][k] = acc / L[i][i];
                }
            }
            L = vt::move(X);
            return L;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix().
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::inv(), and vt::numeric_matrix_static_t< T, Row, Col >::inv_ut().
inv_ut()
template<typename T , size_t Row, size_t Col> template<size_t OSize> static numeric_matrix_static_t< T, OSize, OSize > vt::numeric_matrix_static_t< T, Row, Col >::inv_ut (numeric_matrix_static_t< T, OSize, OSize > & U) inline static private
Definition at line 872 of file numeric_matrix.h.
{
            static_assert(static_is_a_square_matrix(), "Can only inverse a square matrix.");
            numeric_matrix_static_t<T, OSize, OSize> tmp = vt::move(U.transpose());
            return inv_lt(tmp).transpose();
        }
References vt::numeric_matrix_static_t< T, Row, Col >::inv_lt(), vt::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix(), and vt::numeric_matrix_static_t< T, Row, Col >::transpose().
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::inv().
inverse()
template<typename T , size_t Row, size_t Col> constexpr numeric_matrix_static_t vt::numeric_matrix_static_t< T, Row, Col >::inverse () const inline constexpr
Finds inverse of this matrix.
If this matrix is not square, the compile-time error is thrown.
Returns
Inverse of this matrix
Definition at line 523 of file numeric_matrix.h.
{ return inv(); }
References vt::numeric_matrix_static_t< T, Row, Col >::inv().
is_multiple_of_2()
template<typename T , size_t Row, size_t Col> static constexpr bool vt::numeric_matrix_static_t< T, Row, Col >::is_multiple_of_2 (size_t x) inline static constexpr private
Definition at line 817 of file numeric_matrix.h.
{ return x != 0 && !(x & (x - 1)); }
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::closest_2().
is_square()
template<typename T , size_t Row, size_t Col> constexpr bool vt::numeric_matrix_static_t< T, Row, Col >::is_square () const inline constexpr
Returns whether the matrix is square.
Returns
Definition at line 743 of file numeric_matrix.h.
{ return Row == Col; }
isub()
template<typename T , size_t Row, size_t Col> static numeric_matrix_static_t & vt::numeric_matrix_static_t< T, Row, Col >::isub (numeric_matrix_static_t< T, Row, Col > & C, const numeric_matrix_static_t< T, Row, Col > & A, const numeric_matrix_static_t< T, Row, Col > & B) inline static
In-place C = A - B_ tools
Parameters
C
A
B
Returns
C
Definition at line 231 of file numeric_matrix.h.
{
            for (size_t i = 0; i < Row; ++i)
                for (size_t j = 0; j < Col; ++j)
                    C[i][j] = A[i][j] - B[i][j];
            return C;
        }
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::operator-=().
LU()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_lu_t< T, Order > vt::numeric_matrix_static_t< T, Row, Col >::LU () const inline
Finds LU-decomposition of this matrix.
If this matrix is not square, the compile-time error is thrown.
Returns
LU-decomposition of this matrix
Definition at line 531 of file numeric_matrix.h.
{
            static_assert(static_is_a_square_matrix(), "Can only find LU decomposition of a square matrix.");
            numeric_matrix_static_t<T, Order, Order> lower;
            numeric_matrix_static_t<T, Order, Order> upper;
            for (size_t i = 0; i < Order; ++i) {
                for (size_t k = 0; k < Order; ++k) {
                    T sum_ = 0;
                    for (size_t j = 0; j < i; ++j) sum_ += lower[i][j] * upper[j][k];
                    upper[i][k] = vector_[i][k] - sum_;
                }
                for (size_t k = i; k < Order; ++k) {
                    if (i == k) lower[i][i] = 1;
                    else {
                        T sum_ = 0;
                        for (size_t j = 0; j < i; ++j) sum_ += lower[k][j] * upper[j][i];
                        lower[k][i] = (vector_[k][i] - sum_) / upper[i][i];
                    }
                }
            }
            return {lower, upper};
        }
References vt::numeric_matrix_static_t< T, Row, Col >::Order, vt::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix(), and vt::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::det(), and vt::numeric_matrix_static_t< T, Row, Col >::inv().
matmul_naive()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> numeric_matrix_static_t< T, Row, OCol > vt::numeric_matrix_static_t< T, Row, Col >::matmul_naive (const numeric_matrix_static_t< T, ORow, OCol > & other) const inline
Multiply this matrix with the other matrix in naive O(n^3) way (default multiplication method).
Template Parameters
ORow
OCol
Parameters
other
Returns
Multiplied matrix
Definition at line 295 of file numeric_matrix.h.
{
            numeric_matrix_static_t<T, Row, OCol> C;
            return mm_naive(C, *this, other);
        }
References vt::numeric_matrix_static_t< T, Row, Col >::mm_naive().
matpow()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t< T, Order, Order > vt::numeric_matrix_static_t< T, Row, Col >::matpow (size_t n) inline
Calculate a nth power of this matrix in O(log n * mulO). Must be a square matrix.
If this matrix is not square, the compile-time error is thrown.
Parameters
n
Returns
A^n
Definition at line 338 of file numeric_matrix.h.
{
            static_assert(static_is_a_square_matrix(), "Non-square matrix can\'t use power operator.");
            return operator^(n);
        }
References vt::numeric_matrix_static_t< T, Row, Col >::n(), vt::numeric_matrix_static_t< T, Row, Col >::operator^(), and vt::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix().
matpow_naive()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t< T, Order, Order > vt::numeric_matrix_static_t< T, Row, Col >::matpow_naive (size_t n) inline
Calculate a nth power of this matrix in O(n * mulO) naively. Must be a square matrix.
If this matrix is not square, the compile-time error is thrown.
Parameters
n
Returns
A^n
Definition at line 350 of file numeric_matrix.h.
{
            static_assert(static_is_a_square_matrix(), "Non-square matrix can\'t use power operator.");
            numeric_matrix_static_t<T, Order, Order> product = vt::move(id());
            for (size_t i = 0; i < n; ++i) product *= *this;
            return product;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::n(), and vt::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix().
mm_naive()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t X, size_t OCol> static numeric_matrix_static_t< T, ORow, OCol > & vt::numeric_matrix_static_t< T, Row, Col >::mm_naive (numeric_matrix_static_t< T, ORow, OCol > & C, const numeric_matrix_static_t< T, ORow, X > & A, const numeric_matrix_static_t< T, X, OCol > & B) inline static private
Definition at line 830 of file numeric_matrix.h.
{
            for (size_t i = 0; i < ORow; ++i) {
                numeric_vector_static_t<T, OCol> &row_C = C[i];
                for (size_t k = 0; k < X; ++k) {
                    const T &val_A = A[i][k];
                    for (size_t j = 0; j < OCol; ++j) {
                        row_C[j] += val_A * B[k][j];
                    }
                }
            }
            return C;
        }
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::imatmul(), vt::numeric_matrix_static_t< T, Row, Col >::matmul_naive(), and vt::numeric_matrix_static_t< T, Row, Col >::mm_strassen().
mm_strassen()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t X, size_t OCol> static constexpr numeric_matrix_static_t< T, ORow, OCol > & vt::numeric_matrix_static_t< T, Row, Col >::mm_strassen (numeric_matrix_static_t< T, ORow, OCol > & C, const numeric_matrix_static_t< T, ORow, X > & A, const numeric_matrix_static_t< T, X, OCol > & B) inline static constexpr private
Definition at line 846 of file numeric_matrix.h.
{
            // to be implemented later.
            // not suitable for embedded system.
            return mm_naive(C, A, B);
        }
References vt::numeric_matrix_static_t< T, Row, Col >::mm_naive().
n()
template<typename T , size_t Row, size_t Col> constexpr size_t vt::numeric_matrix_static_t< T, Row, Col >::n () const inline constexpr
Returns number of entries.
Returns
Number of entries
Definition at line 729 of file numeric_matrix.h.
{ return Row * Col; }
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::matpow(), vt::numeric_matrix_static_t< T, Row, Col >::matpow_naive(), vt::numeric_matrix_static_t< T, Row, Col >::operator^(), and vt::numeric_matrix_static_t< T, Row, Col >::operator^=().
ones()
template<typename T , size_t Row, size_t Col> static constexpr numeric_matrix_static_t vt::numeric_matrix_static_t< T, Row, Col >::ones () inline static constexpr
Returns 1-filled matrix.
Returns
1-filled matrix
Definition at line 891 of file numeric_matrix.h.
{ return numeric_matrix_static_t(1); }
References vt::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t().
operator!=() [1/2]
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> constexpr bool vt::numeric_matrix_static_t< T, Row, Col >::operator!= (const numeric_matrix_static_t< T, ORow, OCol > & other) const inline constexpr
Checks inequality of this matrix and the other matrix.
Template Parameters
ORow
OCol
Parameters
other Other matrix
Returns
Definition at line 629 of file numeric_matrix.h.
{
            return !operator==(other);
        }
References vt::numeric_matrix_static_t< T, Row, Col >::operator==().
operator!=() [2/2]
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> constexpr bool vt::numeric_matrix_static_t< T, Row, Col >::operator!= (const T(&) array[ORow][OCol]) const inline constexpr
Checks inequality of this matrix and the other matrix.
Template Parameters
ORow
OCol
Parameters
array Other matrix as array
Returns
Definition at line 642 of file numeric_matrix.h.
{ return !operator==(array); }
References vt::numeric_matrix_static_t< T, Row, Col >::operator==().
operator*() [1/3]
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> numeric_matrix_static_t< T, Row, OCol > vt::numeric_matrix_static_t< T, Row, Col >::operator* (const numeric_matrix_static_t< T, ORow, OCol > & other) const inline
Definition at line 246 of file numeric_matrix.h.
{
            numeric_matrix_static_t<T, Row, OCol> C;
            return imatmul(C, *this, other);
        }
References vt::numeric_matrix_static_t< T, Row, Col >::imatmul().
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::transform().
operator*() [2/3]
template<typename T , size_t Row, size_t Col> numeric_vector_static_t< T, Row > vt::numeric_matrix_static_t< T, Row, Col >::operator* (const numeric_vector_static_t< T, Col > & other) const inline
Definition at line 262 of file numeric_matrix.h.
{
            numeric_vector_static_t<T, Row> tmp;
            for (size_t i = 0; i < Row; ++i) tmp[i] = vector_[i].dot(other);
            return tmp;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
operator*() [3/3]
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t vt::numeric_matrix_static_t< T, Row, Col >::operator* (T rhs) const inline
Definition at line 256 of file numeric_matrix.h.
{
            numeric_matrix_static_t tmp(*this);
            tmp.operator*=(rhs);
            return tmp;
        }
operator*=() [1/2]
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t< T, Order, Order > & vt::numeric_matrix_static_t< T, Row, Col >::operator*= (const numeric_matrix_static_t< T, Order, Order > & other) inline
Definition at line 240 of file numeric_matrix.h.
{
            steal(vt::move(operator*(other)));
            return *this;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::steal().
operator*=() [2/2]
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t & vt::numeric_matrix_static_t< T, Row, Col >::operator*= (T rhs) inline
Definition at line 251 of file numeric_matrix.h.
{
            for (auto &x: vector_) x *= rhs;
            return *this;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
operator+()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t vt::numeric_matrix_static_t< T, Row, Col >::operator+ (const numeric_matrix_static_t< T, Row, Col > & other) const inline
Definition at line 188 of file numeric_matrix.h.
{
            numeric_matrix_static_t tmp(*this);
            tmp.operator+=(other);
            return tmp;
        }
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::add().
operator+=()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t & vt::numeric_matrix_static_t< T, Row, Col >::operator+= (const numeric_matrix_static_t< T, Row, Col > & other) inline
Definition at line 186 of file numeric_matrix.h.
{ return iadd(*this, *this, other); }
References vt::numeric_matrix_static_t< T, Row, Col >::iadd().
operator-()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t vt::numeric_matrix_static_t< T, Row, Col >::operator- (const numeric_matrix_static_t< T, Row, Col > & other) const inline
Definition at line 215 of file numeric_matrix.h.
{
            numeric_matrix_static_t tmp(*this);
            tmp.operator-=(other);
            return tmp;
        }
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::sub().
operator-=()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t & vt::numeric_matrix_static_t< T, Row, Col >::operator-= (const numeric_matrix_static_t< T, Row, Col > & other) inline
Definition at line 213 of file numeric_matrix.h.
{ return isub(*this, *this, other); }
References vt::numeric_matrix_static_t< T, Row, Col >::isub().
operator=() [1/4]
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t & vt::numeric_matrix_static_t< T, Row, Col >::operator= (const numeric_matrix_static_t< T, Row, Col > & other) inline
Definition at line 166 of file numeric_matrix.h.
{
            if (this != &other) allocate_from(other);
            return *this;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::allocate_from().
operator=() [2/4]
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t & vt::numeric_matrix_static_t< T, Row, Col >::operator= (const numeric_vector_static_t< T, Col >(&) vectors[Row]) inline
Definition at line 181 of file numeric_matrix.h.
{
            allocate_from(vectors);
            return *this;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::allocate_from().
operator=() [3/4]
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t & vt::numeric_matrix_static_t< T, Row, Col >::operator= (const T(&) array[Row][Col]) inline
Definition at line 176 of file numeric_matrix.h.
{
            allocate_from(array);
            return *this;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::allocate_from().
operator=() [4/4]
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t & vt::numeric_matrix_static_t< T, Row, Col >::operator= (numeric_matrix_static_t< T, Row, Col > && other) inline noexcept
Definition at line 171 of file numeric_matrix.h.
{
            if (this != &other) steal(vt::move(other));
            return *this;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::steal().
operator==() [1/2]
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> bool vt::numeric_matrix_static_t< T, Row, Col >::operator== (const numeric_matrix_static_t< T, ORow, OCol > & other) const inline
Checks equality of this matrix and the other matrix.
Template Parameters
ORow
OCol
Parameters
other Other matrix
Returns
Definition at line 598 of file numeric_matrix.h.
{
            if (this == &other) return true;
            if (Row != ORow || Col != OCol) return false;
            for (size_t i = 0; i < Row; ++i) if (vector_[i] != other.vector_[i]) return false;
            return true;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::equals(), vt::numeric_matrix_static_t< T, Row, Col >::equals(), vt::numeric_matrix_static_t< T, Row, Col >::operator!=(), and vt::numeric_matrix_static_t< T, Row, Col >::operator!=().
operator==() [2/2]
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> bool vt::numeric_matrix_static_t< T, Row, Col >::operator== (const T(&) array[ORow][OCol]) const inline
Checks equality of this matrix and the other matrix.
Template Parameters
ORow
OCol
Parameters
array Other matrix as array
Returns
Definition at line 614 of file numeric_matrix.h.
{
            if (Row != ORow || Col != OCol) return false;
            for (size_t i = 0; i < Row; ++i) if (vector_[i] != array[i]) return false;
            return true;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
operator[]() [1/2]
template<typename T , size_t Row, size_t Col> Col & vt::numeric_matrix_static_t< T, Row, Col >::operator[] (size_t index) inline
Definition at line 150 of file numeric_matrix.h.
{ return vector_[index]; }
operator[]() [2/2]
template<typename T , size_t Row, size_t Col> Col & vt::numeric_matrix_static_t< T, Row, Col >::operator[] (size_t index) const inline
Definition at line 153 of file numeric_matrix.h.
{ return vector_[index]; }
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
operator^()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t< T, Order, Order > vt::numeric_matrix_static_t< T, Row, Col >::operator^ (size_t n) inline
Definition at line 317 of file numeric_matrix.h.
{
            static_assert(static_is_a_square_matrix(), "Non-square matrix can\'t use power operator.");
            if (n == 0) return identity();
            if (n == 1) return numeric_matrix_static_t(*this);
            numeric_matrix_static_t<T, Order, Order> base(*this);
            numeric_matrix_static_t<T, Order, Order> product(vt::move(identity()));
            while (n > 0) {
                if (n % 2 == 1) product.operator*=(base);
                if (n > 1) base *= base;
                n >>= 1;
            }
            return product;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::identity(), vt::numeric_matrix_static_t< T, Row, Col >::n(), vt::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t(), and vt::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix().
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::matpow().
operator^=()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t< T, Order, Order > & vt::numeric_matrix_static_t< T, Row, Col >::operator^= (size_t n) inline
Definition at line 311 of file numeric_matrix.h.
{
            static_assert(static_is_a_square_matrix(), "Non-square matrix can\'t use power operator.");
            steal(vt::move(operator^(n)));
            return *this;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::n(), vt::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix(), and vt::numeric_matrix_static_t< T, Row, Col >::steal().
order()
template<typename T , size_t Row, size_t Col> constexpr size_t vt::numeric_matrix_static_t< T, Row, Col >::order () const inline constexpr
Returns order of this matrix (min(Row, Col)).
Returns
Order of this matrix
Definition at line 736 of file numeric_matrix.h.
{ return Order; }
References vt::numeric_matrix_static_t< T, Row, Col >::Order.
quad()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> static numeric_matrix_static_t constexpr vt::numeric_matrix_static_t< T, Row, Col >::quad (const numeric_matrix_static_t< T, ORow, OCol > M) inline static constexpr
Returns a quad-filled matrix where M11, M12, M21, and M22 are the same.
Template Parameters
ORow
OCol
Parameters
M Fill matrix
Returns
Quad-filled matrix
Definition at line 945 of file numeric_matrix.h.
{
            return numeric_matrix_static_t(M, M, M, M);
        }
References vt::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t().
r()
template<typename T , size_t Row, size_t Col> constexpr size_t vt::numeric_matrix_static_t< T, Row, Col >::r () const inline constexpr
Returns number of rows.
Returns
Number of rows
Definition at line 715 of file numeric_matrix.h.
{ return Row; }
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::RRE().
row()
template<typename T , size_t Row, size_t Col> constexpr numeric_vector_static_t< T, Col > vt::numeric_matrix_static_t< T, Row, Col >::row (size_t r_index) const inline constexpr
Returns row at index as vector.
WARNING: Doesn't have out of range check!
Parameters
r_index Row index
Returns
Row at index as vector
Definition at line 432 of file numeric_matrix.h.
{
            return numeric_vector_static_t<T, Col>(operator[](r_index));
        }
RRE()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t vt::numeric_matrix_static_t< T, Row, Col >::RRE () const inline
Finds Row-Reduced Echlon (RRE) form of this matrix.
If this matrix is not square, the compile-time error is thrown.
Returns
Row-Reduced Echlon form of this matrix
Definition at line 559 of file numeric_matrix.h.
{
            numeric_matrix_static_t m(*this);
            size_t lead = 0;
            for (size_t r = 0; r < Row; ++r) {
                if (lead >= Col) return m;
                size_t i;
                for (i = r; m[i][lead] == 0;) {
                    ++i;
                    if (i == Row) {
                        i = r;
                        ++lead;
                        if (lead == Col) return m;
                    }
                }
                m[i].swap(m[r]);
                T val = m[r][lead];
                for (size_t j = 0; j < Col; ++j) m[r][j] /= val;
                for (i = 0; i < Row; ++i) {
                    if (i != r) {
                        val = m[i][lead];
                        for (size_t j = 0; j < Col; ++j)
                            m[i][j] -= val * m[r][j];
                    }
                }
                ++lead;
            }
            m.fix_zero();
            return m;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::fix_zero(), vt::numeric_matrix_static_t< T, Row, Col >::r(), and vt::numeric_matrix_static_t< T, Row, Col >::swap().
Referenced by vt::RRE().
slice()
template<typename T , size_t Row, size_t Col> template<size_t r1, size_t c1, size_t r2, size_t c2> numeric_matrix_static_t< T, r2 - r1, c2 - c1 > vt::numeric_matrix_static_t< T, Row, Col >::slice () const inline
Slice current matrix.
Template Parameters
r1 Row position from
c1 Column position from
r2 Row position to
c2 Colum position to
Returns
A slice of current matrix
Definition at line 413 of file numeric_matrix.h.
{
            static_assert(r1 < r2, "Start row must be less than stop row.");
            static_assert(c1 < c2, "Start column must be less than stop column.");
            static_assert(r2 <= Row, "Row is out of range.");
            static_assert(c2 <= Col, "Column is out of range.");
            numeric_matrix_static_t<T, r2 - r1, c2 - c1> result;
            for (size_t i = 0; i < r2 - r1; ++i)
                for (size_t j = 0; j < c2 - c1; ++j)
                    result[i][j] = vector_[r1 + i][c1 + j];
            return result;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
static_is_a_square_matrix()
template<typename T , size_t Row, size_t Col> static constexpr bool vt::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix () inline static constexpr private
Definition at line 815 of file numeric_matrix.h.
{ return Row == Col; }
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::det(), vt::numeric_matrix_static_t< T, Row, Col >::identity(), vt::numeric_matrix_static_t< T, Row, Col >::inv(), vt::numeric_matrix_static_t< T, Row, Col >::inv_lt(), vt::numeric_matrix_static_t< T, Row, Col >::inv_ut(), vt::numeric_matrix_static_t< T, Row, Col >::LU(), vt::numeric_matrix_static_t< T, Row, Col >::matpow(), vt::numeric_matrix_static_t< T, Row, Col >::matpow_naive(), vt::numeric_matrix_static_t< T, Row, Col >::operator^(), vt::numeric_matrix_static_t< T, Row, Col >::operator^=(), and vt::numeric_matrix_static_t< T, Row, Col >::tr().
steal()
template<typename T , size_t Row, size_t Col> void vt::numeric_matrix_static_t< T, Row, Col >::steal (numeric_matrix_static_t< T, Row, Col > && other) inline private
Definition at line 791 of file numeric_matrix.h.
{ vector_ = vt::move(other.vector_); }
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::operator*=(), vt::numeric_matrix_static_t< T, Row, Col >::operator=(), and vt::numeric_matrix_static_t< T, Row, Col >::operator^=().
sub()
template<typename T , size_t Row, size_t Col> constexpr numeric_matrix_static_t vt::numeric_matrix_static_t< T, Row, Col >::sub (const numeric_matrix_static_t< T, Row, Col > & other) const inline constexpr
Definition at line 221 of file numeric_matrix.h.
{ return operator-(other); }
References vt::numeric_matrix_static_t< T, Row, Col >::operator-().
swap()
template<typename T , size_t Row, size_t Col> void vt::numeric_matrix_static_t< T, Row, Col >::swap (numeric_matrix_static_t< T, Row, Col > & other) inline
Swaps entries with the other matrix.
Parameters
other
Definition at line 750 of file numeric_matrix.h.
{
            for (size_t i = 0; i < Row; ++i) vector_[i].swap(other.vector_[i]);
        }
References vt::numeric_matrix_static_t< T, Row, Col >::swap(), and vt::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::RRE(), and vt::numeric_matrix_static_t< T, Row, Col >::swap().
tr()
template<typename T , size_t Row, size_t Col> T vt::numeric_matrix_static_t< T, Row, Col >::tr () const inline
Finds trace of this matrix.
If this matrix is not square, the compile-time error is thrown.
Returns
Trace of this matrix
Definition at line 498 of file numeric_matrix.h.
                     {
            static_assert(static_is_a_square_matrix(), "Can only find trace of a square matrix.");
            T acc = 0;
            for (size_t i = 0; i < Order; ++i) acc += vector_[i][i];
            return acc;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::Order, vt::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix(), and vt::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::tr().
transform()
template<typename T , size_t Row, size_t Col> constexpr numeric_vector_static_t< T, Row > vt::numeric_matrix_static_t< T, Row, Col >::transform (const numeric_vector_static_t< T, Col > & other) const inline constexpr
Transform input vector to output vector by left-multiplication of this matrix B_ = Ax.
Alias for writing A * x_ (which is more preferred than transform function.)
Parameters
other
Returns
Transformed vector
Definition at line 307 of file numeric_matrix.h.
{
            return operator*(other);
        }
References vt::numeric_matrix_static_t< T, Row, Col >::operator*().
transpose()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t< T, Col, Row > vt::numeric_matrix_static_t< T, Row, Col >::transpose () const inline
Returns A^T (transposed matrix of this matrix).
Returns
A^T
Definition at line 465 of file numeric_matrix.h.
{
            numeric_matrix_static_t<T, Col, Row> result;
            for (size_t i = 0; i < Row; ++i)
                for (size_t j = 0; j < Col; ++j)
                    result[j][i] = vector_[i][j];
            return result;
        }
References vt::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::inv_ut().
zeros()
template<typename T , size_t Row, size_t Col> static constexpr numeric_matrix_static_t vt::numeric_matrix_static_t< T, Row, Col >::zeros () inline static constexpr
Returns zero matrix.
Returns
Zero matrix
Definition at line 884 of file numeric_matrix.h.
{ return numeric_matrix_static_t(); }
References vt::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t().
Friends And Related Symbol Documentation
numeric_vector_static_t
template<typename T , size_t Row, size_t Col> template<typename U , size_t V> friend class numeric_vector_static_t friend
Definition at line 39 of file numeric_matrix.h.
Field Documentation
c_index
template<typename T , size_t Row, size_t Col> size_t vt::numeric_matrix_static_t< T, Row, Col >::c_index { return vector_[r_index][c_index]
Definition at line 155 of file numeric_matrix.h.
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::__attribute__(), vt::numeric_matrix_static_t< T, Row, Col >::__attribute__(), vt::numeric_matrix_static_t< T, Row, Col >::__attribute__(), and vt::numeric_matrix_static_t< T, Row, Col >::col().
const
template<typename T , size_t Row, size_t Col> size_t c_index vt::numeric_matrix_static_t< T, Row, Col >::const { return vector_[r_index][c_index]
Definition at line 158 of file numeric_matrix.h.
Order
template<typename T , size_t Row, size_t Col> constexpr size_t vt::numeric_matrix_static_t< T, Row, Col >::Order = (Row < Col) ? Row : Col static constexpr private
Definition at line 42 of file numeric_matrix.h.
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::det(), vt::numeric_matrix_static_t< T, Row, Col >::diag(), vt::numeric_matrix_static_t< T, Row, Col >::diagonals(), vt::numeric_matrix_static_t< T, Row, Col >::diagonals(), vt::numeric_matrix_static_t< T, Row, Col >::LU(), vt::numeric_matrix_static_t< T, Row, Col >::order(), and vt::numeric_matrix_static_t< T, Row, Col >::tr().
vector_
template<typename T , size_t Row, size_t Col> numeric_vector_static_t<numeric_vector_static_t<T, Col>, Row> vt::numeric_matrix_static_t< T, Row, Col >::vector_ = {} private
Definition at line 43 of file numeric_matrix.h.
Referenced by vt::numeric_matrix_static_t< T, Row, Col >::__attribute__(), vt::numeric_matrix_static_t< T, Row, Col >::__attribute__(), vt::numeric_matrix_static_t< T, Row, Col >::allocate_fill(), vt::numeric_matrix_static_t< T, Row, Col >::allocate_from(), vt::numeric_matrix_static_t< T, Row, Col >::allocate_from(), vt::numeric_matrix_static_t< T, Row, Col >::allocate_from(), vt::numeric_matrix_static_t< T, Row, Col >::allocate_zero(), vt::numeric_matrix_static_t< T, Row, Col >::begin(), vt::numeric_matrix_static_t< T, Row, Col >::begin(), vt::numeric_matrix_static_t< T, Row, Col >::col(), vt::numeric_matrix_static_t< T, Row, Col >::diag(), vt::numeric_matrix_static_t< T, Row, Col >::end(), vt::numeric_matrix_static_t< T, Row, Col >::end(), vt::numeric_matrix_static_t< T, Row, Col >::fix_zero(), vt::numeric_matrix_static_t< T, Row, Col >::float_equals(), vt::numeric_matrix_static_t< T, Row, Col >::helper_insert_unsafe(), vt::numeric_matrix_static_t< T, Row, Col >::insert(), vt::numeric_matrix_static_t< T, Row, Col >::insert(), vt::numeric_matrix_static_t< T, Row, Col >::LU(), vt::numeric_matrix_static_t< T, Row, Col >::operator*(), vt::numeric_matrix_static_t< T, Row, Col >::operator*=(), vt::numeric_matrix_static_t< T, Row, Col >::operator==(), vt::numeric_matrix_static_t< T, Row, Col >::operator==(), vt::numeric_matrix_static_t< T, Row, Col >::operator[](), vt::numeric_matrix_static_t< T, Row, Col >::slice(), vt::numeric_matrix_static_t< T, Row, Col >::steal(), vt::numeric_matrix_static_t< T, Row, Col >::swap(), vt::numeric_matrix_static_t< T, Row, Col >::tr(), and vt::numeric_matrix_static_t< T, Row, Col >::transpose().
The documentation for this class was generated from the following file:
numeric_matrix.h