VT Linear Algebra Library: vt::impl::numeric_matrix_static_lu_t< T, OSize > Class Template Reference
vt::impl::numeric_matrix_static_lu_t< T, OSize > Class Template Reference
#include <numeric_matrix.h>
Public Member Functions
numeric_matrix_static_lu_t (const numeric_matrix_static_lu_t &other)
numeric_matrix_static_lu_t (numeric_matrix_static_lu_t &&other) noexcept
numeric_matrix_static_lu_t (const Pair_t &lu)
numeric_matrix_static_lu_t (const Matrix_t &l, const Matrix_t &u)
Matrix_t & l ()
constexpr const Matrix_t & l () const
Matrix_t & u ()
constexpr const Matrix_t & u () const
Private Types
using Matrix_t = numeric_matrix_static_t< T, OSize, OSize >
using Pair_t = vt::pair< numeric_matrix_static_t< T, OSize, OSize >, numeric_matrix_static_t< T, OSize, OSize > >
Private Attributes
numeric_matrix_static_t< T, OSize, OSize > l_
numeric_matrix_static_t< T, OSize, OSize > u_
Detailed Description
template<typename T, size_t OSize>
class vt::impl::numeric_matrix_static_lu_t< T, OSize >
Wrapper class for LU-decomposed matrix comprised of L and U square matrices.
Template Parameters
T
OSize
Definition at line 1078 of file numeric_matrix.h.
Member Typedef Documentation
Matrix_t
template<typename T , size_t OSize> using vt::impl::numeric_matrix_static_lu_t< T, OSize >::Matrix_t = numeric_matrix_static_t<T, OSize, OSize> private
Definition at line 1080 of file numeric_matrix.h.
Pair_t
template<typename T , size_t OSize> using vt::impl::numeric_matrix_static_lu_t< T, OSize >::Pair_t = vt::pair<numeric_matrix_static_t<T, OSize, OSize>, numeric_matrix_static_t<T, OSize, OSize> > private
Definition at line 1081 of file numeric_matrix.h.
Constructor & Destructor Documentation
numeric_matrix_static_lu_t() [1/4]
template<typename T , size_t OSize> vt::impl::numeric_matrix_static_lu_t< T, OSize >::numeric_matrix_static_lu_t (const numeric_matrix_static_lu_t< T, OSize > & other) inline
Definition at line 1086 of file numeric_matrix.h.
: l_(other.l_), u_(other.u_) {}
numeric_matrix_static_lu_t() [2/4]
template<typename T , size_t OSize> vt::impl::numeric_matrix_static_lu_t< T, OSize >::numeric_matrix_static_lu_t (numeric_matrix_static_lu_t< T, OSize > && other) inline noexcept
Definition at line 1088 of file numeric_matrix.h.
                                                                                   : l_(vt::move(other.l_)),
                                                                                     u_(vt::move(other.u_)) {}
numeric_matrix_static_lu_t() [3/4]
template<typename T , size_t OSize> vt::impl::numeric_matrix_static_lu_t< T, OSize >::numeric_matrix_static_lu_t (const Pair_t & lu) inline explicit
Definition at line 1091 of file numeric_matrix.h.
: l_(lu.first), u_(lu.second) {}
numeric_matrix_static_lu_t() [4/4]
template<typename T , size_t OSize> vt::impl::numeric_matrix_static_lu_t< T, OSize >::numeric_matrix_static_lu_t (const Matrix_t & l, const Matrix_t & u) inline
Definition at line 1093 of file numeric_matrix.h.
: l_(l), u_(u) {}
Member Function Documentation
l() [1/2]
template<typename T , size_t OSize> Matrix_t & vt::impl::numeric_matrix_static_lu_t< T, OSize >::l () inline
L Matrix
Returns
L Matrix
Definition at line 1100 of file numeric_matrix.h.
{ return l_; }
References vt::impl::numeric_matrix_static_lu_t< T, OSize >::l_.
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::det_from_lu(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::inv().
l() [2/2]
template<typename T , size_t OSize> constexpr const Matrix_t & vt::impl::numeric_matrix_static_lu_t< T, OSize >::l () const inline constexpr
L Matrix
Returns
L Matrix
Definition at line 1107 of file numeric_matrix.h.
{ return l_; }
References vt::impl::numeric_matrix_static_lu_t< T, OSize >::l_.
u() [1/2]
template<typename T , size_t OSize> Matrix_t & vt::impl::numeric_matrix_static_lu_t< T, OSize >::u () inline
U Matrix
Returns
u Matrix
Definition at line 1114 of file numeric_matrix.h.
{ return u_; }
References vt::impl::numeric_matrix_static_lu_t< T, OSize >::u_.
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::det_from_lu(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::inv().
u() [2/2]
template<typename T , size_t OSize> constexpr const Matrix_t & vt::impl::numeric_matrix_static_lu_t< T, OSize >::u () const inline constexpr
U Matrix
Returns
u Matrix
Definition at line 1121 of file numeric_matrix.h.
{ return u_; }
References vt::impl::numeric_matrix_static_lu_t< T, OSize >::u_.
Member Data Documentation
l_
template<typename T , size_t OSize> numeric_matrix_static_t<T, OSize, OSize> vt::impl::numeric_matrix_static_lu_t< T, OSize >::l_ private
Definition at line 1082 of file numeric_matrix.h.
Referenced by vt::impl::numeric_matrix_static_lu_t< T, OSize >::l(), and vt::impl::numeric_matrix_static_lu_t< T, OSize >::l().
u_
template<typename T , size_t OSize> numeric_matrix_static_t<T, OSize, OSize> vt::impl::numeric_matrix_static_lu_t< T, OSize >::u_ private
Definition at line 1083 of file numeric_matrix.h.
Referenced by vt::impl::numeric_matrix_static_lu_t< T, OSize >::u(), and vt::impl::numeric_matrix_static_lu_t< T, OSize >::u().
The documentation for this class was generated from the following file:
include/numeric_matrix.h