VT Linear Algebra Library: vt::impl::numeric_matrix_static_t< T, Row, Col > Class Template Reference
vt::impl::numeric_matrix_static_t< T, Row, Col > Class Template Reference
#include <numeric_matrix.h>
Public Member Functions
constexpr numeric_matrix_static_t ()=default
constexpr numeric_matrix_static_t (const T &fill)
constexpr numeric_matrix_static_t (const numeric_matrix_static_t &)=default
constexpr numeric_matrix_static_t (numeric_matrix_static_t &&) noexcept=default
constexpr numeric_matrix_static_t (const T(&array)[Row][Col])
numeric_matrix_static_t (const numeric_vector_static_t< T, Col >(&vectors)[Row])
constexpr numeric_matrix_static_t (const numeric_vector_static_t< numeric_vector_static_t< T, Col >, Row > &nested)
template<size_t ORow, size_t OCol, size_t M, size_t N>
numeric_matrix_static_t (const numeric_matrix_static_t< T, ORow, OCol >(&blocks)[M][N])
template<size_t R1, size_t C1>
numeric_matrix_static_t (const numeric_matrix_static_t< T, R1, C1 > &M11, const numeric_matrix_static_t< T, R1, Col - C1 > &M12, const numeric_matrix_static_t< T, Row - R1, C1 > &M21, const numeric_matrix_static_t< T, Row - R1, Col - C1 > &M22)
template<size_t C1>
numeric_matrix_static_t (const numeric_matrix_static_t< T, Row, C1 > &A, const numeric_matrix_static_t< T, Row, Col - C1 > &B)
numeric_vector_static_t< T, Col > & operator[] (size_t index)
constexpr const numeric_vector_static_t< T, Col > & operator[] (size_t index) const
T & at (size_t r_index, size_t c_index)
constexpr const T & at (size_t r_index, size_t c_index) const
T & operator() (size_t r_index, size_t c_index)
constexpr const T & operator() (size_t r_index, size_t c_index) const
numeric_matrix_static_t & operator= (const numeric_matrix_static_t &other)
numeric_matrix_static_t & operator= (numeric_matrix_static_t &&other) noexcept
numeric_matrix_static_t & operator= (const T(&array)[Row][Col])
numeric_matrix_static_t & operator= (const numeric_vector_static_t< T, Col >(&vectors)[Row])
numeric_matrix_static_t & operator+= (const numeric_matrix_static_t &other)
numeric_matrix_static_t operator+ (const numeric_matrix_static_t &other) const
constexpr numeric_matrix_static_t add (const numeric_matrix_static_t &other) const
numeric_matrix_static_t & operator-= (const numeric_matrix_static_t &other)
numeric_matrix_static_t operator- (const numeric_matrix_static_t &other) const
constexpr numeric_matrix_static_t sub (const numeric_matrix_static_t &other) const
numeric_matrix_static_t< T, Order, Order > & operator*= (const numeric_matrix_static_t< T, Order, Order > &other)
template<size_t ORow, size_t OCol>
numeric_matrix_static_t< T, Row, OCol > matmul (const numeric_matrix_static_t< T, ORow, OCol > &other) const
template<size_t ORow, size_t OCol>
numeric_matrix_static_t< T, Row, ORow > matmul_T (const numeric_matrix_static_t< T, ORow, OCol > &other) const
template<size_t ORow, size_t OCol>
numeric_matrix_static_t< T, Row, OCol > operator* (const numeric_matrix_static_t< T, ORow, OCol > &other) const
numeric_matrix_static_t & operator*= (T rhs)
numeric_matrix_static_t operator* (T rhs) const
numeric_vector_static_t< T, Row > operator* (const numeric_vector_static_t< T, Col > &other) const
template<size_t ORow, size_t OCol>
numeric_matrix_static_t< T, Row, OCol > matmul_naive (const numeric_matrix_static_t< T, ORow, OCol > &other) const
constexpr numeric_vector_static_t< T, Row > transform (const numeric_vector_static_t< T, Col > &other) const
numeric_matrix_static_t< T, Order, Order > & operator^= (size_t n)
numeric_matrix_static_t< T, Order, Order > operator^ (size_t n)
numeric_matrix_static_t< T, Order, Order > matpow (size_t n)
numeric_matrix_static_t< T, Order, Order > matpow_naive (size_t n)
template<size_t pos_row = 0, size_t pos_col = 0, size_t ORow, size_t OCol>
numeric_matrix_static_t & insert (const numeric_matrix_static_t< T, ORow, OCol > &M)
template<size_t pos_row = 0, size_t pos_col = 0, size_t ORow, size_t OCol>
numeric_matrix_static_t & insert (const T(&array)[ORow][OCol])
template<size_t r1, size_t c1, size_t r2, size_t c2>
numeric_matrix_static_t< T, r2 - r1, c2 - c1 > slice () const
constexpr numeric_vector_static_t< T, Col > row (size_t r_index) const
numeric_vector_static_t< T, Row > col (size_t c_index) const
numeric_vector_static_t< T, Order > diag () const
numeric_matrix_static_t< T, Col, Row > transpose () const
T det () const
T tr () const
numeric_matrix_static_t inv () const
constexpr numeric_matrix_static_t inverse () const
numeric_matrix_static_lu_t< T, Order > LU () const
numeric_matrix_static_t RRE () const
template<size_t ORow, size_t OCol>
bool operator== (const numeric_matrix_static_t< T, ORow, OCol > &other) const
template<size_t ORow, size_t OCol>
bool operator== (const T(&array)[ORow][OCol]) const
template<size_t ORow, size_t OCol>
constexpr bool operator!= (const numeric_matrix_static_t< T, ORow, OCol > &other) const
template<size_t ORow, size_t OCol>
constexpr bool operator!= (const T(&array)[ORow][OCol]) const
template<size_t ORow, size_t OCol>
constexpr bool equals (const numeric_matrix_static_t< T, ORow, OCol > &other) const
template<size_t ORow, size_t OCol>
bool float_equals (const numeric_matrix_static_t< T, ORow, OCol > &other) const
template<size_t ORow, size_t OCol>
constexpr bool equals (const T(&array)[ORow][OCol]) const
iterator< numeric_vector_static_t< T, Col > > begin ()
constexpr const_iterator< numeric_vector_static_t< T, Col > > begin () const
iterator< numeric_vector_static_t< T, Col > > end ()
constexpr const_iterator< numeric_vector_static_t< T, Col > > end () const
constexpr size_t r () const
constexpr size_t c () const
constexpr size_t n () const
constexpr size_t order () const
constexpr bool is_square () const
void swap (numeric_matrix_static_t &other)
constexpr numeric_matrix_static_t copy () const
Static Public Member Functions
static numeric_matrix_static_t & iadd (numeric_matrix_static_t &C, const numeric_matrix_static_t &A, const numeric_matrix_static_t &B)
static numeric_matrix_static_t & isub (numeric_matrix_static_t &C, const numeric_matrix_static_t &A, const numeric_matrix_static_t &B)
template<size_t ORow, size_t X, size_t OCol>
static constexpr numeric_matrix_static_t< T, ORow, OCol > imatmul (numeric_matrix_static_t< T, ORow, OCol > &C, const numeric_matrix_static_t< T, ORow, X > &A, const numeric_matrix_static_t< T, X, OCol > &B)
static constexpr numeric_matrix_static_t zeros ()
static constexpr numeric_matrix_static_t ones ()
static constexpr numeric_matrix_static_t identity ()
static constexpr numeric_matrix_static_t id ()
static constexpr numeric_matrix_static_t diagonals (const T &value)
static constexpr numeric_matrix_static_t diagonals (const T(&array)[Order])
template<size_t ORow, size_t OCol>
static numeric_matrix_static_t constexpr quad (const numeric_matrix_static_t< T, ORow, OCol > M)
Private Member Functions
T det_from_lu (const numeric_matrix_static_lu_t< T, Order > &lu) const
void fix_zero ()
void allocate_zero ()
void allocate_fill (T fill)
void allocate_from (const numeric_matrix_static_t &other)
void allocate_from (const T(&array)[Row][Col])
void allocate_from (const numeric_vector_static_t< T, Col >(&vectors)[Row])
void steal (numeric_matrix_static_t &&other)
template<size_t ORow, size_t OCol, size_t M, size_t N>
void helper_insert_major (size_t pos_row, const numeric_matrix_static_t< T, ORow, OCol >(&blocks)[M][N])
template<size_t ORow, size_t OCol, size_t M, size_t N>
void helper_insert_minor (size_t pos_row, size_t pos_col, const numeric_matrix_static_t< T, ORow, OCol >(&blocks)[M][N])
template<size_t ORow, size_t OCol>
void helper_insert_unsafe (size_t pos_row, size_t pos_col, const numeric_matrix_static_t< T, ORow, OCol > &M)
Static Private Member Functions
static constexpr bool static_is_a_square_matrix ()
static constexpr bool is_multiple_of_2 (size_t x)
static size_t closest_2 (size_t x)
template<size_t ORow, size_t X, size_t OCol>
static numeric_matrix_static_t< T, ORow, OCol > & mm_naive (numeric_matrix_static_t< T, ORow, OCol > &C, const numeric_matrix_static_t< T, ORow, X > &A, const numeric_matrix_static_t< T, X, OCol > &B)
template<size_t ORow, size_t X, size_t OCol>
static numeric_matrix_static_t< T, ORow, OCol > & mm_naive_T (numeric_matrix_static_t< T, ORow, OCol > &C, const numeric_matrix_static_t< T, ORow, X > &A, const numeric_matrix_static_t< T, OCol, X > &B)
template<size_t ORow, size_t X, size_t OCol>
static constexpr numeric_matrix_static_t< T, ORow, OCol > & mm_strassen (numeric_matrix_static_t< T, ORow, OCol > &C, const numeric_matrix_static_t< T, ORow, X > &A, const numeric_matrix_static_t< T, X, OCol > &B)
template<size_t OSize>
static numeric_matrix_static_t< T, OSize, OSize > inv_lt (numeric_matrix_static_t< T, OSize, OSize > &L)
template<size_t OSize>
static numeric_matrix_static_t< T, OSize, OSize > inv_ut (numeric_matrix_static_t< T, OSize, OSize > &U)
Private Attributes
numeric_vector_static_t< numeric_vector_static_t< T, Col >, Row > vector_ = {}
Static Private Attributes
static constexpr size_t Order = (Row < Col) ? Row : Col
Friends
template<typename U , size_t V>
class numeric_vector_static_t
Detailed Description
template<typename T, size_t Row, size_t Col>
class vt::impl::numeric_matrix_static_t< T, Row, Col >
Numeric matrix template class where the dimension must be known at compile-time and can't be changed by any ways during runtime to prevent unexpected behavior or errors. This avoid heap usages for safety-critical and performance-critical systems.
Template Parameters
T data type
Row row dimension
Col column dimension
Definition at line 32 of file numeric_matrix.h.
Constructor & Destructor Documentation
numeric_matrix_static_t() [1/10]
template<typename T , size_t Row, size_t Col> constexpr vt::impl::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t () constexpr default
Default constructor, initializes to zero
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::copy(), vt::impl::numeric_matrix_static_t< T, Row, Col >::diagonals(), vt::impl::numeric_matrix_static_t< T, Row, Col >::diagonals(), vt::impl::numeric_matrix_static_t< T, Row, Col >::inv(), vt::impl::numeric_matrix_static_t< T, Row, Col >::ones(), vt::impl::numeric_matrix_static_t< T, Row, Col >::operator^(), vt::impl::numeric_matrix_static_t< T, Row, Col >::quad(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::zeros().
numeric_matrix_static_t() [2/10]
template<typename T , size_t Row, size_t Col> constexpr vt::impl::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t (const T & fill) inline explicit constexpr
Fill constructor, initializes to fill value
Parameters
fill Fill value
Definition at line 57 of file numeric_matrix.h.
                    : vector_(
                    numeric_vector_static_t<numeric_vector_static_t<T, Col>, Row>(numeric_vector_static_t<T, Col>(fill))
            ) {}
numeric_matrix_static_t() [3/10]
template<typename T , size_t Row, size_t Col> constexpr vt::impl::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t (const numeric_matrix_static_t< T, Row, Col > &) constexpr default
Copy constructor
Parameters
other Other matrix
numeric_matrix_static_t() [4/10]
template<typename T , size_t Row, size_t Col> constexpr vt::impl::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t (numeric_matrix_static_t< T, Row, Col > &&) constexpr default noexcept
Move constructor
Parameters
other Other vector
numeric_matrix_static_t() [5/10]
template<typename T , size_t Row, size_t Col> constexpr vt::impl::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t (const T(&) array[Row][Col]) inline explicit constexpr
Array constructor, construct from array
Parameters
array Array of entries
Definition at line 81 of file numeric_matrix.h.
                    : vector_(vt::detail::make_nested(array)) {}
numeric_matrix_static_t() [6/10]
template<typename T , size_t Row, size_t Col> vt::impl::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t (const numeric_vector_static_t< T, Col >(&) vectors[Row]) inline explicit
Array of vectors as rows constructor, construct from array
Parameters
vectors Array of rows
Definition at line 89 of file numeric_matrix.h.
{
                allocate_from(vectors);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::allocate_from().
numeric_matrix_static_t() [7/10]
template<typename T , size_t Row, size_t Col> constexpr vt::impl::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t (const numeric_vector_static_t< numeric_vector_static_t< T, Col >, Row > & nested) inline explicit constexpr
Nested vector constructor
Parameters
nested Nested vector
Definition at line 98 of file numeric_matrix.h.
                    : vector_(nested) {}
numeric_matrix_static_t() [8/10]
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol, size_t M, size_t N> vt::impl::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t (const numeric_matrix_static_t< T, ORow, OCol >(&) blocks[M][N]) inline explicit
Block matrix constructor
Template Parameters
ORow
OCol
M
N
Parameters
blocks Array of blocks
Definition at line 112 of file numeric_matrix.h.
{
                helper_insert_major(0, blocks);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::helper_insert_major().
numeric_matrix_static_t() [9/10]
template<typename T , size_t Row, size_t Col> template<size_t R1, size_t C1> vt::impl::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t (const numeric_matrix_static_t< T, R1, C1 > & M11, const numeric_matrix_static_t< T, R1, Col - C1 > & M12, const numeric_matrix_static_t< T, Row - R1, C1 > & M21, const numeric_matrix_static_t< T, Row - R1, Col - C1 > & M22) inline
Quad-matrix constructor, construct M from M11, M12, M21, M22
Template Parameters
R1
C1
Parameters
M11 Upper-left matrix
M12 Upper-right matrix
M21 Lower-left matrix
M22 Lower-right matrix
Definition at line 127 of file numeric_matrix.h.
{
                insert<0, 0>(M11);
                insert<0, C1>(M12);
                insert<R1, 0>(M21);
                insert<R1, C1>(M22);
            }
numeric_matrix_static_t() [10/10]
template<typename T , size_t Row, size_t Col> template<size_t C1> vt::impl::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t (const numeric_matrix_static_t< T, Row, C1 > & A, const numeric_matrix_static_t< T, Row, Col - C1 > & B) inline
B matrix constructor, construct M from [A | B]
Template Parameters
C1 Main column
Parameters
A Main matrix
B Augment part
Definition at line 145 of file numeric_matrix.h.
{
                insert<0, 0>(A);
                insert<0, C1>(B);
            }
Member Function Documentation
operator[]() [1/2]
template<typename T , size_t Row, size_t Col> numeric_vector_static_t< T, Col > & vt::impl::numeric_matrix_static_t< T, Row, Col >::operator[] (size_t index) inline
Definition at line 151 of file numeric_matrix.h.
{ return vector_[index]; }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
operator[]() [2/2]
template<typename T , size_t Row, size_t Col> constexpr const numeric_vector_static_t< T, Col > & vt::impl::numeric_matrix_static_t< T, Row, Col >::operator[] (size_t index) const inline constexpr
Definition at line 154 of file numeric_matrix.h.
{ return vector_[index]; }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
at() [1/2]
template<typename T , size_t Row, size_t Col> T & vt::impl::numeric_matrix_static_t< T, Row, Col >::at (size_t r_index, size_t c_index) inline
Definition at line 156 of file numeric_matrix.h.
{ return vector_[r_index][c_index]; };
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::operator()(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::operator()().
at() [2/2]
template<typename T , size_t Row, size_t Col> constexpr const T & vt::impl::numeric_matrix_static_t< T, Row, Col >::at (size_t r_index, size_t c_index) const inline constexpr
Definition at line 159 of file numeric_matrix.h.
{ return vector_[r_index][c_index]; };
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
operator()() [1/2]
template<typename T , size_t Row, size_t Col> T & vt::impl::numeric_matrix_static_t< T, Row, Col >::operator() (size_t r_index, size_t c_index) inline
Definition at line 161 of file numeric_matrix.h.
{ return at(r_index, c_index); }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::at().
operator()() [2/2]
template<typename T , size_t Row, size_t Col> constexpr const T & vt::impl::numeric_matrix_static_t< T, Row, Col >::operator() (size_t r_index, size_t c_index) const inline constexpr
Definition at line 163 of file numeric_matrix.h.
{
                return at(r_index, c_index);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::at().
operator=() [1/4]
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t & vt::impl::numeric_matrix_static_t< T, Row, Col >::operator= (const numeric_matrix_static_t< T, Row, Col > & other) inline
Definition at line 167 of file numeric_matrix.h.
{
                if (this != &other) allocate_from(other);
                return *this;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::allocate_from().
operator=() [2/4]
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t & vt::impl::numeric_matrix_static_t< T, Row, Col >::operator= (numeric_matrix_static_t< T, Row, Col > && other) inline noexcept
Definition at line 172 of file numeric_matrix.h.
{
                if (this != &other) steal(vt::move(other));
                return *this;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::steal().
operator=() [3/4]
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t & vt::impl::numeric_matrix_static_t< T, Row, Col >::operator= (const T(&) array[Row][Col]) inline
Definition at line 177 of file numeric_matrix.h.
{
                allocate_from(array);
                return *this;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::allocate_from().
operator=() [4/4]
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t & vt::impl::numeric_matrix_static_t< T, Row, Col >::operator= (const numeric_vector_static_t< T, Col >(&) vectors[Row]) inline
Definition at line 182 of file numeric_matrix.h.
{
                allocate_from(vectors);
                return *this;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::allocate_from().
operator+=()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t & vt::impl::numeric_matrix_static_t< T, Row, Col >::operator+= (const numeric_matrix_static_t< T, Row, Col > & other) inline
Definition at line 187 of file numeric_matrix.h.
{
                return iadd(*this, *this, other);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::iadd().
operator+()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t vt::impl::numeric_matrix_static_t< T, Row, Col >::operator+ (const numeric_matrix_static_t< T, Row, Col > & other) const inline
Definition at line 191 of file numeric_matrix.h.
{
                numeric_matrix_static_t tmp(*this);
                tmp.operator+=(other);
                return tmp;
            }
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::add().
add()
template<typename T , size_t Row, size_t Col> constexpr numeric_matrix_static_t vt::impl::numeric_matrix_static_t< T, Row, Col >::add (const numeric_matrix_static_t< T, Row, Col > & other) const inline constexpr
Definition at line 197 of file numeric_matrix.h.
{
                return operator+(other);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::operator+().
iadd()
template<typename T , size_t Row, size_t Col> static numeric_matrix_static_t & vt::impl::numeric_matrix_static_t< T, Row, Col >::iadd (numeric_matrix_static_t< T, Row, Col > & C, const numeric_matrix_static_t< T, Row, Col > & A, const numeric_matrix_static_t< T, Row, Col > & B) inline static
In-place C = A + B_ tools
Parameters
C
A
B
Returns
C
Definition at line 209 of file numeric_matrix.h.
{
                for (size_t i = 0; i < Row; ++i)
                    for (size_t j = 0; j < Col; ++j)
                        C[i][j] = A[i][j] + B[i][j];
                return C;
            }
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::operator+=().
operator-=()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t & vt::impl::numeric_matrix_static_t< T, Row, Col >::operator-= (const numeric_matrix_static_t< T, Row, Col > & other) inline
Definition at line 218 of file numeric_matrix.h.
{
                return isub(*this, *this, other);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::isub().
operator-()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t vt::impl::numeric_matrix_static_t< T, Row, Col >::operator- (const numeric_matrix_static_t< T, Row, Col > & other) const inline
Definition at line 222 of file numeric_matrix.h.
{
                numeric_matrix_static_t tmp(*this);
                tmp.operator-=(other);
                return tmp;
            }
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::sub().
sub()
template<typename T , size_t Row, size_t Col> constexpr numeric_matrix_static_t vt::impl::numeric_matrix_static_t< T, Row, Col >::sub (const numeric_matrix_static_t< T, Row, Col > & other) const inline constexpr
Definition at line 228 of file numeric_matrix.h.
{
                return operator-(other);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::operator-().
isub()
template<typename T , size_t Row, size_t Col> static numeric_matrix_static_t & vt::impl::numeric_matrix_static_t< T, Row, Col >::isub (numeric_matrix_static_t< T, Row, Col > & C, const numeric_matrix_static_t< T, Row, Col > & A, const numeric_matrix_static_t< T, Row, Col > & B) inline static
In-place C = A - B_ tools
Parameters
C
A
B
Returns
C
Definition at line 240 of file numeric_matrix.h.
{
                for (size_t i = 0; i < Row; ++i)
                    for (size_t j = 0; j < Col; ++j)
                        C[i][j] = A[i][j] - B[i][j];
                return C;
            }
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::operator-=().
operator*=() [1/2]
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t< T, Order, Order > & vt::impl::numeric_matrix_static_t< T, Row, Col >::operator*= (const numeric_matrix_static_t< T, Order, Order > & other) inline
Definition at line 250 of file numeric_matrix.h.
{
                steal(vt::move(operator*(other)));
                return *this;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::steal().
matmul()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> numeric_matrix_static_t< T, Row, OCol > vt::impl::numeric_matrix_static_t< T, Row, Col >::matmul (const numeric_matrix_static_t< T, ORow, OCol > & other) const inline
Definition at line 256 of file numeric_matrix.h.
{
                return operator*(other);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::operator*().
matmul_T()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> numeric_matrix_static_t< T, Row, ORow > vt::impl::numeric_matrix_static_t< T, Row, Col >::matmul_T (const numeric_matrix_static_t< T, ORow, OCol > & other) const inline
Multiply with another matrix transposed (i.e., A * B^T).
Template Parameters
ORow
OCol
Parameters
other
Returns
Definition at line 269 of file numeric_matrix.h.
{
                numeric_matrix_static_t<T, Row, ORow> C;
                return mm_naive_T(C, *this, other);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::mm_naive_T().
operator*() [1/3]
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> numeric_matrix_static_t< T, Row, OCol > vt::impl::numeric_matrix_static_t< T, Row, Col >::operator* (const numeric_matrix_static_t< T, ORow, OCol > & other) const inline
Definition at line 275 of file numeric_matrix.h.
{
                numeric_matrix_static_t<T, Row, OCol> C;
                return imatmul(C, *this, other);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::imatmul().
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::matmul(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::transform().
operator*=() [2/2]
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t & vt::impl::numeric_matrix_static_t< T, Row, Col >::operator*= (T rhs) inline
Definition at line 280 of file numeric_matrix.h.
{
                for (auto &x: vector_) x *= rhs;
                return *this;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
operator*() [2/3]
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t vt::impl::numeric_matrix_static_t< T, Row, Col >::operator* (T rhs) const inline
Definition at line 285 of file numeric_matrix.h.
{
                numeric_matrix_static_t tmp(*this);
                tmp.operator*=(rhs);
                return tmp;
            }
operator*() [3/3]
template<typename T , size_t Row, size_t Col> numeric_vector_static_t< T, Row > vt::impl::numeric_matrix_static_t< T, Row, Col >::operator* (const numeric_vector_static_t< T, Col > & other) const inline
Definition at line 291 of file numeric_matrix.h.
{
                numeric_vector_static_t<T, Row> tmp;
                for (size_t i = 0; i < Row; ++i) tmp[i] = vector_[i].dot(other);
                return tmp;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
imatmul()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t X, size_t OCol> static constexpr numeric_matrix_static_t< T, ORow, OCol > vt::impl::numeric_matrix_static_t< T, Row, Col >::imatmul (numeric_matrix_static_t< T, ORow, OCol > & C, const numeric_matrix_static_t< T, ORow, X > & A, const numeric_matrix_static_t< T, X, OCol > & B) inline static constexpr
In-place C = AB tools
Template Parameters
ORow
X
OCol
Parameters
C
A
B
Returns
C
Definition at line 309 of file numeric_matrix.h.
{
                return mm_naive(C, A, B);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::mm_naive().
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::operator*().
matmul_naive()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> numeric_matrix_static_t< T, Row, OCol > vt::impl::numeric_matrix_static_t< T, Row, Col >::matmul_naive (const numeric_matrix_static_t< T, ORow, OCol > & other) const inline
Multiply this matrix with the other matrix in naive O(n^3) way (default multiplication method).
Template Parameters
ORow
OCol
Parameters
other
Returns
Multiplied matrix
Definition at line 325 of file numeric_matrix.h.
{
                numeric_matrix_static_t<T, Row, OCol> C;
                return mm_naive(C, *this, other);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::mm_naive().
transform()
template<typename T , size_t Row, size_t Col> constexpr numeric_vector_static_t< T, Row > vt::impl::numeric_matrix_static_t< T, Row, Col >::transform (const numeric_vector_static_t< T, Col > & other) const inline constexpr
Transform input vector to output vector by left-multiplication of this matrix B_ = Ax.
Alias for writing A * x_ (which is more preferred than transform function.)
Parameters
other
Returns
Transformed vector
Definition at line 337 of file numeric_matrix.h.
{
                return operator*(other);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::operator*().
operator^=()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t< T, Order, Order > & vt::impl::numeric_matrix_static_t< T, Row, Col >::operator^= (size_t n) inline
Definition at line 341 of file numeric_matrix.h.
{
                static_assert(static_is_a_square_matrix(), "Non-square matrix can\'t use power operator.");
                steal(vt::move(operator^(n)));
                return *this;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::n(), vt::impl::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::steal().
operator^()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t< T, Order, Order > vt::impl::numeric_matrix_static_t< T, Row, Col >::operator^ (size_t n) inline
Definition at line 347 of file numeric_matrix.h.
{
                static_assert(static_is_a_square_matrix(), "Non-square matrix can\'t use power operator.");
                if (n == 0) return identity();
                if (n == 1) return numeric_matrix_static_t(*this);
                numeric_matrix_static_t<T, Order, Order> base(*this);
                numeric_matrix_static_t<T, Order, Order> product(vt::move(identity()));
                while (n > 0) {
                    if (n % 2 == 1) product.operator*=(base);
                    if (n > 1) base *= base;
                    n >>= 1;
                }
                return product;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::identity(), vt::impl::numeric_matrix_static_t< T, Row, Col >::n(), vt::impl::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix().
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::matpow().
matpow()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t< T, Order, Order > vt::impl::numeric_matrix_static_t< T, Row, Col >::matpow (size_t n) inline
Calculate a nth power of this matrix in O(log n * mulO). Must be a square matrix.
If this matrix is not square, the compile-time error is thrown.
Parameters
n
Returns
A^n
Definition at line 368 of file numeric_matrix.h.
{
                static_assert(static_is_a_square_matrix(), "Non-square matrix can\'t use power operator.");
                return operator^(n);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::n(), vt::impl::numeric_matrix_static_t< T, Row, Col >::operator^(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix().
matpow_naive()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t< T, Order, Order > vt::impl::numeric_matrix_static_t< T, Row, Col >::matpow_naive (size_t n) inline
Calculate a nth power of this matrix in O(n * mulO) naively. Must be a square matrix.
If this matrix is not square, the compile-time error is thrown.
Parameters
n
Returns
A^n
Definition at line 380 of file numeric_matrix.h.
{
                static_assert(static_is_a_square_matrix(), "Non-square matrix can\'t use power operator.");
                numeric_matrix_static_t<T, Order, Order> product = vt::move(id());
                for (size_t i = 0; i < n; ++i) product *= *this;
                return product;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::n(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix().
insert() [1/2]
template<typename T , size_t Row, size_t Col> template<size_t pos_row = 0, size_t pos_col = 0, size_t ORow, size_t OCol> numeric_matrix_static_t & vt::impl::numeric_matrix_static_t< T, Row, Col >::insert (const numeric_matrix_static_t< T, ORow, OCol > & M) inline
Insert the other matrix into current matrix, returning reference to the current matrix.
If insertion is not valid, the compile-time error is thrown.
Template Parameters
pos_row Row position to insert, default to 0
pos_col Column position to insert, default to 0
ORow Other matrix's row size
OCol Other matrix's column size
Parameters
M Other matrix
Returns
Reference to this matrix
Definition at line 399 of file numeric_matrix.h.
{
                static_assert(pos_row < Row, "Insertion failed! Start row is out of range.");
                static_assert(pos_col < Col, "Insertion failed! Start column is out of range.");
                static_assert(pos_row + ORow <= Row, "Insertion failed! Stop row is out of range.");
                static_assert(pos_col + OCol <= Col, "Insertion failed! Stop column is out of range.");
                for (size_t i = 0; i < ORow; ++i)
                    for (size_t j = 0; j < OCol; ++j)
                        vector_[pos_row + i][pos_col + j] = M[i][j];
                return *this;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
insert() [2/2]
template<typename T , size_t Row, size_t Col> template<size_t pos_row = 0, size_t pos_col = 0, size_t ORow, size_t OCol> numeric_matrix_static_t & vt::impl::numeric_matrix_static_t< T, Row, Col >::insert (const T(&) array[ORow][OCol]) inline
Insert the other matrix into current matrix, returning reference to the current matrix.
If insertion is not valid, the compile-time error is thrown.
Template Parameters
pos_row Row position to insert, default to 0
pos_col Column position to insert, default to 0
ORow Other matrix's row size
OCol Other matrix's column size
Parameters
array Other matrix as 2D array
Returns
Reference to this matrix
Definition at line 422 of file numeric_matrix.h.
{
                static_assert(pos_row < Row, "Insertion failed! Start row is out of range.");
                static_assert(pos_col < Col, "Insertion failed! Start column is out of range.");
                static_assert(pos_row + ORow <= Row, "Insertion failed! Stop row is out of range.");
                static_assert(pos_col + OCol <= Col, "Insertion failed! Stop column is out of range.");
                for (size_t i = 0; i < ORow; ++i)
                    for (size_t j = 0; j < OCol; ++j)
                        vector_[pos_row + i][pos_col + j] = array[i][j];
                return *this;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
slice()
template<typename T , size_t Row, size_t Col> template<size_t r1, size_t c1, size_t r2, size_t c2> numeric_matrix_static_t< T, r2 - r1, c2 - c1 > vt::impl::numeric_matrix_static_t< T, Row, Col >::slice () const inline
Slice current matrix.
Template Parameters
r1 Row position from
c1 Column position from
r2 Row position to
c2 Colum position to
Returns
A slice of current matrix
Definition at line 443 of file numeric_matrix.h.
{
                static_assert(r1 < r2, "Start row must be less than stop row.");
                static_assert(c1 < c2, "Start column must be less than stop column.");
                static_assert(r2 <= Row, "Row is out of range.");
                static_assert(c2 <= Col, "Column is out of range.");
                numeric_matrix_static_t<T, r2 - r1, c2 - c1> result;
                for (size_t i = 0; i < r2 - r1; ++i)
                    for (size_t j = 0; j < c2 - c1; ++j)
                        result[i][j] = vector_[r1 + i][c1 + j];
                return result;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
row()
template<typename T , size_t Row, size_t Col> constexpr numeric_vector_static_t< T, Col > vt::impl::numeric_matrix_static_t< T, Row, Col >::row (size_t r_index) const inline constexpr
Returns row at index as vector.
WARNING: Doesn't have out of range check!
Parameters
r_index Row index
Returns
Row at index as vector
Definition at line 462 of file numeric_matrix.h.
{
                return numeric_vector_static_t<T, Col>(operator[](r_index));
            }
col()
template<typename T , size_t Row, size_t Col> numeric_vector_static_t< T, Row > vt::impl::numeric_matrix_static_t< T, Row, Col >::col (size_t c_index) const inline
Returns column at index as vector.
WARNING: Doesn't have out of range check!
Parameters
c_index Column index
Returns
Column at index as vector
Definition at line 473 of file numeric_matrix.h.
{
                numeric_vector_static_t<T, Row> result;
                for (size_t i = 0; i < Row; ++i) result[i] = vector_[i][c_index];
                return result;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
diag()
template<typename T , size_t Row, size_t Col> numeric_vector_static_t< T, Order > vt::impl::numeric_matrix_static_t< T, Row, Col >::diag () const inline
Returns main diagonal entries as vector.
Returns
Main diagonal entries as vector
Definition at line 484 of file numeric_matrix.h.
{
                numeric_vector_static_t<T, Order> result;
                for (size_t i = 0; i < Order; ++i) result[i] = vector_[i][i];
                return result;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::Order, and vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
transpose()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t< T, Col, Row > vt::impl::numeric_matrix_static_t< T, Row, Col >::transpose () const inline
Returns A^T (transposed matrix of this matrix).
Returns
A^T
Definition at line 495 of file numeric_matrix.h.
{
                numeric_matrix_static_t<T, Col, Row> result;
                for (size_t i = 0; i < Row; ++i)
                    for (size_t j = 0; j < Col; ++j)
                        result[j][i] = vector_[i][j];
                return result;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::inv_ut().
det()
template<typename T , size_t Row, size_t Col> T vt::impl::numeric_matrix_static_t< T, Row, Col >::det () const inline
Finds determinant of this matrix.
If this matrix is not square, the compile-time error is thrown.
Returns
Determinant of this matrix
Definition at line 509 of file numeric_matrix.h.
{
                static_assert(static_is_a_square_matrix(), "Can only find determinant of a square matrix.");
                return det_from_lu(LU());
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::det_from_lu(), vt::impl::numeric_matrix_static_t< T, Row, Col >::LU(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix().
Referenced by vt::det(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::det_from_lu().
det_from_lu()
template<typename T , size_t Row, size_t Col> T vt::impl::numeric_matrix_static_t< T, Row, Col >::det_from_lu (const numeric_matrix_static_lu_t< T, Order > & lu) const inline private
Definition at line 515 of file numeric_matrix.h.
{
                T det = 1;
                size_t r_swaps = 0;
                for (size_t i = 0; i < Order; ++i) {
                    det *= lu.u()[i][i];
                    if (lu.u()[i][i] == 0) return 0;
                    if (lu.l()[i][i] != 1) r_swaps++;
                }
                return (r_swaps % 2 == 0) ? det : -det;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::det(), vt::impl::numeric_matrix_static_lu_t< T, OSize >::l(), vt::impl::numeric_matrix_static_t< T, Row, Col >::Order, and vt::impl::numeric_matrix_static_lu_t< T, OSize >::u().
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::det(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::inv().
tr()
template<typename T , size_t Row, size_t Col> T vt::impl::numeric_matrix_static_t< T, Row, Col >::tr () const inline
Finds trace of this matrix.
If this matrix is not square, the compile-time error is thrown.
Returns
Trace of this matrix
Definition at line 534 of file numeric_matrix.h.
{
                static_assert(static_is_a_square_matrix(), "Can only find trace of a square matrix.");
                T acc = 0;
                for (size_t i = 0; i < Order; ++i) acc += vector_[i][i];
                return acc;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::Order, vt::impl::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::tr().
inv()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t vt::impl::numeric_matrix_static_t< T, Row, Col >::inv () const inline
Finds inverse of this matrix.
If this matrix is not square, the compile-time error is thrown.
If inverse doesn't exist (det = 0), the zero matrix is returned.
Returns
Inverse of this matrix
Definition at line 549 of file numeric_matrix.h.
{
                static_assert(static_is_a_square_matrix(), "Can only find inverse of a square matrix.");
                numeric_matrix_static_lu_t<T, Order> lu = vt::move(LU());
                if (abs(det_from_lu(lu)) > 1e-10) return (inv_ut(lu.u()) * inv_lt(lu.l()));
                return numeric_matrix_static_t();
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::det_from_lu(), vt::impl::numeric_matrix_static_t< T, Row, Col >::inv_lt(), vt::impl::numeric_matrix_static_t< T, Row, Col >::inv_ut(), vt::impl::numeric_matrix_static_lu_t< T, OSize >::l(), vt::impl::numeric_matrix_static_t< T, Row, Col >::LU(), vt::impl::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t(), vt::impl::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix(), and vt::impl::numeric_matrix_static_lu_t< T, OSize >::u().
Referenced by vt::inv(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::inverse().
inverse()
template<typename T , size_t Row, size_t Col> constexpr numeric_matrix_static_t vt::impl::numeric_matrix_static_t< T, Row, Col >::inverse () const inline constexpr
Finds inverse of this matrix.
If this matrix is not square, the compile-time error is thrown.
Returns
Inverse of this matrix
Definition at line 562 of file numeric_matrix.h.
{ return inv(); }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::inv().
LU()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_lu_t< T, Order > vt::impl::numeric_matrix_static_t< T, Row, Col >::LU () const inline
Finds LU-decomposition of this matrix.
If this matrix is not square, the compile-time error is thrown.
Returns
LU-decomposition of this matrix
Definition at line 570 of file numeric_matrix.h.
{
                static_assert(static_is_a_square_matrix(), "Can only find LU decomposition of a square matrix.");
                numeric_matrix_static_t<T, Order, Order> lower;
                numeric_matrix_static_t<T, Order, Order> upper;
                for (size_t i = 0; i < Order; ++i) {
                    for (size_t k = 0; k < Order; ++k) {
                        T sum_ = 0;
                        for (size_t j = 0; j < i; ++j) sum_ += lower[i][j] * upper[j][k];
                        upper[i][k] = vector_[i][k] - sum_;
                    }
                    for (size_t k = i; k < Order; ++k) {
                        if (i == k) lower[i][i] = 1;
                        else {
                            T sum_ = 0;
                            for (size_t j = 0; j < i; ++j) sum_ += lower[k][j] * upper[j][i];
                            lower[k][i] = (vector_[k][i] - sum_) / upper[i][i];
                        }
                    }
                }
                return {lower, upper};
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::Order, vt::impl::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::det(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::inv().
RRE()
template<typename T , size_t Row, size_t Col> numeric_matrix_static_t vt::impl::numeric_matrix_static_t< T, Row, Col >::RRE () const inline
Finds Row-Reduced Echlon (RRE) form of this matrix.
If this matrix is not square, the compile-time error is thrown.
Returns
Row-Reduced Echlon form of this matrix
Definition at line 598 of file numeric_matrix.h.
{
                numeric_matrix_static_t m(*this);
                size_t lead = 0;
                for (size_t r = 0; r < Row; ++r) {
                    if (lead >= Col) return m;
                    size_t i;
                    for (i = r; m[i][lead] == 0;) {
                        ++i;
                        if (i == Row) {
                            i = r;
                            ++lead;
                            if (lead == Col) return m;
                        }
                    }
                    m[i].swap(m[r]);
                    T val = m[r][lead];
                    for (size_t j = 0; j < Col; ++j) m[r][j] /= val;
                    for (i = 0; i < Row; ++i) {
                        if (i != r) {
                            val = m[i][lead];
                            for (size_t j = 0; j < Col; ++j)
                                m[i][j] -= val * m[r][j];
                        }
                    }
                    ++lead;
                }
                m.fix_zero();
                return m;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::fix_zero(), vt::impl::numeric_matrix_static_t< T, Row, Col >::r(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::swap().
Referenced by vt::RRE().
operator==() [1/2]
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> bool vt::impl::numeric_matrix_static_t< T, Row, Col >::operator== (const numeric_matrix_static_t< T, ORow, OCol > & other) const inline
Checks equality of this matrix and the other matrix.
Template Parameters
ORow
OCol
Parameters
other Other matrix
Returns
Definition at line 637 of file numeric_matrix.h.
{
                if (this == &other) return true;
                if (Row != ORow || Col != OCol) return false;
                for (size_t i = 0; i < Row; ++i) if (vector_[i] != other.vector_[i]) return false;
                return true;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::equals(), vt::impl::numeric_matrix_static_t< T, Row, Col >::equals(), vt::impl::numeric_matrix_static_t< T, Row, Col >::operator!=(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::operator!=().
operator==() [2/2]
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> bool vt::impl::numeric_matrix_static_t< T, Row, Col >::operator== (const T(&) array[ORow][OCol]) const inline
Checks equality of this matrix and the other matrix.
Template Parameters
ORow
OCol
Parameters
array Other matrix as array
Returns
Definition at line 653 of file numeric_matrix.h.
{
                if (Row != ORow || Col != OCol) return false;
                for (size_t i = 0; i < Row; ++i) if (vector_[i] != array[i]) return false;
                return true;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
operator!=() [1/2]
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> constexpr bool vt::impl::numeric_matrix_static_t< T, Row, Col >::operator!= (const numeric_matrix_static_t< T, ORow, OCol > & other) const inline constexpr
Checks inequality of this matrix and the other matrix.
Template Parameters
ORow
OCol
Parameters
other Other matrix
Returns
Definition at line 668 of file numeric_matrix.h.
{
                return !operator==(other);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::operator==().
operator!=() [2/2]
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> constexpr bool vt::impl::numeric_matrix_static_t< T, Row, Col >::operator!= (const T(&) array[ORow][OCol]) const inline constexpr
Checks inequality of this matrix and the other matrix.
Template Parameters
ORow
OCol
Parameters
array Other matrix as array
Returns
Definition at line 681 of file numeric_matrix.h.
{ return !operator==(array); }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::operator==().
equals() [1/2]
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> constexpr bool vt::impl::numeric_matrix_static_t< T, Row, Col >::equals (const numeric_matrix_static_t< T, ORow, OCol > & other) const inline constexpr
Checks equality of this matrix and the other matrix.
Template Parameters
ORow
OCol
Parameters
other Other matrix
Returns
Definition at line 692 of file numeric_matrix.h.
{
                return operator==(other);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::operator==().
float_equals()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> bool vt::impl::numeric_matrix_static_t< T, Row, Col >::float_equals (const numeric_matrix_static_t< T, ORow, OCol > & other) const inline
Checks equality of this matrix and the other matrix with float/double threshold using equation abs(x_ - y) < threshold for equality.
Template Parameters
ORow
OCol
Parameters
other Other matrix
Returns
Definition at line 705 of file numeric_matrix.h.
{
                if (this == &other) return true;
                if (Row != ORow || Col != OCol) return false;
                for (size_t i = 0; i < Row; ++i) if (!vector_[i].float_equals(other.vector_[i])) return false;
                return true;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::float_equals(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::float_equals().
equals() [2/2]
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> constexpr bool vt::impl::numeric_matrix_static_t< T, Row, Col >::equals (const T(&) array[ORow][OCol]) const inline constexpr
Checks equality of this matrix and the other matrix.
Template Parameters
ORow
OCol
Parameters
array Other matrix as array
Returns
Definition at line 721 of file numeric_matrix.h.
{ return operator==(array); }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::operator==().
begin() [1/2]
template<typename T , size_t Row, size_t Col> iterator< numeric_vector_static_t< T, Col > > vt::impl::numeric_matrix_static_t< T, Row, Col >::begin () inline
Returns an iterator to matrix's first row.
Returns
An iterator to matrix's first row
Definition at line 728 of file numeric_matrix.h.
{ return vector_.begin(); }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
begin() [2/2]
template<typename T , size_t Row, size_t Col> constexpr const_iterator< numeric_vector_static_t< T, Col > > vt::impl::numeric_matrix_static_t< T, Row, Col >::begin () const inline constexpr
Returns an iterator to matrix's first row.
Returns
An iterator to matrix's first row
Definition at line 735 of file numeric_matrix.h.
{ return vector_.begin(); }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
end() [1/2]
template<typename T , size_t Row, size_t Col> iterator< numeric_vector_static_t< T, Col > > vt::impl::numeric_matrix_static_t< T, Row, Col >::end () inline
Returns an iterator to matrix's last row.
Returns
An iterator to matrix's last row
Definition at line 742 of file numeric_matrix.h.
{ return vector_.end(); }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
end() [2/2]
template<typename T , size_t Row, size_t Col> constexpr const_iterator< numeric_vector_static_t< T, Col > > vt::impl::numeric_matrix_static_t< T, Row, Col >::end () const inline constexpr
Returns an iterator to matrix's last row.
Returns
An iterator to matrix's last row
Definition at line 749 of file numeric_matrix.h.
{ return vector_.end(); }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
r()
template<typename T , size_t Row, size_t Col> constexpr size_t vt::impl::numeric_matrix_static_t< T, Row, Col >::r () const inline constexpr
Returns number of rows.
Returns
Number of rows
Definition at line 756 of file numeric_matrix.h.
{ return Row; }
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::RRE().
c()
template<typename T , size_t Row, size_t Col> constexpr size_t vt::impl::numeric_matrix_static_t< T, Row, Col >::c () const inline constexpr
Returns number of columns.
Returns
Number of columns
Definition at line 763 of file numeric_matrix.h.
{ return Col; }
n()
template<typename T , size_t Row, size_t Col> constexpr size_t vt::impl::numeric_matrix_static_t< T, Row, Col >::n () const inline constexpr
Returns number of entries.
Returns
Number of entries
Definition at line 770 of file numeric_matrix.h.
{ return Row * Col; }
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::matpow(), vt::impl::numeric_matrix_static_t< T, Row, Col >::matpow_naive(), vt::impl::numeric_matrix_static_t< T, Row, Col >::operator^(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::operator^=().
order()
template<typename T , size_t Row, size_t Col> constexpr size_t vt::impl::numeric_matrix_static_t< T, Row, Col >::order () const inline constexpr
Returns order of this matrix (min(Row, Col)).
Returns
Order of this matrix
Definition at line 777 of file numeric_matrix.h.
{ return Order; }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::Order.
is_square()
template<typename T , size_t Row, size_t Col> constexpr bool vt::impl::numeric_matrix_static_t< T, Row, Col >::is_square () const inline constexpr
Returns whether the matrix is square.
Returns
Definition at line 784 of file numeric_matrix.h.
{ return Row == Col; }
swap()
template<typename T , size_t Row, size_t Col> void vt::impl::numeric_matrix_static_t< T, Row, Col >::swap (numeric_matrix_static_t< T, Row, Col > & other) inline
Swaps entries with the other matrix.
Parameters
other
Definition at line 791 of file numeric_matrix.h.
{
                for (size_t i = 0; i < Row; ++i) vector_[i].swap(other.vector_[i]);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::swap(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::RRE(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::swap().
copy()
template<typename T , size_t Row, size_t Col> constexpr numeric_matrix_static_t vt::impl::numeric_matrix_static_t< T, Row, Col >::copy () const inline constexpr
Creates a copy of this matrix.
Returns
A copy of this matrix
Definition at line 800 of file numeric_matrix.h.
{ return numeric_matrix_static_t(*this); }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t().
fix_zero()
template<typename T , size_t Row, size_t Col> void vt::impl::numeric_matrix_static_t< T, Row, Col >::fix_zero () inline private
Definition at line 803 of file numeric_matrix.h.
{
                for (size_t i = 0; i < Row; ++i)
                    for (size_t j = 0; j < Col; ++j)
                        if (vector_[i][j] == 0.0)
                            vector_[i][j] = 0.0;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::RRE().
allocate_zero()
template<typename T , size_t Row, size_t Col> void vt::impl::numeric_matrix_static_t< T, Row, Col >::allocate_zero () inline private
Definition at line 810 of file numeric_matrix.h.
{
                vector_ = vt::move(numeric_vector_static_t<numeric_vector_static_t<T, Col>, Row>());
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
allocate_fill()
template<typename T , size_t Row, size_t Col> void vt::impl::numeric_matrix_static_t< T, Row, Col >::allocate_fill (T fill) inline private
Definition at line 814 of file numeric_matrix.h.
{
                vector_ = vt::move(
                        numeric_vector_static_t<numeric_vector_static_t<T, Col>, Row>(
                                numeric_vector_static_t<T, Col>(fill))
                );
            }
References vt::fill(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
allocate_from() [1/3]
template<typename T , size_t Row, size_t Col> void vt::impl::numeric_matrix_static_t< T, Row, Col >::allocate_from (const numeric_matrix_static_t< T, Row, Col > & other) inline private
Definition at line 821 of file numeric_matrix.h.
{ vector_ = other.vector_; }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t(), vt::impl::numeric_matrix_static_t< T, Row, Col >::operator=(), vt::impl::numeric_matrix_static_t< T, Row, Col >::operator=(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::operator=().
allocate_from() [2/3]
template<typename T , size_t Row, size_t Col> void vt::impl::numeric_matrix_static_t< T, Row, Col >::allocate_from (const T(&) array[Row][Col]) inline private
Definition at line 823 of file numeric_matrix.h.
{
                for (size_t i = 0; i < Row; ++i)
                    for (size_t j = 0; j < Col; ++j)
                        vector_[i][j] = array[i][j];
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
allocate_from() [3/3]
template<typename T , size_t Row, size_t Col> void vt::impl::numeric_matrix_static_t< T, Row, Col >::allocate_from (const numeric_vector_static_t< T, Col >(&) vectors[Row]) inline private
Definition at line 829 of file numeric_matrix.h.
{
                for (size_t i = 0; i < Row; ++i)
                    for (size_t j = 0; j < Col; ++j)
                        vector_[i][j] = vectors[i][j];
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
steal()
template<typename T , size_t Row, size_t Col> void vt::impl::numeric_matrix_static_t< T, Row, Col >::steal (numeric_matrix_static_t< T, Row, Col > && other) inline private
Definition at line 835 of file numeric_matrix.h.
{ vector_ = vt::move(other.vector_); }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::operator*=(), vt::impl::numeric_matrix_static_t< T, Row, Col >::operator=(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::operator^=().
helper_insert_major()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol, size_t M, size_t N> void vt::impl::numeric_matrix_static_t< T, Row, Col >::helper_insert_major (size_t pos_row, const numeric_matrix_static_t< T, ORow, OCol >(&) blocks[M][N]) inline private
Definition at line 838 of file numeric_matrix.h.
{
                if (pos_row < M) {
                    helper_insert_minor(pos_row, 0, blocks);
                    helper_insert_major(pos_row + 1, blocks);
                }
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::helper_insert_major(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::helper_insert_minor().
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::helper_insert_major(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t().
helper_insert_minor()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol, size_t M, size_t N> void vt::impl::numeric_matrix_static_t< T, Row, Col >::helper_insert_minor (size_t pos_row, size_t pos_col, const numeric_matrix_static_t< T, ORow, OCol >(&) blocks[M][N]) inline private
Definition at line 846 of file numeric_matrix.h.
{
                helper_insert_unsafe(ORow * pos_row, OCol * pos_col, blocks[pos_row][pos_col]);
                if (pos_col < N - 1) helper_insert_minor(pos_row, pos_col + 1, blocks);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::helper_insert_minor(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::helper_insert_unsafe().
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::helper_insert_major(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::helper_insert_minor().
helper_insert_unsafe()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> void vt::impl::numeric_matrix_static_t< T, Row, Col >::helper_insert_unsafe (size_t pos_row, size_t pos_col, const numeric_matrix_static_t< T, ORow, OCol > & M) inline private
Definition at line 853 of file numeric_matrix.h.
{
                for (size_t i = 0; i < ORow; ++i)
                    for (size_t j = 0; j < OCol; ++j)
                        vector_[pos_row + i][pos_col + j] = M[i][j];
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_.
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::helper_insert_minor().
static_is_a_square_matrix()
template<typename T , size_t Row, size_t Col> static constexpr bool vt::impl::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix () inline static constexpr private
Definition at line 859 of file numeric_matrix.h.
{ return Row == Col; }
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::det(), vt::impl::numeric_matrix_static_t< T, Row, Col >::identity(), vt::impl::numeric_matrix_static_t< T, Row, Col >::inv(), vt::impl::numeric_matrix_static_t< T, Row, Col >::inv_lt(), vt::impl::numeric_matrix_static_t< T, Row, Col >::inv_ut(), vt::impl::numeric_matrix_static_t< T, Row, Col >::LU(), vt::impl::numeric_matrix_static_t< T, Row, Col >::matpow(), vt::impl::numeric_matrix_static_t< T, Row, Col >::matpow_naive(), vt::impl::numeric_matrix_static_t< T, Row, Col >::operator^(), vt::impl::numeric_matrix_static_t< T, Row, Col >::operator^=(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::tr().
is_multiple_of_2()
template<typename T , size_t Row, size_t Col> static constexpr bool vt::impl::numeric_matrix_static_t< T, Row, Col >::is_multiple_of_2 (size_t x) inline static constexpr private
Definition at line 861 of file numeric_matrix.h.
{ return x != 0 && !(x & (x - 1)); }
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::closest_2().
closest_2()
template<typename T , size_t Row, size_t Col> static size_t vt::impl::numeric_matrix_static_t< T, Row, Col >::closest_2 (size_t x) inline static private
Definition at line 863 of file numeric_matrix.h.
{
                if (is_multiple_of_2(x)) return x;
                size_t result = 1;
                while (x != 0) {
                    x >>= 1;
                    result <<= 1;
                }
                return result;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::is_multiple_of_2().
mm_naive()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t X, size_t OCol> static numeric_matrix_static_t< T, ORow, OCol > & vt::impl::numeric_matrix_static_t< T, Row, Col >::mm_naive (numeric_matrix_static_t< T, ORow, OCol > & C, const numeric_matrix_static_t< T, ORow, X > & A, const numeric_matrix_static_t< T, X, OCol > & B) inline static private
Definition at line 874 of file numeric_matrix.h.
{
                for (size_t i = 0; i < ORow; ++i) {
                    numeric_vector_static_t<T, OCol> &row_C = C[i];
                    for (size_t k = 0; k < X; ++k) {
                        const T &val_A = A[i][k];
                        for (size_t j = 0; j < OCol; ++j) {
                            row_C[j] += val_A * B[k][j];
                        }
                    }
                }
                return C;
            }
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::imatmul(), vt::impl::numeric_matrix_static_t< T, Row, Col >::matmul_naive(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::mm_strassen().
mm_naive_T()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t X, size_t OCol> static numeric_matrix_static_t< T, ORow, OCol > & vt::impl::numeric_matrix_static_t< T, Row, Col >::mm_naive_T (numeric_matrix_static_t< T, ORow, OCol > & C, const numeric_matrix_static_t< T, ORow, X > & A, const numeric_matrix_static_t< T, OCol, X > & B) inline static private
Definition at line 890 of file numeric_matrix.h.
{
                for (size_t i = 0; i < ORow; ++i) {
                    numeric_vector_static_t<T, OCol> &row_C = C[i];
                    for (size_t k = 0; k < X; ++k) {
                        const T &val_A = A[i][k];
                        for (size_t j = 0; j < OCol; ++j) {
                            row_C[j] += val_A * B[j][k];
                        }
                    }
                }
                return C;
            }
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::matmul_T().
mm_strassen()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t X, size_t OCol> static constexpr numeric_matrix_static_t< T, ORow, OCol > & vt::impl::numeric_matrix_static_t< T, Row, Col >::mm_strassen (numeric_matrix_static_t< T, ORow, OCol > & C, const numeric_matrix_static_t< T, ORow, X > & A, const numeric_matrix_static_t< T, X, OCol > & B) inline static constexpr private
Definition at line 907 of file numeric_matrix.h.
{
                // to be implemented later.
                // not suitable for embedded system.
                return mm_naive(C, A, B);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::mm_naive().
inv_lt()
template<typename T , size_t Row, size_t Col> template<size_t OSize> static numeric_matrix_static_t< T, OSize, OSize > vt::impl::numeric_matrix_static_t< T, Row, Col >::inv_lt (numeric_matrix_static_t< T, OSize, OSize > & L) inline static private
Definition at line 916 of file numeric_matrix.h.
{
                static_assert(static_is_a_square_matrix(), "Can only inverse a square matrix.");
                numeric_matrix_static_t<T, OSize, OSize> X;
                for (size_t k = 0; k < OSize; ++k) {
                    X[k][k] = 1 / L[k][k];
                    for (size_t i = k + 1; i < OSize; ++i) {
                        T acc = 0;
                        for (size_t j = k; j < i; ++j)
                            acc -= L[i][j] * X[j][k];
                        X[i][k] = acc / L[i][i];
                    }
                }
                L = vt::move(X);
                return L;
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix().
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::inv(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::inv_ut().
inv_ut()
template<typename T , size_t Row, size_t Col> template<size_t OSize> static numeric_matrix_static_t< T, OSize, OSize > vt::impl::numeric_matrix_static_t< T, Row, Col >::inv_ut (numeric_matrix_static_t< T, OSize, OSize > & U) inline static private
Definition at line 933 of file numeric_matrix.h.
{
                static_assert(static_is_a_square_matrix(), "Can only inverse a square matrix.");
                numeric_matrix_static_t<T, OSize, OSize> tmp = vt::move(U.transpose());
                return inv_lt(tmp).transpose();
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::inv_lt(), vt::impl::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::transpose().
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::inv().
zeros()
template<typename T , size_t Row, size_t Col> static constexpr numeric_matrix_static_t vt::impl::numeric_matrix_static_t< T, Row, Col >::zeros () inline static constexpr
Returns zero matrix.
Returns
Zero matrix
Definition at line 945 of file numeric_matrix.h.
{ return numeric_matrix_static_t(); }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t().
ones()
template<typename T , size_t Row, size_t Col> static constexpr numeric_matrix_static_t vt::impl::numeric_matrix_static_t< T, Row, Col >::ones () inline static constexpr
Returns 1-filled matrix.
Returns
1-filled matrix
Definition at line 952 of file numeric_matrix.h.
{ return numeric_matrix_static_t(1); }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t().
identity()
template<typename T , size_t Row, size_t Col> static constexpr numeric_matrix_static_t vt::impl::numeric_matrix_static_t< T, Row, Col >::identity () inline static constexpr
Returns an identity matrix of current dimension.
If this matrix is not square, the compile-time error is thrown.
Returns
Identity matrix
Definition at line 960 of file numeric_matrix.h.
{
                static_assert(static_is_a_square_matrix(), "Identity matrix must be a square matrix.");
                return diagonals(1);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::diagonals(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::static_is_a_square_matrix().
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::id(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::operator^().
id()
template<typename T , size_t Row, size_t Col> static constexpr numeric_matrix_static_t vt::impl::numeric_matrix_static_t< T, Row, Col >::id () inline static constexpr
Returns an identity matrix of current dimension.
If this matrix is not square, the compile-time error is thrown.
Returns
Identity matrix
Definition at line 971 of file numeric_matrix.h.
{ return identity(); }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::identity().
diagonals() [1/2]
template<typename T , size_t Row, size_t Col> static constexpr numeric_matrix_static_t vt::impl::numeric_matrix_static_t< T, Row, Col >::diagonals (const T & value) inline static constexpr
Returns a matrix where the main diagonal is filled with fill value.
Parameters
value Fill value
Returns
Filled diagonal matrix
Definition at line 979 of file numeric_matrix.h.
{
                return numeric_matrix_static_t(detail::make_diagonal(numeric_vector_static_t<T, Order>(value).arr_));
            }
References vt::detail::make_diagonal(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t().
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::identity().
diagonals() [2/2]
template<typename T , size_t Row, size_t Col> static constexpr numeric_matrix_static_t vt::impl::numeric_matrix_static_t< T, Row, Col >::diagonals (const T(&) array[Order]) inline static constexpr
Returns a matrix where the main diagonal is filled with fill values from array.
Parameters
array Fill array
Returns
Filled diagonal matrix
Definition at line 989 of file numeric_matrix.h.
{
                return numeric_matrix_static_t(detail::make_diagonal(array));
            }
References vt::detail::make_diagonal(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t().
quad()
template<typename T , size_t Row, size_t Col> template<size_t ORow, size_t OCol> static numeric_matrix_static_t constexpr vt::impl::numeric_matrix_static_t< T, Row, Col >::quad (const numeric_matrix_static_t< T, ORow, OCol > M) inline static constexpr
Returns a quad-filled matrix where M11, M12, M21, and M22 are the same.
Template Parameters
ORow
OCol
Parameters
M Fill matrix
Returns
Quad-filled matrix
Definition at line 1002 of file numeric_matrix.h.
{
                return numeric_matrix_static_t(M, M, M, M);
            }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::numeric_matrix_static_t().
Friends And Related Symbol Documentation
numeric_vector_static_t
template<typename T , size_t Row, size_t Col> template<typename U , size_t V> friend class numeric_vector_static_t friend
Definition at line 39 of file numeric_matrix.h.
Member Data Documentation
Order
template<typename T , size_t Row, size_t Col> constexpr size_t vt::impl::numeric_matrix_static_t< T, Row, Col >::Order = (Row < Col) ? Row : Col static constexpr private
Definition at line 42 of file numeric_matrix.h.
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::det_from_lu(), vt::impl::numeric_matrix_static_t< T, Row, Col >::diag(), vt::impl::numeric_matrix_static_t< T, Row, Col >::LU(), vt::impl::numeric_matrix_static_t< T, Row, Col >::order(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::tr().
vector_
template<typename T , size_t Row, size_t Col> numeric_vector_static_t<numeric_vector_static_t<T, Col>, Row> vt::impl::numeric_matrix_static_t< T, Row, Col >::vector_ = {} private
Definition at line 43 of file numeric_matrix.h.
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::allocate_fill(), vt::impl::numeric_matrix_static_t< T, Row, Col >::allocate_from(), vt::impl::numeric_matrix_static_t< T, Row, Col >::allocate_from(), vt::impl::numeric_matrix_static_t< T, Row, Col >::allocate_from(), vt::impl::numeric_matrix_static_t< T, Row, Col >::allocate_zero(), vt::impl::numeric_matrix_static_t< T, Row, Col >::at(), vt::impl::numeric_matrix_static_t< T, Row, Col >::at(), vt::impl::numeric_matrix_static_t< T, Row, Col >::begin(), vt::impl::numeric_matrix_static_t< T, Row, Col >::begin(), vt::impl::numeric_matrix_static_t< T, Row, Col >::col(), vt::impl::numeric_matrix_static_t< T, Row, Col >::diag(), vt::impl::numeric_matrix_static_t< T, Row, Col >::end(), vt::impl::numeric_matrix_static_t< T, Row, Col >::end(), vt::impl::numeric_matrix_static_t< T, Row, Col >::fix_zero(), vt::impl::numeric_matrix_static_t< T, Row, Col >::float_equals(), vt::impl::numeric_matrix_static_t< T, Row, Col >::helper_insert_unsafe(), vt::impl::numeric_matrix_static_t< T, Row, Col >::insert(), vt::impl::numeric_matrix_static_t< T, Row, Col >::insert(), vt::impl::numeric_matrix_static_t< T, Row, Col >::LU(), vt::impl::numeric_matrix_static_t< T, Row, Col >::operator*(), vt::impl::numeric_matrix_static_t< T, Row, Col >::operator*=(), vt::impl::numeric_matrix_static_t< T, Row, Col >::operator==(), vt::impl::numeric_matrix_static_t< T, Row, Col >::operator==(), vt::impl::numeric_matrix_static_t< T, Row, Col >::operator[](), vt::impl::numeric_matrix_static_t< T, Row, Col >::operator[](), vt::impl::numeric_matrix_static_t< T, Row, Col >::slice(), vt::impl::numeric_matrix_static_t< T, Row, Col >::steal(), vt::impl::numeric_matrix_static_t< T, Row, Col >::swap(), vt::impl::numeric_matrix_static_t< T, Row, Col >::tr(), and vt::impl::numeric_matrix_static_t< T, Row, Col >::transpose().
The documentation for this class was generated from the following file:
include/numeric_matrix.h