VT Linear Algebra Library: vt::impl::numeric_vector_static_t< T, Size > Class Template Reference
vt::impl::numeric_vector_static_t< T, Size > Class Template Reference
#include <numeric_vector.h>
Public Member Functions
constexpr numeric_vector_static_t ()=default
constexpr numeric_vector_static_t (const T &fill)
constexpr numeric_vector_static_t (const numeric_vector_static_t &)=default
constexpr numeric_vector_static_t (numeric_vector_static_t &&) noexcept=default
constexpr numeric_vector_static_t (const T(&array)[Size])
template<size_t S1, size_t S2>
numeric_vector_static_t (const numeric_vector_static_t< T, S1 > &v1, const numeric_vector_static_t< T, S2 > &v2)
template<size_t S1, size_t S2>
numeric_vector_static_t (const T(&a1)[S1], const T(&a2)[S2])
T & operator[] (size_t index)
constexpr const T & operator[] (size_t index) const
T & at (size_t index)
constexpr const T & at (size_t index) const
T & operator() (size_t index)
constexpr const T & operator() (size_t index) const
numeric_vector_static_t & operator= (const numeric_vector_static_t &other)
numeric_vector_static_t & operator= (numeric_vector_static_t &&other) noexcept
numeric_vector_static_t & operator= (const T(&array)[Size])
numeric_vector_static_t & operator+= (const numeric_vector_static_t &other)
numeric_vector_static_t & operator+= (const T(&array)[Size])
numeric_vector_static_t operator+ (const numeric_vector_static_t &other) const
numeric_vector_static_t operator+ (const T(&array)[Size]) const
constexpr numeric_vector_static_t add (const numeric_vector_static_t &other) const
constexpr numeric_vector_static_t add (const T(&array)[Size]) const
numeric_vector_static_t & operator-= (const numeric_vector_static_t &other)
numeric_vector_static_t & operator-= (const T(&array)[Size])
numeric_vector_static_t operator- (const numeric_vector_static_t &other) const
numeric_vector_static_t operator- (const T(&array)[Size]) const
constexpr numeric_vector_static_t subtract (const numeric_vector_static_t &other) const
constexpr numeric_vector_static_t subtract (const T(&array)[Size]) const
numeric_vector_static_t & operator*= (T rhs)
numeric_vector_static_t operator* (T rhs) const
numeric_vector_static_t & operator/= (T rhs)
numeric_vector_static_t operator/ (T rhs) const
T dot (const numeric_vector_static_t &other) const
T dot (const T(&array)[Size]) const
constexpr T inner (const numeric_vector_static_t &other) const
constexpr T inner (const T(&array)[Size]) const
template<size_t OSize>
numeric_matrix_static_t< T, Size, OSize > outer (const numeric_vector_static_t< T, OSize > &other) const
template<size_t OSize>
numeric_matrix_static_t< T, Size, OSize > outer (const T(&array)[OSize]) const
T sum () const
constexpr T norm () const
constexpr numeric_vector_static_t normalize () const
template<size_t OSize>
bool operator== (const numeric_vector_static_t< T, OSize > &other) const
template<size_t OSize>
bool operator== (const T(&array)[OSize]) const
template<size_t OSize>
constexpr bool operator!= (const numeric_vector_static_t< T, OSize > &other) const
template<size_t OSize>
constexpr bool operator!= (const T(&array)[OSize]) const
template<size_t OSize>
constexpr bool equals (const numeric_vector_static_t< T, OSize > &other) const
template<size_t OSize>
bool float_equals (const numeric_vector_static_t< T, OSize > &other, real_t threshold=1e-10) const
template<size_t OSize>
constexpr bool equals (const T(&array)[OSize]) const
template<size_t pos = 0, size_t OSize>
numeric_vector_static_t & insert (const numeric_vector_static_t< T, OSize > &v)
template<size_t pos = 0, size_t OSize>
numeric_vector_static_t & insert (const T(&array)[OSize])
template<size_t from, size_t to>
numeric_vector_static_t< T, to - from > slice ()
numeric_matrix_static_t< T, Size, 1 > as_matrix_col ()
numeric_matrix_static_t< T, 1, Size > as_matrix_row ()
iterator< T > begin ()
constexpr const_iterator< T > begin () const
iterator< T > end ()
constexpr const_iterator< T > end () const
constexpr size_t size () const
constexpr size_t dim () const
constexpr size_t dimension () const
void swap (numeric_vector_static_t &other)
constexpr numeric_vector_static_t copy () const
template<typename... Ts>
numeric_vector_static_t & assign_to (Ts &...vars)
template<typename... Ts>
numeric_vector_static_t & assign_from (const Ts &...vars)
detail::output_assignment_chain< T, Size, 1 > operator>> (T &var) const
detail::input_assignment_chain< T, Size, 1 > operator<< (const T &var)
Static Public Member Functions
static constexpr numeric_vector_static_t zeros ()
static constexpr numeric_vector_static_t ones ()
Private Member Functions
template<size_t... I>
constexpr numeric_vector_static_t (const T &fill, vt::index_sequence< I... >)
template<size_t... I>
constexpr numeric_vector_static_t (const T(&array)[Size], vt::index_sequence< I... >)
void allocate_zero ()
void allocate_fill (const T &fill)
void allocate_from (const numeric_vector_static_t &other)
void allocate_from (const T(&array)[Size])
Private Attributes
T arr_ [Size] = {}
Friends
template<typename U , size_t V, size_t W>
class numeric_matrix_static_t
Detailed Description
template<typename T, size_t Size>
class vt::impl::numeric_vector_static_t< T, Size >
Numeric vector template class where the dimension must be known at compile-time and can't be changed by any ways during runtime to prevent unexpected behavior or errors. This avoid heap usages for safety-critical and performance-critical systems.
Template Parameters
T data type
Size vector dimension
Definition at line 49 of file numeric_vector.h.
Constructor & Destructor Documentation
numeric_vector_static_t() [1/9]
template<typename T , size_t Size> constexpr vt::impl::numeric_vector_static_t< T, Size >::numeric_vector_static_t () constexpr default
Default constructor, initializes to zero
Referenced by vt::impl::numeric_vector_static_t< T, Size >::copy(), vt::impl::numeric_vector_static_t< T, Size >::normalize(), vt::impl::numeric_vector_static_t< T, Size >::ones(), and vt::impl::numeric_vector_static_t< T, Size >::zeros().
numeric_vector_static_t() [2/9]
template<typename T , size_t Size> template<size_t... I> constexpr vt::impl::numeric_vector_static_t< T, Size >::numeric_vector_static_t (const T & fill, vt::index_sequence< I... >) inline constexpr private
Definition at line 68 of file numeric_vector.h.
                    : arr_{(static_cast<void>(I), fill)...} {}
numeric_vector_static_t() [3/9]
template<typename T , size_t Size> constexpr vt::impl::numeric_vector_static_t< T, Size >::numeric_vector_static_t (const T & fill) inline explicit constexpr
Fill constructor, initializes to fill value
Parameters
fill Fill value
Definition at line 77 of file numeric_vector.h.
                    : numeric_vector_static_t(fill, vt::make_index_sequence<Size>()) {}
numeric_vector_static_t() [4/9]
template<typename T , size_t Size> constexpr vt::impl::numeric_vector_static_t< T, Size >::numeric_vector_static_t (const numeric_vector_static_t< T, Size > &) constexpr default
Copy constructor
Parameters
other Other vector
numeric_vector_static_t() [5/9]
template<typename T , size_t Size> constexpr vt::impl::numeric_vector_static_t< T, Size >::numeric_vector_static_t (numeric_vector_static_t< T, Size > &&) constexpr default noexcept
Move constructor
Parameters
other Other vector
numeric_vector_static_t() [6/9]
template<typename T , size_t Size> template<size_t... I> constexpr vt::impl::numeric_vector_static_t< T, Size >::numeric_vector_static_t (const T(&) array[Size], vt::index_sequence< I... >) inline constexpr private
Definition at line 96 of file numeric_vector.h.
                    : arr_{array[I]...} {}
numeric_vector_static_t() [7/9]
template<typename T , size_t Size> constexpr vt::impl::numeric_vector_static_t< T, Size >::numeric_vector_static_t (const T(&) array[Size]) inline explicit constexpr
Array constructor, construct from array
Parameters
array Array of entries
Definition at line 105 of file numeric_vector.h.
                    : numeric_vector_static_t(array, vt::make_index_sequence<Size>()) {}
numeric_vector_static_t() [8/9]
template<typename T , size_t Size> template<size_t S1, size_t S2> vt::impl::numeric_vector_static_t< T, Size >::numeric_vector_static_t (const numeric_vector_static_t< T, S1 > & v1, const numeric_vector_static_t< T, S2 > & v2) inline
Extended constructor
Template Parameters
S1
S2
Parameters
v1
v2
Definition at line 117 of file numeric_vector.h.
{
                insert<0>(v1);
                insert<S1>(v2);
            }
numeric_vector_static_t() [9/9]
template<typename T , size_t Size> template<size_t S1, size_t S2> vt::impl::numeric_vector_static_t< T, Size >::numeric_vector_static_t (const T(&) a1[S1], const T(&) a2[S2]) inline
Extended constructor
Template Parameters
S1
S2
Parameters
a1
a2
Definition at line 132 of file numeric_vector.h.
{
                insert<0>(a1);
                insert<S1>(a2);
            }
Member Function Documentation
operator[]() [1/2]
template<typename T , size_t Size> T & vt::impl::numeric_vector_static_t< T, Size >::operator[] (size_t index) inline
Definition at line 138 of file numeric_vector.h.
{ return *(arr_ + index); }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
Referenced by vt::impl::numeric_vector_static_t< T, Size >::at(), and vt::impl::numeric_vector_static_t< T, Size >::at().
operator[]() [2/2]
template<typename T , size_t Size> constexpr const T & vt::impl::numeric_vector_static_t< T, Size >::operator[] (size_t index) const inline constexpr
Definition at line 140 of file numeric_vector.h.
{ return *(arr_ + index); }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
at() [1/2]
template<typename T , size_t Size> T & vt::impl::numeric_vector_static_t< T, Size >::at (size_t index) inline
Definition at line 142 of file numeric_vector.h.
{ return operator[](index); };
References vt::impl::numeric_vector_static_t< T, Size >::operator[]().
Referenced by vt::impl::numeric_vector_static_t< T, Size >::operator()(), and vt::impl::numeric_vector_static_t< T, Size >::operator()().
at() [2/2]
template<typename T , size_t Size> constexpr const T & vt::impl::numeric_vector_static_t< T, Size >::at (size_t index) const inline constexpr
Definition at line 144 of file numeric_vector.h.
{ return operator[](index); };
References vt::impl::numeric_vector_static_t< T, Size >::operator[]().
operator()() [1/2]
template<typename T , size_t Size> T & vt::impl::numeric_vector_static_t< T, Size >::operator() (size_t index) inline
Definition at line 146 of file numeric_vector.h.
{ return at(index); }
References vt::impl::numeric_vector_static_t< T, Size >::at().
operator()() [2/2]
template<typename T , size_t Size> constexpr const T & vt::impl::numeric_vector_static_t< T, Size >::operator() (size_t index) const inline constexpr
Definition at line 148 of file numeric_vector.h.
{ return at(index); }
References vt::impl::numeric_vector_static_t< T, Size >::at().
operator=() [1/3]
template<typename T , size_t Size> numeric_vector_static_t & vt::impl::numeric_vector_static_t< T, Size >::operator= (const numeric_vector_static_t< T, Size > & other) inline
Definition at line 150 of file numeric_vector.h.
{
                if (this != &other) allocate_from(other);
                return *this;
            }
References vt::impl::numeric_vector_static_t< T, Size >::allocate_from().
operator=() [2/3]
template<typename T , size_t Size> numeric_vector_static_t & vt::impl::numeric_vector_static_t< T, Size >::operator= (numeric_vector_static_t< T, Size > && other) inline noexcept
Definition at line 155 of file numeric_vector.h.
{
                if (this != &other) for (size_t i = 0; i < Size; ++i) arr_[i] = vt::move(other.arr_[i]);
                return *this;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
operator=() [3/3]
template<typename T , size_t Size> numeric_vector_static_t & vt::impl::numeric_vector_static_t< T, Size >::operator= (const T(&) array[Size]) inline
Definition at line 160 of file numeric_vector.h.
{
                allocate_from(array);
                return *this;
            }
References vt::impl::numeric_vector_static_t< T, Size >::allocate_from().
operator+=() [1/2]
template<typename T , size_t Size> numeric_vector_static_t & vt::impl::numeric_vector_static_t< T, Size >::operator+= (const numeric_vector_static_t< T, Size > & other) inline
Definition at line 165 of file numeric_vector.h.
{
                for (size_t i = 0; i < Size; ++i) arr_[i] += other.arr_[i];
                return *this;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
operator+=() [2/2]
template<typename T , size_t Size> numeric_vector_static_t & vt::impl::numeric_vector_static_t< T, Size >::operator+= (const T(&) array[Size]) inline
Definition at line 170 of file numeric_vector.h.
{
                for (size_t i = 0; i < Size; ++i) arr_[i] += array[i];
                return *this;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
operator+() [1/2]
template<typename T , size_t Size> numeric_vector_static_t vt::impl::numeric_vector_static_t< T, Size >::operator+ (const numeric_vector_static_t< T, Size > & other) const inline
Definition at line 175 of file numeric_vector.h.
{
                numeric_vector_static_t tmp(*this);
                tmp.operator+=(other);
                return tmp;
            }
Referenced by vt::impl::numeric_vector_static_t< T, Size >::add(), and vt::impl::numeric_vector_static_t< T, Size >::add().
operator+() [2/2]
template<typename T , size_t Size> numeric_vector_static_t vt::impl::numeric_vector_static_t< T, Size >::operator+ (const T(&) array[Size]) const inline
Definition at line 181 of file numeric_vector.h.
{
                numeric_vector_static_t tmp(*this);
                tmp.operator+=(array);
                return tmp;
            }
add() [1/2]
template<typename T , size_t Size> constexpr numeric_vector_static_t vt::impl::numeric_vector_static_t< T, Size >::add (const numeric_vector_static_t< T, Size > & other) const inline constexpr
Definition at line 187 of file numeric_vector.h.
{
                return operator+(other);
            }
References vt::impl::numeric_vector_static_t< T, Size >::operator+().
add() [2/2]
template<typename T , size_t Size> constexpr numeric_vector_static_t vt::impl::numeric_vector_static_t< T, Size >::add (const T(&) array[Size]) const inline constexpr
Definition at line 191 of file numeric_vector.h.
{ return operator+(array); }
References vt::impl::numeric_vector_static_t< T, Size >::operator+().
operator-=() [1/2]
template<typename T , size_t Size> numeric_vector_static_t & vt::impl::numeric_vector_static_t< T, Size >::operator-= (const numeric_vector_static_t< T, Size > & other) inline
Definition at line 193 of file numeric_vector.h.
{
                for (size_t i = 0; i < Size; ++i) arr_[i] -= other.arr_[i];
                return *this;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
operator-=() [2/2]
template<typename T , size_t Size> numeric_vector_static_t & vt::impl::numeric_vector_static_t< T, Size >::operator-= (const T(&) array[Size]) inline
Definition at line 198 of file numeric_vector.h.
{
                for (size_t i = 0; i < Size; ++i) arr_[i] -= array[i];
                return *this;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
operator-() [1/2]
template<typename T , size_t Size> numeric_vector_static_t vt::impl::numeric_vector_static_t< T, Size >::operator- (const numeric_vector_static_t< T, Size > & other) const inline
Definition at line 203 of file numeric_vector.h.
{
                numeric_vector_static_t tmp(*this);
                tmp.operator-=(other);
                return tmp;
            }
Referenced by vt::impl::numeric_vector_static_t< T, Size >::subtract(), and vt::impl::numeric_vector_static_t< T, Size >::subtract().
operator-() [2/2]
template<typename T , size_t Size> numeric_vector_static_t vt::impl::numeric_vector_static_t< T, Size >::operator- (const T(&) array[Size]) const inline
Definition at line 209 of file numeric_vector.h.
{
                numeric_vector_static_t tmp(*this);
                tmp.operator-=(array);
                return tmp;
            }
subtract() [1/2]
template<typename T , size_t Size> constexpr numeric_vector_static_t vt::impl::numeric_vector_static_t< T, Size >::subtract (const numeric_vector_static_t< T, Size > & other) const inline constexpr
Definition at line 215 of file numeric_vector.h.
{
                return operator-(other);
            }
References vt::impl::numeric_vector_static_t< T, Size >::operator-().
subtract() [2/2]
template<typename T , size_t Size> constexpr numeric_vector_static_t vt::impl::numeric_vector_static_t< T, Size >::subtract (const T(&) array[Size]) const inline constexpr
Definition at line 219 of file numeric_vector.h.
{ return operator-(array); }
References vt::impl::numeric_vector_static_t< T, Size >::operator-().
operator*=()
template<typename T , size_t Size> numeric_vector_static_t & vt::impl::numeric_vector_static_t< T, Size >::operator*= (T rhs) inline
Definition at line 221 of file numeric_vector.h.
{
                for (size_t i = 0; i < Size; ++i) arr_[i] *= rhs;
                return *this;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
operator*()
template<typename T , size_t Size> numeric_vector_static_t vt::impl::numeric_vector_static_t< T, Size >::operator* (T rhs) const inline
Definition at line 226 of file numeric_vector.h.
{
                numeric_vector_static_t tmp(*this);
                tmp.operator*=(rhs);
                return tmp;
            }
operator/=()
template<typename T , size_t Size> numeric_vector_static_t & vt::impl::numeric_vector_static_t< T, Size >::operator/= (T rhs) inline
Definition at line 232 of file numeric_vector.h.
{
                for (size_t i = 0; i < Size; ++i) arr_[i] /= rhs;
                return *this;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
operator/()
template<typename T , size_t Size> numeric_vector_static_t vt::impl::numeric_vector_static_t< T, Size >::operator/ (T rhs) const inline
Definition at line 237 of file numeric_vector.h.
{
                numeric_vector_static_t tmp(*this);
                tmp.operator/=(rhs);
                return tmp;
            }
dot() [1/2]
template<typename T , size_t Size> T vt::impl::numeric_vector_static_t< T, Size >::dot (const numeric_vector_static_t< T, Size > & other) const inline
Calculates inner product of this vector (LHS transposed) and the other vector of the same dimension (RHS).
Parameters
other Other vector
Returns
Inner product
Definition at line 249 of file numeric_vector.h.
{
                T acc = 0;
                for (size_t i = 0; i < Size; ++i) acc += arr_[i] * other.arr_[i];
                return acc;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
Referenced by vt::impl::numeric_vector_static_t< T, Size >::inner(), vt::impl::numeric_vector_static_t< T, Size >::inner(), and vt::impl::numeric_vector_static_t< T, Size >::norm().
dot() [2/2]
template<typename T , size_t Size> T vt::impl::numeric_vector_static_t< T, Size >::dot (const T(&) array[Size]) const inline
Calculates inner product of this vector (LHS transposed) and the other vector of the same dimension (RHS).
Parameters
array Other vector as array
Returns
Inner product
Definition at line 261 of file numeric_vector.h.
{
                T acc = 0;
                for (size_t i = 0; i < Size; ++i) acc += arr_[i] * array[i];
                return acc;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
inner() [1/2]
template<typename T , size_t Size> constexpr T vt::impl::numeric_vector_static_t< T, Size >::inner (const numeric_vector_static_t< T, Size > & other) const inline constexpr
Calculates inner product of this vector (LHS transposed) and the other vector of the same dimension (RHS).
Parameters
other Other vector
Returns
Inner product
Definition at line 273 of file numeric_vector.h.
{ return dot(other); }
References vt::impl::numeric_vector_static_t< T, Size >::dot().
inner() [2/2]
template<typename T , size_t Size> constexpr T vt::impl::numeric_vector_static_t< T, Size >::inner (const T(&) array[Size]) const inline constexpr
Calculates inner product of this vector (LHS transposed) and the other vector of the same dimension (RHS).
Parameters
array Other vector as array
Returns
Inner product
Definition at line 281 of file numeric_vector.h.
{ return dot(array); }
References vt::impl::numeric_vector_static_t< T, Size >::dot().
outer() [1/2]
template<typename T , size_t Size> template<size_t OSize> numeric_matrix_static_t< T, Size, OSize > vt::impl::numeric_vector_static_t< T, Size >::outer (const numeric_vector_static_t< T, OSize > & other) const inline
Calculates outer product of this vector (LHS) and the other vector (RHS transposed).
Template Parameters
OSize Other vector's dimension
Parameters
other Other vector
Returns
Outer product
Definition at line 291 of file numeric_vector.h.
{
                numeric_matrix_static_t<T, Size, OSize> result;
                for (size_t i = 0; i < Size; ++i)
                    for (size_t j = 0; j < OSize; ++j)
                        result[i][j] = arr_[i] * other.arr_[j];
                return result;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
outer() [2/2]
template<typename T , size_t Size> template<size_t OSize> numeric_matrix_static_t< T, Size, OSize > vt::impl::numeric_vector_static_t< T, Size >::outer (const T(&) array[OSize]) const inline
Calculates outer product of this vector (LHS) and the other vector as array (RHS transposed).
Template Parameters
OSize Other vector's dimension
Parameters
array Other vector as array
Returns
Outer product
Definition at line 307 of file numeric_vector.h.
{
                numeric_matrix_static_t<T, Size, OSize> result;
                for (size_t i = 0; i < Size; ++i)
                    for (size_t j = 0; j < OSize; ++j)
                        result[i][j] = arr_[i] * array[j];
                return result;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
sum()
template<typename T , size_t Size> T vt::impl::numeric_vector_static_t< T, Size >::sum () const inline
Finds a sum of all entries.
Returns
A sum of all entries
Definition at line 320 of file numeric_vector.h.
{
                T acc = 0;
                for (size_t i = 0; i < Size; ++i) acc += arr_[i];
                return acc;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
norm()
template<typename T , size_t Size> constexpr T vt::impl::numeric_vector_static_t< T, Size >::norm () const inline constexpr
Finds a norm of this vector.
Returns
A norm of this vector
Definition at line 331 of file numeric_vector.h.
{ return pow(dot(*this), 0.5); }
References vt::impl::numeric_vector_static_t< T, Size >::dot().
Referenced by vt::impl::numeric_vector_static_t< T, Size >::normalize().
normalize()
template<typename T , size_t Size> constexpr numeric_vector_static_t vt::impl::numeric_vector_static_t< T, Size >::normalize () const inline constexpr
Returns a normalized vector of this vector.
Returns
A normalized vector of this vector
Definition at line 338 of file numeric_vector.h.
{ return numeric_vector_static_t(*this) / norm(); }
References vt::impl::numeric_vector_static_t< T, Size >::norm(), and vt::impl::numeric_vector_static_t< T, Size >::numeric_vector_static_t().
operator==() [1/2]
template<typename T , size_t Size> template<size_t OSize> bool vt::impl::numeric_vector_static_t< T, Size >::operator== (const numeric_vector_static_t< T, OSize > & other) const inline
Checks equality of this vector and the other vector.
Template Parameters
OSize Other vector's dimension
Parameters
other Other vector to compare
Returns
Definition at line 348 of file numeric_vector.h.
{
                if (this == &other) return true;
                if (Size != OSize) return false;
                for (size_t i = 0; i < Size; ++i) if (arr_[i] != other.arr_[i]) return false;
                return true;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
Referenced by vt::impl::numeric_vector_static_t< T, Size >::equals(), vt::impl::numeric_vector_static_t< T, Size >::equals(), vt::impl::numeric_vector_static_t< T, Size >::operator!=(), and vt::impl::numeric_vector_static_t< T, Size >::operator!=().
operator==() [2/2]
template<typename T , size_t Size> template<size_t OSize> bool vt::impl::numeric_vector_static_t< T, Size >::operator== (const T(&) array[OSize]) const inline
Checks equality of this vector and the other array.
Template Parameters
OSize Other array's dimension
Parameters
array Array to compare
Returns
Definition at line 363 of file numeric_vector.h.
{
                if (Size != OSize) return false;
                for (size_t i = 0; i < Size; ++i) if (arr_[i] != array[i]) return false;
                return true;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
operator!=() [1/2]
template<typename T , size_t Size> template<size_t OSize> constexpr bool vt::impl::numeric_vector_static_t< T, Size >::operator!= (const numeric_vector_static_t< T, OSize > & other) const inline constexpr
Checks inequality of this vector and the other vector.
Template Parameters
OSize Other vector's dimension
Parameters
other Other vector to compare
Returns
Definition at line 377 of file numeric_vector.h.
{
                return !operator==(other);
            }
References vt::impl::numeric_vector_static_t< T, Size >::operator==().
operator!=() [2/2]
template<typename T , size_t Size> template<size_t OSize> constexpr bool vt::impl::numeric_vector_static_t< T, Size >::operator!= (const T(&) array[OSize]) const inline constexpr
Checks inequality of this vector and the other array.
Template Parameters
OSize Other array's dimension
Parameters
array Array to compare
Returns
Definition at line 389 of file numeric_vector.h.
{ return !operator==(array); }
References vt::impl::numeric_vector_static_t< T, Size >::operator==().
equals() [1/2]
template<typename T , size_t Size> template<size_t OSize> constexpr bool vt::impl::numeric_vector_static_t< T, Size >::equals (const numeric_vector_static_t< T, OSize > & other) const inline constexpr
Checks equality of this vector and the other vector.
Template Parameters
OSize Other vector's dimension
Parameters
other Other vector to compare
Returns
Definition at line 399 of file numeric_vector.h.
{ return operator==(other); }
References vt::impl::numeric_vector_static_t< T, Size >::operator==().
float_equals()
template<typename T , size_t Size> template<size_t OSize> bool vt::impl::numeric_vector_static_t< T, Size >::float_equals (const numeric_vector_static_t< T, OSize > & other, real_t threshold = 1e-10) const inline
Checks equality of this vector and the other vector with float/double threshold using equation abs(x_ - y) < threshold for equality.
Template Parameters
OSize Other vector's dimension
Parameters
other Other vector to compare
threshold Equality threshold
Returns
Definition at line 411 of file numeric_vector.h.
{
                if (this == &other) return true;
                if (Size != OSize) return false;
                for (size_t i = 0; i < Size; ++i) if (abs(arr_[i] - other.arr_[i]) > threshold) return false;
                return true;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
equals() [2/2]
template<typename T , size_t Size> template<size_t OSize> constexpr bool vt::impl::numeric_vector_static_t< T, Size >::equals (const T(&) array[OSize]) const inline constexpr
Checks equality of this vector and the other array.
Template Parameters
OSize Other array's dimension
Parameters
array Array to compare
Returns
Definition at line 426 of file numeric_vector.h.
{ return operator==(array); }
References vt::impl::numeric_vector_static_t< T, Size >::operator==().
insert() [1/2]
template<typename T , size_t Size> template<size_t pos = 0, size_t OSize> numeric_vector_static_t & vt::impl::numeric_vector_static_t< T, Size >::insert (const numeric_vector_static_t< T, OSize > & v) inline
Insert the vector into the vector.
Template Parameters
pos Position to insert
OSize
Parameters
v Vector to insert
Returns
Reference to this vector
Definition at line 437 of file numeric_vector.h.
{
                static_assert(pos < Size, "Insertion failed! Position must be within range.");
                static_assert(pos + OSize <= Size, "Insertion failed! Vector out of range.");
                for (size_t i = 0; i < OSize; ++i) arr_[pos + i] = v[i];
                return *this;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
insert() [2/2]
template<typename T , size_t Size> template<size_t pos = 0, size_t OSize> numeric_vector_static_t & vt::impl::numeric_vector_static_t< T, Size >::insert (const T(&) array[OSize]) inline
Insert the vector into the vector.
Template Parameters
pos Position to insert
OSize
Parameters
array Vector to insert
Returns
Reference to this vector
Definition at line 453 of file numeric_vector.h.
{
                static_assert(pos < Size, "Insertion failed! Position must be within range.");
                static_assert(pos + OSize <= Size, "Insertion failed! Vector out of range.");
                for (size_t i = 0; i < OSize; ++i) arr_[pos + i] = array[i];
                return *this;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
slice()
template<typename T , size_t Size> template<size_t from, size_t to> numeric_vector_static_t< T, to - from > vt::impl::numeric_vector_static_t< T, Size >::slice () inline
Gets a slice of this vector.
Template Parameters
from From index
to To index
Returns
Sliced vector
Definition at line 468 of file numeric_vector.h.
{
                static_assert(from < to, "from must be less than to.");
                static_assert(to <= Size, "Slice range is out of range.");
                numeric_vector_static_t<T, to - from> result;
                for (size_t i = 0; i < to - from; ++i) result[i] = arr_[from + i];
                return result;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
as_matrix_col()
template<typename T , size_t Size> numeric_matrix_static_t< T, Size, 1 > vt::impl::numeric_vector_static_t< T, Size >::as_matrix_col () inline
Converts this vector to a matrix representation of column vector
Returns
Column vector as matrix
Definition at line 481 of file numeric_vector.h.
{
                numeric_matrix_static_t<T, Size, 1> result;
                for (size_t i = 0; i < Size; ++i) result[i][0] = arr_[i];
                return result;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
as_matrix_row()
template<typename T , size_t Size> numeric_matrix_static_t< T, 1, Size > vt::impl::numeric_vector_static_t< T, Size >::as_matrix_row () inline
Converts this vector to a matrix representation of row vector
Returns
Row vector as matrix
Definition at line 492 of file numeric_vector.h.
{
                numeric_matrix_static_t<T, 1, Size> result;
                for (size_t i = 0; i < Size; ++i) result[0][i] = arr_[i];
                return result;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
begin() [1/2]
template<typename T , size_t Size> iterator< T > vt::impl::numeric_vector_static_t< T, Size >::begin () inline
Returns an iterator to vector's first dimension entry.
Returns
An iterator to vector's first dimension entry
Definition at line 503 of file numeric_vector.h.
{ return iterator<T>(arr_); }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
begin() [2/2]
template<typename T , size_t Size> constexpr const_iterator< T > vt::impl::numeric_vector_static_t< T, Size >::begin () const inline constexpr
Returns an iterator to vector's first dimension entry.
Returns
An iterator to vector's first dimension entry
Definition at line 510 of file numeric_vector.h.
{ return const_iterator<T>(arr_); }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
end() [1/2]
template<typename T , size_t Size> iterator< T > vt::impl::numeric_vector_static_t< T, Size >::end () inline
Returns an iterator to vector's last dimension entry.
Returns
An iterator to vector's last dimension entry
Definition at line 517 of file numeric_vector.h.
{ return iterator<T>(arr_ + Size); }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
end() [2/2]
template<typename T , size_t Size> constexpr const_iterator< T > vt::impl::numeric_vector_static_t< T, Size >::end () const inline constexpr
Returns an iterator to vector's last dimension entry.
Returns
An iterator to vector's last dimension entry
Definition at line 524 of file numeric_vector.h.
{ return const_iterator<T>(arr_ + Size); }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
size()
template<typename T , size_t Size> constexpr size_t vt::impl::numeric_vector_static_t< T, Size >::size () const inline constexpr
Returns vector's dimension (size).
Returns
Vector's dimension (size)
Definition at line 531 of file numeric_vector.h.
{ return Size; }
dim()
template<typename T , size_t Size> constexpr size_t vt::impl::numeric_vector_static_t< T, Size >::dim () const inline constexpr
Returns vector's dimension (size).
Returns
Vector's dimension (size)
Definition at line 538 of file numeric_vector.h.
{ return Size; }
dimension()
template<typename T , size_t Size> constexpr size_t vt::impl::numeric_vector_static_t< T, Size >::dimension () const inline constexpr
Returns vector's dimension (size).
Returns
Vector's dimension (size)
Definition at line 545 of file numeric_vector.h.
{ return Size; }
swap()
template<typename T , size_t Size> void vt::impl::numeric_vector_static_t< T, Size >::swap (numeric_vector_static_t< T, Size > & other) inline
Swaps entries with the other vector.
Parameters
other Other vector
Definition at line 552 of file numeric_vector.h.
{
                for (size_t i = 0; i < Size; ++i) vt::swap(arr_[i], other.arr_[i]);
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_, and vt::swap().
copy()
template<typename T , size_t Size> constexpr numeric_vector_static_t vt::impl::numeric_vector_static_t< T, Size >::copy () const inline constexpr
Creates a copy of this vector.
Returns
A copy of this vector
Definition at line 561 of file numeric_vector.h.
{ return numeric_vector_static_t(*this); }
References vt::impl::numeric_vector_static_t< T, Size >::numeric_vector_static_t().
assign_to()
template<typename T , size_t Size> template<typename... Ts> numeric_vector_static_t & vt::impl::numeric_vector_static_t< T, Size >::assign_to (Ts &... vars) inline
Assign to variables from this vector's values.
Template Parameters
Ts
Parameters
vars
Definition at line 570 of file numeric_vector.h.
{
                static_assert(sizeof...(Ts) <= Size,
                              "Number of variables must not be greater than vector\'s dimension.");
                detail::helper_assign_to<T, Size, sizeof...(Ts), 0>(arr_, vars...);
                return *this;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_, and vt::detail::helper_assign_to().
assign_from()
template<typename T , size_t Size> template<typename... Ts> numeric_vector_static_t & vt::impl::numeric_vector_static_t< T, Size >::assign_from (const Ts &... vars) inline
Definition at line 578 of file numeric_vector.h.
{
                static_assert(sizeof...(Ts) <= Size,
                              "Number of variables must not be greater than vector\'s dimension.");
                detail::helper_assign_from<T, Size, sizeof...(Ts), 0>(arr_, vars...);
                return *this;
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_, and vt::detail::helper_assign_from().
operator>>()
template<typename T , size_t Size> detail::output_assignment_chain< T, Size, 1 > vt::impl::numeric_vector_static_t< T, Size >::operator>> (T & var) const inline
Definition at line 585 of file numeric_vector.h.
{
                var = arr_[0];
                return detail::output_assignment_chain<T, Size, 1>(arr_);
            }
operator<<()
template<typename T , size_t Size> detail::input_assignment_chain< T, Size, 1 > vt::impl::numeric_vector_static_t< T, Size >::operator<< (const T & var) inline
Definition at line 585 of file numeric_vector.h.
{
                arr_[0] = var;
                return detail::input_assignment_chain<T, Size, 1>(arr_);
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_.
allocate_zero()
template<typename T , size_t Size> void vt::impl::numeric_vector_static_t< T, Size >::allocate_zero () inline private
Definition at line 596 of file numeric_vector.h.
{ allocate_fill(T()); }
References vt::impl::numeric_vector_static_t< T, Size >::allocate_fill().
allocate_fill()
template<typename T , size_t Size> void vt::impl::numeric_vector_static_t< T, Size >::allocate_fill (const T & fill) inline private
Definition at line 598 of file numeric_vector.h.
{ vt::fill(arr_, arr_ + Size, fill); }
References vt::impl::numeric_vector_static_t< T, Size >::arr_, and vt::fill().
Referenced by vt::impl::numeric_vector_static_t< T, Size >::allocate_zero().
allocate_from() [1/2]
template<typename T , size_t Size> void vt::impl::numeric_vector_static_t< T, Size >::allocate_from (const numeric_vector_static_t< T, Size > & other) inline private
Definition at line 600 of file numeric_vector.h.
{
                static_cast<void>(vt::copy(other.arr_, other.arr_ + Size, arr_));
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_, and vt::copy().
Referenced by vt::impl::numeric_vector_static_t< T, Size >::operator=(), and vt::impl::numeric_vector_static_t< T, Size >::operator=().
allocate_from() [2/2]
template<typename T , size_t Size> void vt::impl::numeric_vector_static_t< T, Size >::allocate_from (const T(&) array[Size]) inline private
Definition at line 604 of file numeric_vector.h.
{
                static_cast<void>(vt::copy(array, array + Size, arr_));
            }
References vt::impl::numeric_vector_static_t< T, Size >::arr_, and vt::copy().
zeros()
template<typename T , size_t Size> static constexpr numeric_vector_static_t vt::impl::numeric_vector_static_t< T, Size >::zeros () inline static constexpr
Creates a zero matrix.
Returns
Zero matrix
Definition at line 614 of file numeric_vector.h.
{ return numeric_vector_static_t(); }
References vt::impl::numeric_vector_static_t< T, Size >::numeric_vector_static_t().
ones()
template<typename T , size_t Size> static constexpr numeric_vector_static_t vt::impl::numeric_vector_static_t< T, Size >::ones () inline static constexpr
Creates a 1-filled matrix.
Returns
1-filled matrix
Definition at line 621 of file numeric_vector.h.
{ return numeric_vector_static_t(1); }
References vt::impl::numeric_vector_static_t< T, Size >::numeric_vector_static_t().
Friends And Related Symbol Documentation
numeric_matrix_static_t
template<typename T , size_t Size> template<typename U , size_t V, size_t W> friend class numeric_matrix_static_t friend
Definition at line 55 of file numeric_vector.h.
Member Data Documentation
arr_
template<typename T , size_t Size> T vt::impl::numeric_vector_static_t< T, Size >::arr_[Size] = {} private
Definition at line 58 of file numeric_vector.h.
Referenced by vt::impl::numeric_vector_static_t< T, Size >::allocate_fill(), vt::impl::numeric_vector_static_t< T, Size >::allocate_from(), vt::impl::numeric_vector_static_t< T, Size >::allocate_from(), vt::impl::numeric_vector_static_t< T, Size >::as_matrix_col(), vt::impl::numeric_vector_static_t< T, Size >::as_matrix_row(), vt::impl::numeric_vector_static_t< T, Size >::assign_from(), vt::impl::numeric_vector_static_t< T, Size >::assign_to(), vt::impl::numeric_vector_static_t< T, Size >::begin(), vt::impl::numeric_vector_static_t< T, Size >::begin(), vt::impl::numeric_vector_static_t< T, Size >::dot(), vt::impl::numeric_vector_static_t< T, Size >::dot(), vt::impl::numeric_vector_static_t< T, Size >::end(), vt::impl::numeric_vector_static_t< T, Size >::end(), vt::impl::numeric_vector_static_t< T, Size >::float_equals(), vt::impl::numeric_vector_static_t< T, Size >::insert(), vt::impl::numeric_vector_static_t< T, Size >::insert(), vt::impl::numeric_vector_static_t< T, Size >::operator*=(), vt::impl::numeric_vector_static_t< T, Size >::operator+=(), vt::impl::numeric_vector_static_t< T, Size >::operator+=(), vt::impl::numeric_vector_static_t< T, Size >::operator-=(), vt::impl::numeric_vector_static_t< T, Size >::operator-=(), vt::impl::numeric_vector_static_t< T, Size >::operator/=(), vt::impl::numeric_vector_static_t< T, Size >::operator<<(), vt::impl::numeric_vector_static_t< T, Size >::operator=(), vt::impl::numeric_vector_static_t< T, Size >::operator==(), vt::impl::numeric_vector_static_t< T, Size >::operator==(), vt::impl::numeric_vector_static_t< T, Size >::operator[](), vt::impl::numeric_vector_static_t< T, Size >::operator[](), vt::impl::numeric_vector_static_t< T, Size >::outer(), vt::impl::numeric_vector_static_t< T, Size >::outer(), vt::impl::numeric_vector_static_t< T, Size >::slice(), vt::impl::numeric_vector_static_t< T, Size >::sum(), and vt::impl::numeric_vector_static_t< T, Size >::swap().
The documentation for this class was generated from the following file:
include/numeric_vector.h