VT Linear Algebra Library: vt::numeric_matrix_dynamic_lu_t< T > Class Template Reference
vt::numeric_matrix_dynamic_lu_t< T > Class Template Reference
#include <dynamic_numeric_matrix.h>
Public Member Functions
numeric_matrix_dynamic_lu_t (const numeric_matrix_dynamic_lu_t &other)
numeric_matrix_dynamic_lu_t (numeric_matrix_dynamic_lu_t &&other) noexcept
numeric_matrix_dynamic_lu_t (const PM &lu)
numeric_matrix_dynamic_lu_t (const numeric_matrix_dynamic_t< T > &l, const numeric_matrix_dynamic_t< T > &u)
numeric_matrix_dynamic_t< T > & l ()
constexpr const numeric_matrix_dynamic_t< T > & l () const
numeric_matrix_dynamic_t< T > & u ()
constexpr const numeric_matrix_dynamic_t< T > & u () const
Private Types
using PM = vt::pair< numeric_matrix_dynamic_t< T >, numeric_matrix_dynamic_t< T > >
Private Attributes
numeric_matrix_dynamic_t< T > l_
numeric_matrix_dynamic_t< T > u_
Detailed Description
template<typename T>
class vt::numeric_matrix_dynamic_lu_t< T >
Definition at line 651 of file dynamic_numeric_matrix.h.
Member Typedef Documentation
PM
template<typename T > using vt::numeric_matrix_dynamic_lu_t< T >::PM = vt::pair<numeric_matrix_dynamic_t<T>, numeric_matrix_dynamic_t<T> > private
Definition at line 653 of file dynamic_numeric_matrix.h.
Constructor & Destructor Documentation
numeric_matrix_dynamic_lu_t() [1/4]
template<typename T > vt::numeric_matrix_dynamic_lu_t< T >::numeric_matrix_dynamic_lu_t (const numeric_matrix_dynamic_lu_t< T > & other) inline
Definition at line 658 of file dynamic_numeric_matrix.h.
: l_(other.l_), u_(other.u_) {}
numeric_matrix_dynamic_lu_t() [2/4]
template<typename T > vt::numeric_matrix_dynamic_lu_t< T >::numeric_matrix_dynamic_lu_t (numeric_matrix_dynamic_lu_t< T > && other) inline noexcept
Definition at line 660 of file dynamic_numeric_matrix.h.
: l_(vt::move(other.l_)), u_(vt::move(other.u_)) {}
numeric_matrix_dynamic_lu_t() [3/4]
template<typename T > vt::numeric_matrix_dynamic_lu_t< T >::numeric_matrix_dynamic_lu_t (const PM & lu) inline explicit
Definition at line 662 of file dynamic_numeric_matrix.h.
: l_(lu.first), u_(lu.second) {}
numeric_matrix_dynamic_lu_t() [4/4]
template<typename T > vt::numeric_matrix_dynamic_lu_t< T >::numeric_matrix_dynamic_lu_t (const numeric_matrix_dynamic_t< T > & l, const numeric_matrix_dynamic_t< T > & u) inline
Definition at line 664 of file dynamic_numeric_matrix.h.
: l_(l), u_(u) {}
Member Function Documentation
l() [1/2]
template<typename T > numeric_matrix_dynamic_t< T > & vt::numeric_matrix_dynamic_lu_t< T >::l () inline
Definition at line 666 of file dynamic_numeric_matrix.h.
{ return l_; }
References vt::numeric_matrix_dynamic_lu_t< T >::l_.
Referenced by vt::numeric_matrix_dynamic_t< T >::det(), and vt::numeric_matrix_dynamic_t< T >::inv().
l() [2/2]
template<typename T > constexpr const numeric_matrix_dynamic_t< T > & vt::numeric_matrix_dynamic_lu_t< T >::l () const inline constexpr
Definition at line 668 of file dynamic_numeric_matrix.h.
{ return l_; }
References vt::numeric_matrix_dynamic_lu_t< T >::l_.
u() [1/2]
template<typename T > numeric_matrix_dynamic_t< T > & vt::numeric_matrix_dynamic_lu_t< T >::u () inline
Definition at line 670 of file dynamic_numeric_matrix.h.
{ return u_; }
References vt::numeric_matrix_dynamic_lu_t< T >::u_.
Referenced by vt::numeric_matrix_dynamic_t< T >::det(), and vt::numeric_matrix_dynamic_t< T >::inv().
u() [2/2]
template<typename T > constexpr const numeric_matrix_dynamic_t< T > & vt::numeric_matrix_dynamic_lu_t< T >::u () const inline constexpr
Definition at line 672 of file dynamic_numeric_matrix.h.
{ return u_; }
References vt::numeric_matrix_dynamic_lu_t< T >::u_.
Member Data Documentation
l_
template<typename T > numeric_matrix_dynamic_t<T> vt::numeric_matrix_dynamic_lu_t< T >::l_ private
Definition at line 654 of file dynamic_numeric_matrix.h.
Referenced by vt::numeric_matrix_dynamic_lu_t< T >::l(), and vt::numeric_matrix_dynamic_lu_t< T >::l().
u_
template<typename T > numeric_matrix_dynamic_t<T> vt::numeric_matrix_dynamic_lu_t< T >::u_ private
Definition at line 655 of file dynamic_numeric_matrix.h.
Referenced by vt::numeric_matrix_dynamic_lu_t< T >::u(), and vt::numeric_matrix_dynamic_lu_t< T >::u().
The documentation for this class was generated from the following file:
include/dynamic_numeric_matrix.h