VT Linear Algebra Library: vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension > Class Template Reference
vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension > Class Template Reference
#include <kalman.h>
Public Member Functions
constexpr simple_kalman_filter_t (const numeric_matrix< N_, N_ > &F_matrix, const numeric_matrix< N_, L_ > &B_matrix, const numeric_matrix< M_, N_ > &H_matrix, const numeric_matrix< N_, N_ > &Q_matrix, const numeric_matrix< M_, M_ > &R_matrix, const numeric_vector< N_ > &x_0)
constexpr simple_kalman_filter_t (const simple_kalman_filter_t &)=delete
constexpr simple_kalman_filter_t (simple_kalman_filter_t &&) noexcept=delete
void predict (const numeric_vector< L_ > &u={})
void update (const numeric_vector< M_ > &z)
template<typename ... Ts>
void update (Ts ...vs)
Public Attributes
const numeric_vector< N_ > & state_vector = x_
Protected Attributes
const numeric_matrix< N_, N_ > & F_
const numeric_matrix< N_, L_ > & B_
const numeric_matrix< M_, N_ > & H_
const numeric_matrix< N_, N_ > & Q_
const numeric_matrix< M_, M_ > & R_
numeric_vector< N_ > x_
numeric_matrix< N_, N_ > P_
Static Private Attributes
static constexpr size_t N_ = StateVectorDimension
static constexpr size_t M_ = MeasurementVectorDimension
static constexpr size_t L_ = ControlVectorDimension
Detailed Description
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension>
class vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >
Definition at line 21 of file kalman.h.
Constructor & Destructor Documentation
simple_kalman_filter_t() [1/3]
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension> constexpr vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::simple_kalman_filter_t (const numeric_matrix< N_, N_ > & F_matrix, const numeric_matrix< N_, L_ > & B_matrix, const numeric_matrix< M_, N_ > & H_matrix, const numeric_matrix< N_, N_ > & Q_matrix, const numeric_matrix< M_, M_ > & R_matrix, const numeric_vector< N_ > & x_0) inline constexpr
Simple Kalman filter array-copying constructor
Parameters
F_matrix state-transition model
B_matrix control-input model
H_matrix measurement model
Q_matrix covariance of the process noise
R_matrix covariance of the measurement noise
x_0 initial state vector
Definition at line 48 of file kalman.h.
                : F_{F_matrix}, B_{B_matrix}, H_{H_matrix},
                  Q_{Q_matrix}, R_{R_matrix}, x_{x_0}, P_{Q_matrix} {}
simple_kalman_filter_t() [2/3]
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension> constexpr vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::simple_kalman_filter_t (const simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension > &) constexpr delete
simple_kalman_filter_t() [3/3]
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension> constexpr vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::simple_kalman_filter_t (simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension > &&) constexpr delete noexcept
Member Function Documentation
predict()
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension> void vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::predict (const numeric_vector< L_ > & u = {}) inline
Kalman filter prediction
Parameters
u control input vector
Definition at line 68 of file kalman.h.
                                                   {}) {
            x_ = vt::move(F_ * x_ + B_ * u);
            P_ = vt::move(F_ * P_.matmul_T(F_) + Q_);
        }
update() [1/2]
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension> void vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::update (const numeric_vector< M_ > & z) inline
Kalman filter update
Parameters
z Measurement vector
Definition at line 78 of file kalman.h.
{
            numeric_vector<M_> y_ = vt::move(z - H_ * x_);
            numeric_matrix<N_, M_> P_H_t = vt::move(P_.matmul_T(H_));
            numeric_matrix<N_, M_> K_ = vt::move(P_H_t * (H_ * P_H_t + R_).inverse());
            x_ += K_ * y_;
            P_ = vt::move((numeric_matrix<N_, N_>::identity() - K_ * H_) * P_);
        }
References vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::H_, vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::P_, vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::R_, and vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::x_.
update() [2/2]
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension> template<typename ... Ts> void vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::update (Ts ... vs) inline
Definition at line 87 of file kalman.h.
{ update(make_numeric_vector({vs...})); }
References vt::make_numeric_vector(), and vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::update().
Referenced by vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::update().
Member Data Documentation
N_
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension> constexpr size_t vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::N_ = StateVectorDimension static constexpr private
Definition at line 24 of file kalman.h.
M_
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension> constexpr size_t vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::M_ = MeasurementVectorDimension static constexpr private
Definition at line 25 of file kalman.h.
L_
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension> constexpr size_t vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::L_ = ControlVectorDimension static constexpr private
Definition at line 26 of file kalman.h.
F_
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension> const numeric_matrix<N_, N_>& vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::F_ protected
Definition at line 29 of file kalman.h.
B_
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension> const numeric_matrix<N_, L_>& vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::B_ protected
Definition at line 30 of file kalman.h.
H_
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension> const numeric_matrix<M_, N_>& vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::H_ protected
Definition at line 31 of file kalman.h.
Referenced by vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::update().
Q_
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension> const numeric_matrix<N_, N_>& vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::Q_ protected
Definition at line 32 of file kalman.h.
R_
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension> const numeric_matrix<M_, M_>& vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::R_ protected
Definition at line 33 of file kalman.h.
Referenced by vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::update().
x_
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension> numeric_vector<N_> vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::x_ protected
Definition at line 34 of file kalman.h.
Referenced by vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::update().
P_
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension> numeric_matrix<N_, N_> vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::P_ protected
Definition at line 35 of file kalman.h.
Referenced by vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::update().
state_vector
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension> const numeric_vector<N_>& vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::state_vector = x_
Definition at line 89 of file kalman.h.
The documentation for this class was generated from the following file:
include/kalman.h