VT Linear Algebra Library: vt::iterator< T > Class Template Reference
vt::iterator< T > Class Template Reference
#include <iterator.h>
Public Member Functions
constexpr iterator (T *ptr)
constexpr iterator (const iterator &other)
T & operator* ()
T * operator-> ()
constexpr iterator operator+ (size_t n) const
iterator & operator++ ()
const iterator operator++ (int)
constexpr iterator operator- (size_t n) const
constexpr size_t operator- (iterator other) const
iterator & operator-- ()
const iterator operator-- (int)
constexpr bool operator== (const iterator &other) const
constexpr bool operator!= (const iterator &other) const
constexpr bool operator== (T *ptr) const
constexpr bool operator!= (T *ptr) const
Private Attributes
T * ptr_
Detailed Description
template<typename T>
class vt::iterator< T >
Definition at line 8 of file iterator.h.
Constructor & Destructor Documentation
iterator() [1/2]
template<typename T > constexpr vt::iterator< T >::iterator (T * ptr) inline explicit constexpr
Definition at line 13 of file iterator.h.
: ptr_(ptr) {}
iterator() [2/2]
template<typename T > constexpr vt::iterator< T >::iterator (const iterator< T > & other) inline constexpr
Definition at line 15 of file iterator.h.
: ptr_(other.ptr_) {}
Member Function Documentation
operator*()
template<typename T > T & vt::iterator< T >::operator* () inline
Definition at line 17 of file iterator.h.
{ return *ptr_; }
References vt::iterator< T >::ptr_.
operator->()
template<typename T > T * vt::iterator< T >::operator-> () inline
Definition at line 19 of file iterator.h.
{ return ptr_; }
References vt::iterator< T >::ptr_.
operator+()
template<typename T > constexpr iterator vt::iterator< T >::operator+ (size_t n) const inline constexpr
Definition at line 21 of file iterator.h.
{ return iterator(ptr_ + n); }
References vt::iterator< T >::ptr_.
operator++() [1/2]
template<typename T > iterator & vt::iterator< T >::operator++ () inline
Definition at line 23 of file iterator.h.
{
            ++ptr_;
            return *this;
        }
References vt::iterator< T >::ptr_.
Referenced by vt::iterator< T >::operator++().
operator++() [2/2]
template<typename T > const iterator vt::iterator< T >::operator++ (int) inline
Definition at line 28 of file iterator.h.
{
            iterator tmp(*this);
            operator++();
            return tmp;
        }
References vt::iterator< T >::operator++().
operator-() [1/2]
template<typename T > constexpr iterator vt::iterator< T >::operator- (size_t n) const inline constexpr
Definition at line 34 of file iterator.h.
{ return iterator(ptr_ - n); }
References vt::iterator< T >::ptr_.
operator-() [2/2]
template<typename T > constexpr size_t vt::iterator< T >::operator- (iterator< T > other) const inline constexpr
Definition at line 36 of file iterator.h.
{ return ptr_ - other.ptr_; }
References vt::iterator< T >::ptr_.
operator--() [1/2]
template<typename T > iterator & vt::iterator< T >::operator-- () inline
Definition at line 38 of file iterator.h.
{
            --ptr_;
            return *this;
        }
References vt::iterator< T >::ptr_.
Referenced by vt::iterator< T >::operator--().
operator--() [2/2]
template<typename T > const iterator vt::iterator< T >::operator-- (int) inline
Definition at line 43 of file iterator.h.
{
            iterator tmp(*this);
            operator--();
            return tmp;
        }
References vt::iterator< T >::operator--().
operator==() [1/2]
template<typename T > constexpr bool vt::iterator< T >::operator== (const iterator< T > & other) const inline constexpr
Definition at line 49 of file iterator.h.
{ return ptr_ == other.ptr_; }
References vt::iterator< T >::ptr_.
Referenced by vt::iterator< T >::operator!=(), and vt::iterator< T >::operator!=().
operator!=() [1/2]
template<typename T > constexpr bool vt::iterator< T >::operator!= (const iterator< T > & other) const inline constexpr
Definition at line 51 of file iterator.h.
{ return !operator==(other); }
References vt::iterator< T >::operator==().
operator==() [2/2]
template<typename T > constexpr bool vt::iterator< T >::operator== (T * ptr) const inline constexpr
Definition at line 53 of file iterator.h.
{ return ptr_ == ptr; }
References vt::iterator< T >::ptr_.
operator!=() [2/2]
template<typename T > constexpr bool vt::iterator< T >::operator!= (T * ptr) const inline constexpr
Definition at line 55 of file iterator.h.
{ return !operator==(ptr); }
References vt::iterator< T >::operator==().
Member Data Documentation
ptr_
template<typename T > T* vt::iterator< T >::ptr_ private
Definition at line 10 of file iterator.h.
Referenced by vt::iterator< T >::operator*(), vt::iterator< T >::operator+(), vt::iterator< T >::operator++(), vt::iterator< T >::operator-(), vt::iterator< T >::operator-(), vt::iterator< T >::operator--(), vt::iterator< T >::operator->(), vt::iterator< T >::operator==(), and vt::iterator< T >::operator==().
The documentation for this class was generated from the following file:
include/iterator.h