VT Linear Algebra Library: vt::numeric_matrix_dynamic_t< T > Class Template Reference
vt::numeric_matrix_dynamic_t< T > Class Template Reference
#include <dynamic_numeric_matrix.h>
Public Member Functions
numeric_matrix_dynamic_t ()
numeric_matrix_dynamic_t (size_t n)
numeric_matrix_dynamic_t (size_t rows, size_t cols)
numeric_matrix_dynamic_t (size_t rows, size_t cols, T fill)
numeric_matrix_dynamic_t (const numeric_matrix_dynamic_t &other)
numeric_matrix_dynamic_t (numeric_matrix_dynamic_t &&other) noexcept
template<size_t R, size_t C>
numeric_matrix_dynamic_t (const T(&array)[R][C])
template<size_t R>
numeric_matrix_dynamic_t (const numeric_vector_dynamic_t< T >(&vectors)[R])
numeric_matrix_dynamic_t (const numeric_matrix_dynamic_t &M11, const numeric_matrix_dynamic_t &M12, const numeric_matrix_dynamic_t &M21, const numeric_matrix_dynamic_t &M22)
numeric_vector_dynamic_t< T > & operator[] (size_t index)
const numeric_vector_dynamic_t< T > & operator[] (size_t index) const
T & at (size_t r_index, size_t c_index)
const T & at (size_t r_index, size_t c_index) const
T & operator() (size_t r_index, size_t c_index)
const T & operator() (size_t r_index, size_t c_index) const
numeric_matrix_dynamic_t & operator= (const numeric_matrix_dynamic_t &other)
numeric_matrix_dynamic_t & operator= (numeric_matrix_dynamic_t &&other) noexcept
template<size_t R, size_t C>
numeric_matrix_dynamic_t & operator= (const T(&array)[R][C])
template<size_t R>
numeric_matrix_dynamic_t & operator= (const numeric_vector_dynamic_t< T >(&vectors)[R])
numeric_matrix_dynamic_t & operator+= (const numeric_matrix_dynamic_t &other)
numeric_matrix_dynamic_t operator+ (const numeric_matrix_dynamic_t &other) const
numeric_matrix_dynamic_t add (const numeric_matrix_dynamic_t &other) const
numeric_matrix_dynamic_t & operator-= (const numeric_matrix_dynamic_t &other)
numeric_matrix_dynamic_t operator- (const numeric_matrix_dynamic_t &other) const
numeric_matrix_dynamic_t sub (const numeric_matrix_dynamic_t &other) const
numeric_matrix_dynamic_t & operator*= (const numeric_matrix_dynamic_t &other)
numeric_matrix_dynamic_t operator* (const numeric_matrix_dynamic_t &other) const
numeric_matrix_dynamic_t & operator*= (T rhs)
numeric_matrix_dynamic_t operator* (T rhs) const
numeric_vector_dynamic_t< T > operator* (const numeric_vector_dynamic_t< T > &other) const
numeric_matrix_dynamic_t matmul (const numeric_matrix_dynamic_t &other) const
numeric_matrix_dynamic_t matmul_naive (const numeric_matrix_dynamic_t &other) const
numeric_vector_dynamic_t< T > transform (const numeric_vector_dynamic_t< T > &other) const
numeric_matrix_dynamic_t & operator^= (size_t n)
numeric_matrix_dynamic_t operator^ (size_t n)
numeric_matrix_dynamic_t matpow (size_t n)
numeric_matrix_dynamic_t matpow_naive (size_t n)
bool operator== (const numeric_matrix_dynamic_t &other) const
template<size_t R, size_t C>
bool operator== (const T(&array)[R][C]) const
bool operator!= (const numeric_matrix_dynamic_t &other) const
template<size_t R, size_t C>
bool operator!= (const T(&array)[R][C]) const
bool equals (const numeric_matrix_dynamic_t &other) const
bool float_equals (const numeric_matrix_dynamic_t &other) const
template<size_t R, size_t C>
bool equals (const T(&array)[R][C]) const
bool is_square () const
bool caNmultiply_with (const numeric_matrix_dynamic_t &other) const
bool caNmultiply_with (const numeric_vector_dynamic_t< T > &other) const
numeric_vector_dynamic_t< T > row (size_t r_index) const
numeric_vector_dynamic_t< T > col (size_t c_index) const
numeric_vector_dynamic_t< T > diag ()
numeric_matrix_dynamic_t transpose () const
T det () const
T tr () const
numeric_matrix_dynamic_t inv () const
constexpr numeric_matrix_dynamic_t inverse () const
numeric_matrix_dynamic_t RRE () const
numeric_matrix_dynamic_lu_t< T > LU () const
void insert (const numeric_matrix_dynamic_t &M)
template<size_t R, size_t C>
void insert (const T(&array)[R][C])
void insert (size_t pos_row, size_t pos_col, const numeric_matrix_dynamic_t &M)
template<size_t R, size_t C>
void insert (size_t pos_row, size_t pos_col, const T(&array)[R][C])
numeric_matrix_dynamic_t slice (size_t r1, size_t c1, size_t r2, size_t c2) const
void swap (numeric_matrix_dynamic_t &other)
iterator< numeric_vector_dynamic_t< T > > begin ()
iterator< numeric_vector_dynamic_t< T > > begin () const
iterator< numeric_vector_dynamic_t< T > > end ()
iterator< numeric_vector_dynamic_t< T > > end () const
constexpr size_t r () const
constexpr size_t c () const
constexpr size_t n () const
Static Public Member Functions
static numeric_matrix_dynamic_t & iadd (numeric_matrix_dynamic_t &C, const numeric_matrix_dynamic_t &A, const numeric_matrix_dynamic_t &B)
static numeric_matrix_dynamic_t & isub (numeric_matrix_dynamic_t &C, const numeric_matrix_dynamic_t &A, const numeric_matrix_dynamic_t &B)
static numeric_matrix_dynamic_t & imatmul (numeric_matrix_dynamic_t &C, const numeric_matrix_dynamic_t &A, const numeric_matrix_dynamic_t &B)
static constexpr bool is_multiple_of_2 (size_t x)
static size_t closest_2 (size_t x)
static numeric_matrix_dynamic_t zeros (size_t r, size_t c)
static numeric_matrix_dynamic_t zeros (size_t n)
static numeric_matrix_dynamic_t ones (size_t r, size_t c)
static numeric_matrix_dynamic_t ones (size_t n)
static numeric_matrix_dynamic_t identity (size_t n)
static numeric_matrix_dynamic_t id (size_t n)
static numeric_matrix_dynamic_t diagonal (size_t n, T value)
template<typename... Vectors>
static numeric_matrix_dynamic_t from (const Vectors &...vectors)
template<size_t N, typename... Arrays>
static numeric_matrix_dynamic_t from (const Arrays(&...arrays)[N])
static numeric_matrix_dynamic_t from_row (const numeric_vector_dynamic_t< T > &vector)
static numeric_matrix_dynamic_t from_col (const numeric_vector_dynamic_t< T > &vector)
static numeric_matrix_dynamic_t quad (const numeric_matrix_dynamic_t M)
Private Member Functions
void fix_zero ()
void put_array (size_t index, const numeric_vector_dynamic_t< T > &vector)
template<size_t N>
void put_array (size_t index, const T(&array)[N])
template<typename... Vectors>
void put_array (size_t index, const numeric_vector_dynamic_t< T > &vector, const Vectors &...vectors)
template<size_t N, typename... Arrays>
void put_array (size_t index, const T(&array)[N], const Arrays(&...arrays)[N])
void allocate_zero ()
void allocate_fill (T fill)
void steal (numeric_matrix_dynamic_t &&other)
void allocate_from (const numeric_matrix_dynamic_t &other)
template<size_t R, size_t C>
void allocate_from (const T(&array)[R][C])
template<size_t R>
void allocate_from (const numeric_vector_dynamic_t< T >(&vectors)[R])
Static Private Member Functions
static numeric_matrix_dynamic_t & inv_lt (numeric_matrix_dynamic_t &L)
static numeric_matrix_dynamic_t inv_ut (const numeric_matrix_dynamic_t &U)
static numeric_matrix_dynamic_t & mm_naive (numeric_matrix_dynamic_t &C, const numeric_matrix_dynamic_t &A, const numeric_matrix_dynamic_t &B)
static numeric_matrix_dynamic_t & mm_strassen (numeric_matrix_dynamic_t &C, const numeric_matrix_dynamic_t &A, const numeric_matrix_dynamic_t &B)
Private Attributes
size_t r_
size_t c_
numeric_vector_dynamic_t< numeric_vector_dynamic_t< T > > vector_
Static Private Attributes
static constexpr size_t STRASSENDIMENSION = 1024
static constexpr size_t STRASSENTHRESHOLD = STRASSENDIMENSION * STRASSENDIMENSION
Friends
class numeric_vector_dynamic_t< T >
Detailed Description
template<typename T>
class vt::numeric_matrix_dynamic_t< T >
Definition at line 21 of file dynamic_numeric_matrix.h.
Constructor & Destructor Documentation
numeric_matrix_dynamic_t() [1/9]
template<typename T > vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t () inline
Definition at line 33 of file dynamic_numeric_matrix.h.
: r_(0), c_(0), vector_(vt::move(numeric_vector_dynamic_t<numeric_vector_dynamic_t<T>>())) {}
Referenced by vt::numeric_matrix_dynamic_t< T >::mm_strassen(), vt::numeric_matrix_dynamic_t< T >::ones(), vt::numeric_matrix_dynamic_t< T >::ones(), vt::numeric_matrix_dynamic_t< T >::quad(), vt::numeric_matrix_dynamic_t< T >::zeros(), and vt::numeric_matrix_dynamic_t< T >::zeros().
numeric_matrix_dynamic_t() [2/9]
template<typename T > vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t (size_t n) inline explicit
Definition at line 35 of file dynamic_numeric_matrix.h.
: r_(n), c_(n) { allocate_zero(); }
References vt::numeric_matrix_dynamic_t< T >::allocate_zero().
numeric_matrix_dynamic_t() [3/9]
template<typename T > vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t (size_t rows, size_t cols) inline
Definition at line 37 of file dynamic_numeric_matrix.h.
: r_(rows), c_(cols) { allocate_zero(); }
References vt::numeric_matrix_dynamic_t< T >::allocate_zero().
numeric_matrix_dynamic_t() [4/9]
template<typename T > vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t (size_t rows, size_t cols, T fill) inline
Definition at line 39 of file dynamic_numeric_matrix.h.
: r_(rows), c_(cols) { allocate_fill(fill); }
References vt::numeric_matrix_dynamic_t< T >::allocate_fill(), and vt::fill().
numeric_matrix_dynamic_t() [5/9]
template<typename T > vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t (const numeric_matrix_dynamic_t< T > & other) inline
Definition at line 41 of file dynamic_numeric_matrix.h.
: r_(other.r_), c_(other.c_) { allocate_from(other); }
References vt::numeric_matrix_dynamic_t< T >::allocate_from().
numeric_matrix_dynamic_t() [6/9]
template<typename T > vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t (numeric_matrix_dynamic_t< T > && other) inline noexcept
Definition at line 43 of file dynamic_numeric_matrix.h.
                                                                           : r_(other.r_), c_(other.c_) {
            steal(vt::move(other));
            other.r_ = 0;
            other.c_ = 0;
        }
References vt::numeric_matrix_dynamic_t< T >::steal().
numeric_matrix_dynamic_t() [7/9]
template<typename T > template<size_t R, size_t C> vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t (const T(&) array[R][C]) inline explicit
Definition at line 50 of file dynamic_numeric_matrix.h.
: r_(R), c_(C) { allocate_from(array); }
References vt::numeric_matrix_dynamic_t< T >::allocate_from().
numeric_matrix_dynamic_t() [8/9]
template<typename T > template<size_t R> vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t (const numeric_vector_dynamic_t< T >(&) vectors[R]) inline explicit
Definition at line 53 of file dynamic_numeric_matrix.h.
: r_(R), c_(vectors[0].size_) { allocate_from(vectors); }
References vt::numeric_matrix_dynamic_t< T >::allocate_from().
numeric_matrix_dynamic_t() [9/9]
template<typename T > vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t (const numeric_matrix_dynamic_t< T > & M11, const numeric_matrix_dynamic_t< T > & M12, const numeric_matrix_dynamic_t< T > & M21, const numeric_matrix_dynamic_t< T > & M22) inline
Definition at line 55 of file dynamic_numeric_matrix.h.
{
            if (M11.r_ == M12.r_ && M21.r_ == M22.r_ && M11.c_ == M21.c_ && M12.c_ == M22.c_) {
                r_ = M11.r_ + M21.r_;
                c_ = M11.c_ + M12.c_;
                allocate_zero();
                insert(0, 0, M11);
                insert(0, M11.c_, M12);
                insert(M11.r_, 0, M21);
                insert(M11.r_ / 2, M11.c_ / 2, M22);
            } else {
                r_ = vt::max(M11.r_ + M21.r_, M12.r_ + M22.r_);
                c_ = vt::max(M11.c_ + M12.c_, M21.c_ + M22.c_);
                allocate_zero();
            }
        }
References vt::numeric_matrix_dynamic_t< T >::allocate_zero(), vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::insert(), and vt::numeric_matrix_dynamic_t< T >::r_.
Member Function Documentation
operator[]() [1/2]
template<typename T > numeric_vector_dynamic_t< T > & vt::numeric_matrix_dynamic_t< T >::operator[] (size_t index) inline
Definition at line 71 of file dynamic_numeric_matrix.h.
{ return vector_[index]; }
References vt::numeric_matrix_dynamic_t< T >::vector_.
operator[]() [2/2]
template<typename T > const numeric_vector_dynamic_t< T > & vt::numeric_matrix_dynamic_t< T >::operator[] (size_t index) const inline
Definition at line 73 of file dynamic_numeric_matrix.h.
{ return vector_[index]; }
References vt::numeric_matrix_dynamic_t< T >::vector_.
at() [1/2]
template<typename T > T & vt::numeric_matrix_dynamic_t< T >::at (size_t r_index, size_t c_index) inline
Definition at line 75 of file dynamic_numeric_matrix.h.
{ return vector_[r_index][c_index]; };
References vt::numeric_matrix_dynamic_t< T >::vector_.
Referenced by vt::numeric_matrix_dynamic_t< T >::operator()(), and vt::numeric_matrix_dynamic_t< T >::operator()().
at() [2/2]
template<typename T > const T & vt::numeric_matrix_dynamic_t< T >::at (size_t r_index, size_t c_index) const inline
Definition at line 77 of file dynamic_numeric_matrix.h.
{ return vector_[r_index][c_index]; };
References vt::numeric_matrix_dynamic_t< T >::vector_.
operator()() [1/2]
template<typename T > T & vt::numeric_matrix_dynamic_t< T >::operator() (size_t r_index, size_t c_index) inline
Definition at line 79 of file dynamic_numeric_matrix.h.
{ return at(r_index, c_index); }
References vt::numeric_matrix_dynamic_t< T >::at().
operator()() [2/2]
template<typename T > const T & vt::numeric_matrix_dynamic_t< T >::operator() (size_t r_index, size_t c_index) const inline
Definition at line 81 of file dynamic_numeric_matrix.h.
{ return at(r_index, c_index); }
References vt::numeric_matrix_dynamic_t< T >::at().
operator=() [1/4]
template<typename T > numeric_matrix_dynamic_t & vt::numeric_matrix_dynamic_t< T >::operator= (const numeric_matrix_dynamic_t< T > & other) inline
Definition at line 83 of file dynamic_numeric_matrix.h.
{
            if (this != &other) {
                if (r_ == other.r_ && c_ == other.c_) {
                    insert(other);
                } else {
                    allocate_from(other);
                }
            }
            return *this;
        }
References vt::numeric_matrix_dynamic_t< T >::allocate_from(), vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::insert(), and vt::numeric_matrix_dynamic_t< T >::r_.
operator=() [2/4]
template<typename T > numeric_matrix_dynamic_t & vt::numeric_matrix_dynamic_t< T >::operator= (numeric_matrix_dynamic_t< T > && other) inline noexcept
Definition at line 94 of file dynamic_numeric_matrix.h.
{
            if (this != &other) {
                steal(vt::move(other));
                other.r_ = 0;
                other.c_ = 0;
            }
            return *this;
        }
References vt::numeric_matrix_dynamic_t< T >::steal().
operator=() [3/4]
template<typename T > template<size_t R, size_t C> numeric_matrix_dynamic_t & vt::numeric_matrix_dynamic_t< T >::operator= (const T(&) array[R][C]) inline
Definition at line 104 of file dynamic_numeric_matrix.h.
{
            if (r_ == R && c_ == C) {
                insert(array);
            } else {
                allocate_from(array);
            }
            return *this;
        }
References vt::numeric_matrix_dynamic_t< T >::allocate_from(), vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::insert(), and vt::numeric_matrix_dynamic_t< T >::r_.
operator=() [4/4]
template<typename T > template<size_t R> numeric_matrix_dynamic_t & vt::numeric_matrix_dynamic_t< T >::operator= (const numeric_vector_dynamic_t< T >(&) vectors[R]) inline
Definition at line 114 of file dynamic_numeric_matrix.h.
{
            allocate_from(vectors);
            return *this;
        }
References vt::numeric_matrix_dynamic_t< T >::allocate_from().
operator+=()
template<typename T > numeric_matrix_dynamic_t & vt::numeric_matrix_dynamic_t< T >::operator+= (const numeric_matrix_dynamic_t< T > & other) inline
Definition at line 119 of file dynamic_numeric_matrix.h.
{ return iadd(*this, *this, other); }
References vt::numeric_matrix_dynamic_t< T >::iadd().
operator+()
template<typename T > numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::operator+ (const numeric_matrix_dynamic_t< T > & other) const inline
Definition at line 121 of file dynamic_numeric_matrix.h.
{
            numeric_matrix_dynamic_t tmp(*this);
            tmp.operator+=(other);
            return tmp;
        }
Referenced by vt::numeric_matrix_dynamic_t< T >::add().
add()
template<typename T > numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::add (const numeric_matrix_dynamic_t< T > & other) const inline
Definition at line 127 of file dynamic_numeric_matrix.h.
{ return operator+(other); }
References vt::numeric_matrix_dynamic_t< T >::operator+().
iadd()
template<typename T > static numeric_matrix_dynamic_t & vt::numeric_matrix_dynamic_t< T >::iadd (numeric_matrix_dynamic_t< T > & C, const numeric_matrix_dynamic_t< T > & A, const numeric_matrix_dynamic_t< T > & B) inline static
Definition at line 129 of file dynamic_numeric_matrix.h.
{
            for (size_t i = 0; i < C.r_; ++i)
                for (size_t j = 0; j < C.c_; ++j)
                    C[i][j] = A[i][j] + B[i][j];
            return C;
        }
References vt::numeric_matrix_dynamic_t< T >::c_, and vt::numeric_matrix_dynamic_t< T >::r_.
Referenced by vt::numeric_matrix_dynamic_t< T >::operator+=().
operator-=()
template<typename T > numeric_matrix_dynamic_t & vt::numeric_matrix_dynamic_t< T >::operator-= (const numeric_matrix_dynamic_t< T > & other) inline
Definition at line 136 of file dynamic_numeric_matrix.h.
{ return isub(*this, *this, other); }
References vt::numeric_matrix_dynamic_t< T >::isub().
operator-()
template<typename T > numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::operator- (const numeric_matrix_dynamic_t< T > & other) const inline
Definition at line 138 of file dynamic_numeric_matrix.h.
{
            numeric_matrix_dynamic_t tmp(*this);
            tmp.operator-=(other);
            return tmp;
        }
Referenced by vt::numeric_matrix_dynamic_t< T >::sub().
sub()
template<typename T > numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::sub (const numeric_matrix_dynamic_t< T > & other) const inline
Definition at line 144 of file dynamic_numeric_matrix.h.
{ return operator-(other); }
References vt::numeric_matrix_dynamic_t< T >::operator-().
isub()
template<typename T > static numeric_matrix_dynamic_t & vt::numeric_matrix_dynamic_t< T >::isub (numeric_matrix_dynamic_t< T > & C, const numeric_matrix_dynamic_t< T > & A, const numeric_matrix_dynamic_t< T > & B) inline static
Definition at line 146 of file dynamic_numeric_matrix.h.
{
            for (size_t i = 0; i < C.r_; ++i)
                for (size_t j = 0; j < C.c_; ++j)
                    C[i][j] = A[i][j] - B[i][j];
            return C;
        }
References vt::numeric_matrix_dynamic_t< T >::c_, and vt::numeric_matrix_dynamic_t< T >::r_.
Referenced by vt::numeric_matrix_dynamic_t< T >::operator-=().
operator*=() [1/2]
template<typename T > numeric_matrix_dynamic_t & vt::numeric_matrix_dynamic_t< T >::operator*= (const numeric_matrix_dynamic_t< T > & other) inline
Definition at line 153 of file dynamic_numeric_matrix.h.
{
            steal(vt::move(operator*(other)));
            return *this;
        }
References vt::numeric_matrix_dynamic_t< T >::steal().
operator*() [1/3]
template<typename T > numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::operator* (const numeric_matrix_dynamic_t< T > & other) const inline
Definition at line 158 of file dynamic_numeric_matrix.h.
{
            numeric_matrix_dynamic_t C(r_, other.c_);
            return imatmul(C, *this, other);
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::imatmul(), and vt::numeric_matrix_dynamic_t< T >::r_.
Referenced by vt::numeric_matrix_dynamic_t< T >::matmul(), and vt::numeric_matrix_dynamic_t< T >::transform().
operator*=() [2/2]
template<typename T > numeric_matrix_dynamic_t & vt::numeric_matrix_dynamic_t< T >::operator*= (T rhs) inline
Definition at line 163 of file dynamic_numeric_matrix.h.
{
            for (auto &x: vector_) x *= rhs;
            return *this;
        }
References vt::numeric_matrix_dynamic_t< T >::vector_.
operator*() [2/3]
template<typename T > numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::operator* (T rhs) const inline
Definition at line 168 of file dynamic_numeric_matrix.h.
{
            numeric_matrix_dynamic_t tmp(*this);
            tmp.operator*=(rhs);
            return tmp;
        }
operator*() [3/3]
template<typename T > numeric_vector_dynamic_t< T > vt::numeric_matrix_dynamic_t< T >::operator* (const numeric_vector_dynamic_t< T > & other) const inline
Definition at line 174 of file dynamic_numeric_matrix.h.
{
            numeric_vector_dynamic_t<T> tmp(r_);
            for (size_t i = 0; i < r_; ++i) tmp[i] = vector_[i].dot(other);
            return tmp;
        }
References vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_t< T >::vector_.
matmul()
template<typename T > numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::matmul (const numeric_matrix_dynamic_t< T > & other) const inline
Definition at line 180 of file dynamic_numeric_matrix.h.
{ return operator*(other); }
References vt::numeric_matrix_dynamic_t< T >::operator*().
imatmul()
template<typename T > static numeric_matrix_dynamic_t & vt::numeric_matrix_dynamic_t< T >::imatmul (numeric_matrix_dynamic_t< T > & C, const numeric_matrix_dynamic_t< T > & A, const numeric_matrix_dynamic_t< T > & B) inline static
Definition at line 182 of file dynamic_numeric_matrix.h.
{
            if (A.r() != 1 &&
                B.r() != 1 &&
                A.c() != 1 &&
                B.c() != 1 &&
                vt::max(A.r() * A.c(), B.r() * B.c()) >= STRASSENTHRESHOLD)
                return mm_strassen(C, A, B);
            return mm_naive(C, A, B);
        }
References vt::numeric_matrix_dynamic_t< T >::c(), vt::numeric_matrix_dynamic_t< T >::mm_naive(), vt::numeric_matrix_dynamic_t< T >::mm_strassen(), vt::numeric_matrix_dynamic_t< T >::r(), and vt::numeric_matrix_dynamic_t< T >::STRASSENTHRESHOLD.
Referenced by vt::numeric_matrix_dynamic_t< T >::operator*().
matmul_naive()
template<typename T > numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::matmul_naive (const numeric_matrix_dynamic_t< T > & other) const inline
Definition at line 192 of file dynamic_numeric_matrix.h.
{
            numeric_matrix_dynamic_t C(r_, other.c_);
            return mm_naive(C, *this, other);
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::mm_naive(), and vt::numeric_matrix_dynamic_t< T >::r_.
transform()
template<typename T > numeric_vector_dynamic_t< T > vt::numeric_matrix_dynamic_t< T >::transform (const numeric_vector_dynamic_t< T > & other) const inline
Definition at line 197 of file dynamic_numeric_matrix.h.
{ return operator*(other); }
References vt::numeric_matrix_dynamic_t< T >::operator*().
operator^=()
template<typename T > numeric_matrix_dynamic_t & vt::numeric_matrix_dynamic_t< T >::operator^= (size_t n) inline
Definition at line 199 of file dynamic_numeric_matrix.h.
{
            steal(vt::move(operator^(n)));
            return *this;
        }
References vt::numeric_matrix_dynamic_t< T >::n(), and vt::numeric_matrix_dynamic_t< T >::steal().
operator^()
template<typename T > numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::operator^ (size_t n) inline
Definition at line 204 of file dynamic_numeric_matrix.h.
{
            numeric_matrix_dynamic_t product(*this);
            if (n == 0) return id(vt::min(r_, c_));
            if (n == 1) return product;
            product = vt::move(product.operator^(n / 2));
            if (n % 2 == 0) return product.operator*(product);
            else return product.operator*(product).operator*(*this);
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::id(), vt::numeric_matrix_dynamic_t< T >::n(), and vt::numeric_matrix_dynamic_t< T >::r_.
Referenced by vt::numeric_matrix_dynamic_t< T >::matpow().
matpow()
template<typename T > numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::matpow (size_t n) inline
Definition at line 213 of file dynamic_numeric_matrix.h.
{ return operator^(n); }
References vt::numeric_matrix_dynamic_t< T >::n(), and vt::numeric_matrix_dynamic_t< T >::operator^().
matpow_naive()
template<typename T > numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::matpow_naive (size_t n) inline
Definition at line 215 of file dynamic_numeric_matrix.h.
{
            numeric_matrix_dynamic_t product = vt::move(id(r_));
            for (size_t i = 0; i < n; ++i) product *= *this;
            return product;
        }
References vt::numeric_matrix_dynamic_t< T >::n(), and vt::numeric_matrix_dynamic_t< T >::r_.
operator==() [1/2]
template<typename T > bool vt::numeric_matrix_dynamic_t< T >::operator== (const numeric_matrix_dynamic_t< T > & other) const inline
Definition at line 221 of file dynamic_numeric_matrix.h.
{
            if (this == &other) return true;
            if (r_ != other.r_ || c_ != other.c_) return false;
            for (size_t i = 0; i < r_; ++i)
                if (vector_[i] != other.vector_[i])
                    return false;
            return true;
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_t< T >::vector_.
Referenced by vt::numeric_matrix_dynamic_t< T >::equals(), vt::numeric_matrix_dynamic_t< T >::equals(), vt::numeric_matrix_dynamic_t< T >::operator!=(), and vt::numeric_matrix_dynamic_t< T >::operator!=().
operator==() [2/2]
template<typename T > template<size_t R, size_t C> bool vt::numeric_matrix_dynamic_t< T >::operator== (const T(&) array[R][C]) const inline
Definition at line 231 of file dynamic_numeric_matrix.h.
{
            if (r_ != R || c_ != C) return false;
            for (size_t i = 0; i < r_; ++i)
                if (vector_[i] != array[i])
                    return false;
            return true;
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_t< T >::vector_.
operator!=() [1/2]
template<typename T > bool vt::numeric_matrix_dynamic_t< T >::operator!= (const numeric_matrix_dynamic_t< T > & other) const inline
Definition at line 239 of file dynamic_numeric_matrix.h.
{ return !operator==(other); }
References vt::numeric_matrix_dynamic_t< T >::operator==().
operator!=() [2/2]
template<typename T > template<size_t R, size_t C> bool vt::numeric_matrix_dynamic_t< T >::operator!= (const T(&) array[R][C]) const inline
Definition at line 242 of file dynamic_numeric_matrix.h.
{ return !operator==(array); }
References vt::numeric_matrix_dynamic_t< T >::operator==().
equals() [1/2]
template<typename T > bool vt::numeric_matrix_dynamic_t< T >::equals (const numeric_matrix_dynamic_t< T > & other) const inline
Definition at line 244 of file dynamic_numeric_matrix.h.
{ return operator==(other); }
References vt::numeric_matrix_dynamic_t< T >::operator==().
float_equals()
template<typename T > bool vt::numeric_matrix_dynamic_t< T >::float_equals (const numeric_matrix_dynamic_t< T > & other) const inline
Definition at line 246 of file dynamic_numeric_matrix.h.
{
            if (this == &other) return true;
            if (r_ != other.r_ || c_ != other.c_) return false;
            for (size_t i = 0; i < r_; ++i)
                if (!vector_[i].float_equals(other.vector_[i]))
                    return false;
            return true;
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::float_equals(), vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_t< T >::vector_.
Referenced by vt::numeric_matrix_dynamic_t< T >::float_equals().
equals() [2/2]
template<typename T > template<size_t R, size_t C> bool vt::numeric_matrix_dynamic_t< T >::equals (const T(&) array[R][C]) const inline
Definition at line 256 of file dynamic_numeric_matrix.h.
{ return operator==(array); }
References vt::numeric_matrix_dynamic_t< T >::operator==().
is_square()
template<typename T > bool vt::numeric_matrix_dynamic_t< T >::is_square () const inline
Definition at line 258 of file dynamic_numeric_matrix.h.
{ return r_ == c_; }
References vt::numeric_matrix_dynamic_t< T >::c_, and vt::numeric_matrix_dynamic_t< T >::r_.
caNmultiply_with() [1/2]
template<typename T > bool vt::numeric_matrix_dynamic_t< T >::caNmultiply_with (const numeric_matrix_dynamic_t< T > & other) const inline
Definition at line 260 of file dynamic_numeric_matrix.h.
{ return c_ == other.r_; }
References vt::numeric_matrix_dynamic_t< T >::c_, and vt::numeric_matrix_dynamic_t< T >::r_.
caNmultiply_with() [2/2]
template<typename T > bool vt::numeric_matrix_dynamic_t< T >::caNmultiply_with (const numeric_vector_dynamic_t< T > & other) const inline
Definition at line 262 of file dynamic_numeric_matrix.h.
{ return c_ == other.size_; }
References vt::numeric_matrix_dynamic_t< T >::c_, and vt::numeric_vector_dynamic_t< T >::size_.
row()
template<typename T > numeric_vector_dynamic_t< T > vt::numeric_matrix_dynamic_t< T >::row (size_t r_index) const inline
Definition at line 264 of file dynamic_numeric_matrix.h.
{ return numeric_vector_dynamic_t<T>(operator[](r_index)); }
References vt::numeric_matrix_dynamic_t< T >::numeric_vector_dynamic_t< T >.
col()
template<typename T > numeric_vector_dynamic_t< T > vt::numeric_matrix_dynamic_t< T >::col (size_t c_index) const inline
Definition at line 266 of file dynamic_numeric_matrix.h.
{
            numeric_vector_dynamic_t<T> tmp(r_);
            for (size_t i = 0; i < r_; ++i) tmp[i] = vector_[i][c_index];
            return tmp;
        }
References vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_t< T >::vector_.
diag()
template<typename T > numeric_vector_dynamic_t< T > vt::numeric_matrix_dynamic_t< T >::diag () inline
Definition at line 272 of file dynamic_numeric_matrix.h.
{
            size_t miNdim = vt::min(r_, c_);
            numeric_vector_dynamic_t<T> tmp(miNdim);
            for (size_t i = 0; i < miNdim; ++i) tmp[i] = vector_[i][i];
            return tmp;
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_t< T >::vector_.
transpose()
template<typename T > numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::transpose () const inline
Definition at line 279 of file dynamic_numeric_matrix.h.
{
            numeric_matrix_dynamic_t tmp(c_, r_);
            for (size_t i = 0; i < r_; ++i)
                for (size_t j = 0; j < c_; ++j)
                    tmp.vector_[j][i] = vector_[i][j];
            return tmp;
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_t< T >::vector_.
Referenced by vt::numeric_matrix_dynamic_t< T >::inv_ut().
det()
template<typename T > T vt::numeric_matrix_dynamic_t< T >::det () const inline
Definition at line 287 of file dynamic_numeric_matrix.h.
                      {
            numeric_matrix_dynamic_lu_t<T> lu = vt::move(LU());
            T det = 1;
            size_t r_swaps = 0;
            size_t n = vt::min(r_, c_);
            for (size_t i = 0; i < n; ++i) {
                det *= lu.u()[i][i];
                if (lu.u()[i][i] == 0) return 0;
                if (lu.l()[i][i] != 1) ++r_swaps;
            }
            return (r_swaps % 2 == 0) ? det : -det;
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::det(), vt::numeric_matrix_dynamic_lu_t< T >::l(), vt::numeric_matrix_dynamic_t< T >::LU(), vt::numeric_matrix_dynamic_t< T >::n(), vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_lu_t< T >::u().
Referenced by vt::numeric_matrix_dynamic_t< T >::det(), and vt::det().
tr()
template<typename T > T vt::numeric_matrix_dynamic_t< T >::tr () const inline
Definition at line 300 of file dynamic_numeric_matrix.h.
                     {
            T acc = 0;
            size_t n = vt::min(r_, c_);
            for (size_t i = 0; i < n; ++i) acc += vector_[i][i];
            return acc;
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::n(), vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_t< T >::vector_.
Referenced by vt::tr().
inv()
template<typename T > numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::inv () const inline
Definition at line 307 of file dynamic_numeric_matrix.h.
{
            numeric_matrix_dynamic_lu_t<T> lu = vt::move(LU());
            return inv_ut(lu.u()) * inv_lt(lu.l());
        }
References vt::numeric_matrix_dynamic_t< T >::inv_lt(), vt::numeric_matrix_dynamic_t< T >::inv_ut(), vt::numeric_matrix_dynamic_lu_t< T >::l(), vt::numeric_matrix_dynamic_t< T >::LU(), and vt::numeric_matrix_dynamic_lu_t< T >::u().
Referenced by vt::inv(), and vt::numeric_matrix_dynamic_t< T >::inverse().
inverse()
template<typename T > constexpr numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::inverse () const inline constexpr
Definition at line 312 of file dynamic_numeric_matrix.h.
{ return inv(); }
References vt::numeric_matrix_dynamic_t< T >::inv().
Referenced by vt::extended_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::update().
RRE()
template<typename T > numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::RRE () const inline
Definition at line 314 of file dynamic_numeric_matrix.h.
{
            numeric_matrix_dynamic_t m(*this);
            size_t lead = 0;
            for (size_t r = 0; r < r_; ++r) {
                if (lead >= c_) return m;
                size_t i;
                for (i = r; m[i][lead] == 0;) {
                    ++i;
                    if (i == r_) {
                        i = r;
                        ++lead;
                        if (lead == c_) return m;
                    }
                }
                m[i].swap(m[r]);
                T val = m[r][lead];
                for (size_t j = 0; j < c_; ++j) m[r][j] /= val;
                for (i = 0; i < r_; ++i) {
                    if (i != r) {
                        val = m[i][lead];
                        for (size_t j = 0; j < c_; ++j)
                            m[i][j] -= val * m[r][j];
                    }
                }
                ++lead;
            }
            m.fix_zero();
            return m;
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::fix_zero(), vt::numeric_matrix_dynamic_t< T >::r(), vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_t< T >::swap().
LU()
template<typename T > numeric_matrix_dynamic_lu_t< T > vt::numeric_matrix_dynamic_t< T >::LU () const inline
Definition at line 344 of file dynamic_numeric_matrix.h.
{
            size_t n = vt::min(r_, c_);
            numeric_matrix_dynamic_t lower(n, n);
            numeric_matrix_dynamic_t upper(n, n);
            for (size_t i = 0; i < n; ++i) {
                for (size_t k = 0; k < n; ++k) {
                    T sum_ = 0;
                    for (size_t j = 0; j < i; ++j) sum_ += lower[i][j] * upper[j][k];
                    upper[i][k] = vector_[i][k] - sum_;
                }
                for (size_t k = i; k < n; ++k) {
                    if (i == k) lower[i][i] = 1;
                    else {
                        T sum_ = 0;
                        for (size_t j = 0; j < i; ++j) sum_ += lower[k][j] * upper[j][i];
                        lower[k][i] = (vector_[k][i] - sum_) / upper[i][i];
                    }
                }
            }
            return {lower, upper};
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::n(), vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_t< T >::vector_.
Referenced by vt::numeric_matrix_dynamic_t< T >::det(), and vt::numeric_matrix_dynamic_t< T >::inv().
insert() [1/4]
template<typename T > void vt::numeric_matrix_dynamic_t< T >::insert (const numeric_matrix_dynamic_t< T > & M) inline
Definition at line 366 of file dynamic_numeric_matrix.h.
{ insert(0, 0, M); }
References vt::numeric_matrix_dynamic_t< T >::insert().
Referenced by vt::numeric_matrix_dynamic_t< T >::insert(), vt::numeric_matrix_dynamic_t< T >::mm_strassen(), vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t(), vt::numeric_matrix_dynamic_t< T >::operator=(), and vt::numeric_matrix_dynamic_t< T >::operator=().
insert() [2/4]
template<typename T > template<size_t R, size_t C> void vt::numeric_matrix_dynamic_t< T >::insert (const T(&) array[R][C]) inline
Definition at line 369 of file dynamic_numeric_matrix.h.
{ insert(0, 0, array); }
References vt::numeric_matrix_dynamic_t< T >::insert().
Referenced by vt::numeric_matrix_dynamic_t< T >::insert().
insert() [3/4]
template<typename T > void vt::numeric_matrix_dynamic_t< T >::insert (size_t pos_row, size_t pos_col, const numeric_matrix_dynamic_t< T > & M) inline
Definition at line 371 of file dynamic_numeric_matrix.h.
{
            if (pos_row >= r_ || pos_col >= c_ || pos_row + M.r_ > r_ || pos_col + M.c_ > c_) return;
            for (size_t i = 0; i < M.r_; ++i)
                for (size_t j = 0; j < M.c_; ++j)
                    vector_[i + pos_row][j + pos_col] = M[i][j];
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_t< T >::vector_.
insert() [4/4]
template<typename T > template<size_t R, size_t C> void vt::numeric_matrix_dynamic_t< T >::insert (size_t pos_row, size_t pos_col, const T(&) array[R][C]) inline
Definition at line 379 of file dynamic_numeric_matrix.h.
{
            if (pos_row >= r_ || pos_col >= c_ || pos_row + R > r_ || pos_col + C > c_) return;
            for (size_t i = 0; i < R; ++i)
                for (size_t j = 0; j < C; ++j)
                    vector_[i + pos_row][j + pos_col] = array[i][j];
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_t< T >::vector_.
slice()
template<typename T > numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::slice (size_t r1, size_t c1, size_t r2, size_t c2) const inline
Definition at line 386 of file dynamic_numeric_matrix.h.
{
            if (r1 > r2) vt::swap(r1, r2);
            if (c1 > c2) vt::swap(c1, c2);
            r2 = vt::min(r2, r_);
            c2 = vt::min(c2, c_);
            size_t r = r2 - r1;
            size_t c = c2 - c1;
            numeric_matrix_dynamic_t result(r, c);
            if (r == 0 || c == 0 || r1 >= r_ || c1 >= c_) return result;
            for (size_t i = 0; i < r; ++i)
                for (size_t j = 0; j < c; ++j)
                    result[i][j] = vector_[r1 + i][c1 + j];
            return result;
        }
References vt::numeric_matrix_dynamic_t< T >::c(), vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::r(), vt::numeric_matrix_dynamic_t< T >::r_, vt::swap(), and vt::numeric_matrix_dynamic_t< T >::vector_.
Referenced by vt::numeric_matrix_dynamic_t< T >::mm_strassen().
swap()
template<typename T > void vt::numeric_matrix_dynamic_t< T >::swap (numeric_matrix_dynamic_t< T > & other) inline
Definition at line 401 of file dynamic_numeric_matrix.h.
{
            vt::swap(vector_, other.vector_);
            vt::swap(r_, other.r_);
            vt::swap(c_, other.c_);
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::r_, vt::swap(), and vt::numeric_matrix_dynamic_t< T >::vector_.
Referenced by vt::numeric_matrix_dynamic_t< T >::RRE().
begin() [1/2]
template<typename T > iterator< numeric_vector_dynamic_t< T > > vt::numeric_matrix_dynamic_t< T >::begin () inline
Definition at line 407 of file dynamic_numeric_matrix.h.
{ return vector_.begin(); }
References vt::numeric_matrix_dynamic_t< T >::vector_.
begin() [2/2]
template<typename T > iterator< numeric_vector_dynamic_t< T > > vt::numeric_matrix_dynamic_t< T >::begin () const inline
Definition at line 409 of file dynamic_numeric_matrix.h.
{ return vector_.begin(); }
References vt::numeric_matrix_dynamic_t< T >::vector_.
end() [1/2]
template<typename T > iterator< numeric_vector_dynamic_t< T > > vt::numeric_matrix_dynamic_t< T >::end () inline
Definition at line 411 of file dynamic_numeric_matrix.h.
{ return vector_.end(); }
References vt::numeric_matrix_dynamic_t< T >::vector_.
end() [2/2]
template<typename T > iterator< numeric_vector_dynamic_t< T > > vt::numeric_matrix_dynamic_t< T >::end () const inline
Definition at line 413 of file dynamic_numeric_matrix.h.
{ return vector_.end(); }
References vt::numeric_matrix_dynamic_t< T >::vector_.
r()
template<typename T > constexpr size_t vt::numeric_matrix_dynamic_t< T >::r () const inline constexpr
Definition at line 415 of file dynamic_numeric_matrix.h.
{ return r_; }
References vt::numeric_matrix_dynamic_t< T >::r_.
Referenced by vt::numeric_matrix_dynamic_t< T >::imatmul(), vt::numeric_matrix_dynamic_t< T >::ones(), vt::numeric_matrix_dynamic_t< T >::RRE(), vt::numeric_matrix_dynamic_t< T >::slice(), and vt::numeric_matrix_dynamic_t< T >::zeros().
c()
template<typename T > constexpr size_t vt::numeric_matrix_dynamic_t< T >::c () const inline constexpr
Definition at line 417 of file dynamic_numeric_matrix.h.
{ return c_; }
References vt::numeric_matrix_dynamic_t< T >::c_.
Referenced by vt::numeric_matrix_dynamic_t< T >::imatmul(), vt::numeric_matrix_dynamic_t< T >::ones(), vt::numeric_matrix_dynamic_t< T >::slice(), and vt::numeric_matrix_dynamic_t< T >::zeros().
n()
template<typename T > constexpr size_t vt::numeric_matrix_dynamic_t< T >::n () const inline constexpr
Definition at line 419 of file dynamic_numeric_matrix.h.
{ return r_ * c_; }
References vt::numeric_matrix_dynamic_t< T >::c_, and vt::numeric_matrix_dynamic_t< T >::r_.
Referenced by vt::numeric_matrix_dynamic_t< T >::det(), vt::numeric_matrix_dynamic_t< T >::diagonal(), vt::numeric_matrix_dynamic_t< T >::id(), vt::numeric_matrix_dynamic_t< T >::identity(), vt::numeric_matrix_dynamic_t< T >::inv_lt(), vt::numeric_matrix_dynamic_t< T >::LU(), vt::numeric_matrix_dynamic_t< T >::matpow(), vt::numeric_matrix_dynamic_t< T >::matpow_naive(), vt::numeric_matrix_dynamic_t< T >::ones(), vt::numeric_matrix_dynamic_t< T >::operator^(), vt::numeric_matrix_dynamic_t< T >::operator^=(), vt::numeric_matrix_dynamic_t< T >::tr(), and vt::numeric_matrix_dynamic_t< T >::zeros().
is_multiple_of_2()
template<typename T > static constexpr bool vt::numeric_matrix_dynamic_t< T >::is_multiple_of_2 (size_t x) inline static constexpr
Definition at line 422 of file dynamic_numeric_matrix.h.
{ return x != 0 && !(x & (x - 1)); }
Referenced by vt::numeric_matrix_dynamic_t< T >::closest_2().
closest_2()
template<typename T > static size_t vt::numeric_matrix_dynamic_t< T >::closest_2 (size_t x) inline static
Definition at line 424 of file dynamic_numeric_matrix.h.
{
            if (is_multiple_of_2(x)) return x;
            size_t result = 1;
            while (x != 0) {
                x >>= 1;
                result <<= 1;
            }
            return result;
        }
References vt::numeric_matrix_dynamic_t< T >::is_multiple_of_2().
Referenced by vt::numeric_matrix_dynamic_t< T >::mm_strassen().
inv_lt()
template<typename T > static numeric_matrix_dynamic_t & vt::numeric_matrix_dynamic_t< T >::inv_lt (numeric_matrix_dynamic_t< T > & L) inline static private
Definition at line 435 of file dynamic_numeric_matrix.h.
{
            size_t n = vt::min(L.r_, L.c_);
            numeric_matrix_dynamic_t X(n);
            for (size_t k = 0; k < n; ++k) {
                X[k][k] = 1 / L[k][k];
                for (size_t i = k + 1; i < n; ++i) {
                    T acc = 0;
                    for (size_t j = k; j < i; ++j)
                        acc -= L[i][j] * X[j][k];
                    X[i][k] = acc / L[i][i];
                }
            }
            L = vt::move(X);
            return L;
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::n(), and vt::numeric_matrix_dynamic_t< T >::r_.
Referenced by vt::numeric_matrix_dynamic_t< T >::inv(), and vt::numeric_matrix_dynamic_t< T >::inv_ut().
inv_ut()
template<typename T > static numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::inv_ut (const numeric_matrix_dynamic_t< T > & U) inline static private
Definition at line 451 of file dynamic_numeric_matrix.h.
{
            numeric_matrix_dynamic_t tmp = vt::move(U.transpose());
            return inv_lt(tmp).transpose();
        }
References vt::numeric_matrix_dynamic_t< T >::inv_lt(), and vt::numeric_matrix_dynamic_t< T >::transpose().
Referenced by vt::numeric_matrix_dynamic_t< T >::inv().
mm_naive()
template<typename T > static numeric_matrix_dynamic_t & vt::numeric_matrix_dynamic_t< T >::mm_naive (numeric_matrix_dynamic_t< T > & C, const numeric_matrix_dynamic_t< T > & A, const numeric_matrix_dynamic_t< T > & B) inline static private
Definition at line 456 of file dynamic_numeric_matrix.h.
{
            for (size_t i = 0; i < A.r_; ++i) {
                numeric_vector_dynamic_t<T> &row_C = C[i];
                for (size_t k = 0; k < A.c_; ++k) {
                    const T &val_A = A[i][k];
                    for (size_t j = 0; j < B.c_; ++j) {
                        row_C[j] += val_A * B[k][j];
                    }
                }
            }
            return C;
        }
References vt::numeric_matrix_dynamic_t< T >::c_, and vt::numeric_matrix_dynamic_t< T >::r_.
Referenced by vt::numeric_matrix_dynamic_t< T >::imatmul(), and vt::numeric_matrix_dynamic_t< T >::matmul_naive().
mm_strassen()
template<typename T > static numeric_matrix_dynamic_t & vt::numeric_matrix_dynamic_t< T >::mm_strassen (numeric_matrix_dynamic_t< T > & C, const numeric_matrix_dynamic_t< T > & A, const numeric_matrix_dynamic_t< T > & B) inline static private
Definition at line 469 of file dynamic_numeric_matrix.h.
{
            size_t rA = closest_2(A.r_);
            size_t cA = closest_2(A.c_);
            size_t rB = closest_2(B.r_);
            size_t cB = closest_2(B.c_);
            numeric_matrix_dynamic_t A11, A12, A21, A22, B11, B12, B21, B22;
            if (rA == A.r_ && cA == A.c_ && rB == B.r_ && cB == B.c_) {
                A11 = vt::move(A.slice(0, 0, rA / 2, cA / 2));
                A12 = vt::move(A.slice(0, cA / 2, rA / 2, cA));
                A21 = vt::move(A.slice(rA / 2, 0, rA, cA / 2));
                A22 = vt::move(A.slice(rA / 2, cA / 2, rA, cA));
                B11 = vt::move(B.slice(0, 0, rB / 2, cB / 2));
                B12 = vt::move(B.slice(0, cB / 2, rB / 2, cB));
                B21 = vt::move(B.slice(rB / 2, 0, rB, cB / 2));
                B22 = vt::move(B.slice(rB / 2, cB / 2, rB, cB));
            } else {
                numeric_matrix_dynamic_t Ap(rA, cA);
                Ap.insert(A);
                numeric_matrix_dynamic_t Bp(rB, cB);
                Bp.insert(B);
                A11 = vt::move(Ap.slice(0, 0, rA / 2, cA / 2));
                A12 = vt::move(Ap.slice(0, cA / 2, rA / 2, cA));
                A21 = vt::move(Ap.slice(rA / 2, 0, rA, cA / 2));
                A22 = vt::move(Ap.slice(rA / 2, cA / 2, rA, cA));
                B11 = vt::move(Bp.slice(0, 0, rB / 2, cB / 2));
                B12 = vt::move(Bp.slice(0, cB / 2, rB / 2, cB));
                B21 = vt::move(Bp.slice(rB / 2, 0, rB, cB / 2));
                B22 = vt::move(Bp.slice(rB / 2, cB / 2, rB, cB));
                C = vt::move(numeric_matrix_dynamic_t(rA, cB));
            }
            numeric_matrix_dynamic_t M1 = vt::move((A11 + A22) * (B11 + B22));
            numeric_matrix_dynamic_t M2 = vt::move((A21 + A22) * B11);
            numeric_matrix_dynamic_t M3 = vt::move(A11 * (B12 - B22));
            numeric_matrix_dynamic_t M4 = vt::move(A22 * (B21 - B11));
            numeric_matrix_dynamic_t M5 = vt::move((A11 + A12) * B22);
            numeric_matrix_dynamic_t M6 = vt::move((A21 - A11) * (B11 + B12));
            numeric_matrix_dynamic_t M7 = vt::move((A12 - A22) * (B21 + B22));
            C.insert(0, 0, M1 + M4 - M5 + M7);
            C.insert(0, C.c_ / 2, M3 + M5);
            C.insert(C.r_ / 2, 0, M2 + M4);
            C.insert(C.r_ / 2, C.c_ / 2, M1 - M2 + M3 + M6);
            if (rA != A.r_ || cB != B.c_)
                C = C.slice(0, 0, A.r_, B.c_);
            return C;
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::closest_2(), vt::numeric_matrix_dynamic_t< T >::insert(), vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t(), vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_t< T >::slice().
Referenced by vt::numeric_matrix_dynamic_t< T >::imatmul().
fix_zero()
template<typename T > void vt::numeric_matrix_dynamic_t< T >::fix_zero () inline private
Definition at line 519 of file dynamic_numeric_matrix.h.
{
            for (size_t i = 0; i < r_; ++i)
                for (size_t j = 0; j < c_; ++j)
                    if (vector_[i][j] == 0.0)
                        vector_[i][j] = 0.0;
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_t< T >::vector_.
Referenced by vt::numeric_matrix_dynamic_t< T >::RRE().
put_array() [1/4]
template<typename T > void vt::numeric_matrix_dynamic_t< T >::put_array (size_t index, const numeric_vector_dynamic_t< T > & vector) inline private
Definition at line 526 of file dynamic_numeric_matrix.h.
{
            vector_[index] = vector;
            c_ = vector.size();
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_vector_dynamic_t< T >::size(), and vt::numeric_matrix_dynamic_t< T >::vector_.
Referenced by vt::numeric_matrix_dynamic_t< T >::from(), vt::numeric_matrix_dynamic_t< T >::from(), vt::numeric_matrix_dynamic_t< T >::put_array(), and vt::numeric_matrix_dynamic_t< T >::put_array().
put_array() [2/4]
template<typename T > template<size_t N> void vt::numeric_matrix_dynamic_t< T >::put_array (size_t index, const T(&) array[N]) inline private
Definition at line 532 of file dynamic_numeric_matrix.h.
{
            vector_[index] = array;
            c_ = N;
        }
References vt::numeric_matrix_dynamic_t< T >::c_, and vt::numeric_matrix_dynamic_t< T >::vector_.
put_array() [3/4]
template<typename T > template<typename... Vectors> void vt::numeric_matrix_dynamic_t< T >::put_array (size_t index, const numeric_vector_dynamic_t< T > & vector, const Vectors &... vectors) inline private
Definition at line 538 of file dynamic_numeric_matrix.h.
{
            vector_[index] = vector;
            put_array(index + 1, vectors...);
        }
References vt::numeric_matrix_dynamic_t< T >::put_array(), and vt::numeric_matrix_dynamic_t< T >::vector_.
put_array() [4/4]
template<typename T > template<size_t N, typename... Arrays> void vt::numeric_matrix_dynamic_t< T >::put_array (size_t index, const T(&) array[N], const Arrays(&...arrays)[N]) inline private
Definition at line 544 of file dynamic_numeric_matrix.h.
{
            vector_[index] = array;
            put_array(index + 1, arrays...);
        }
References vt::numeric_matrix_dynamic_t< T >::put_array(), and vt::numeric_matrix_dynamic_t< T >::vector_.
allocate_zero()
template<typename T > void vt::numeric_matrix_dynamic_t< T >::allocate_zero () inline private
Definition at line 549 of file dynamic_numeric_matrix.h.
{ vector_ = vt::move(numeric_vector_dynamic_t<numeric_vector_dynamic_t<T>>(r_, numeric_vector_dynamic_t<T>(c_))); }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_t< T >::vector_.
Referenced by vt::numeric_matrix_dynamic_t< T >::allocate_from(), vt::numeric_matrix_dynamic_t< T >::allocate_from(), vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t(), vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t(), and vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t().
allocate_fill()
template<typename T > void vt::numeric_matrix_dynamic_t< T >::allocate_fill (T fill) inline private
Definition at line 551 of file dynamic_numeric_matrix.h.
{ vector_ = vt::move(numeric_vector_dynamic_t<numeric_vector_dynamic_t<T>>(r_, numeric_vector_dynamic_t<T>(c_, fill))); }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::fill(), vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_t< T >::vector_.
Referenced by vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t().
steal()
template<typename T > void vt::numeric_matrix_dynamic_t< T >::steal (numeric_matrix_dynamic_t< T > && other) inline private
Definition at line 553 of file dynamic_numeric_matrix.h.
{
            r_ = other.r_;
            c_ = other.c_;
            vector_ = vt::move(other.vector_);
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_t< T >::vector_.
Referenced by vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t(), vt::numeric_matrix_dynamic_t< T >::operator*=(), vt::numeric_matrix_dynamic_t< T >::operator=(), and vt::numeric_matrix_dynamic_t< T >::operator^=().
allocate_from() [1/3]
template<typename T > void vt::numeric_matrix_dynamic_t< T >::allocate_from (const numeric_matrix_dynamic_t< T > & other) inline private
Definition at line 559 of file dynamic_numeric_matrix.h.
{
            r_ = other.r_;
            c_ = other.c_;
            vector_ = other.vector_;
        }
References vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_t< T >::vector_.
Referenced by vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t(), vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t(), vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t(), vt::numeric_matrix_dynamic_t< T >::operator=(), vt::numeric_matrix_dynamic_t< T >::operator=(), and vt::numeric_matrix_dynamic_t< T >::operator=().
allocate_from() [2/3]
template<typename T > template<size_t R, size_t C> void vt::numeric_matrix_dynamic_t< T >::allocate_from (const T(&) array[R][C]) inline private
Definition at line 566 of file dynamic_numeric_matrix.h.
{
            r_ = R;
            c_ = C;
            allocate_zero();
            for (size_t i = 0; i < r_; ++i)
                for (size_t j = 0; j < c_; ++j)
                    vector_[i][j] = array[i][j];
        }
References vt::numeric_matrix_dynamic_t< T >::allocate_zero(), vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_t< T >::vector_.
allocate_from() [3/3]
template<typename T > template<size_t R> void vt::numeric_matrix_dynamic_t< T >::allocate_from (const numeric_vector_dynamic_t< T >(&) vectors[R]) inline private
Definition at line 576 of file dynamic_numeric_matrix.h.
{
            r_ = R;
            c_ = vectors[0].size_;
            allocate_zero();
            for (size_t i = 0; i < r_; ++i)
                for (size_t j = 0; j < c_; ++j)
                    vector_[i][j] = vectors[i][j];
        }
References vt::numeric_matrix_dynamic_t< T >::allocate_zero(), vt::numeric_matrix_dynamic_t< T >::c_, vt::numeric_matrix_dynamic_t< T >::r_, and vt::numeric_matrix_dynamic_t< T >::vector_.
zeros() [1/2]
template<typename T > static numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::zeros (size_t r, size_t c) inline static
Definition at line 588 of file dynamic_numeric_matrix.h.
{ return numeric_matrix_dynamic_t(r, c); }
References vt::numeric_matrix_dynamic_t< T >::c(), vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t(), and vt::numeric_matrix_dynamic_t< T >::r().
zeros() [2/2]
template<typename T > static numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::zeros (size_t n) inline static
Definition at line 590 of file dynamic_numeric_matrix.h.
{ return numeric_matrix_dynamic_t(n); }
References vt::numeric_matrix_dynamic_t< T >::n(), and vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t().
ones() [1/2]
template<typename T > static numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::ones (size_t r, size_t c) inline static
Definition at line 592 of file dynamic_numeric_matrix.h.
{ return numeric_matrix_dynamic_t(r, c, 1); }
References vt::numeric_matrix_dynamic_t< T >::c(), vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t(), and vt::numeric_matrix_dynamic_t< T >::r().
ones() [2/2]
template<typename T > static numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::ones (size_t n) inline static
Definition at line 594 of file dynamic_numeric_matrix.h.
{ return numeric_matrix_dynamic_t(n, n, 1); }
References vt::numeric_matrix_dynamic_t< T >::n(), and vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t().
identity()
template<typename T > static numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::identity (size_t n) inline static
Definition at line 596 of file dynamic_numeric_matrix.h.
{ return diagonal(n, 1); }
References vt::numeric_matrix_dynamic_t< T >::diagonal(), and vt::numeric_matrix_dynamic_t< T >::n().
Referenced by vt::numeric_matrix_dynamic_t< T >::id().
id()
template<typename T > static numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::id (size_t n) inline static
Definition at line 598 of file dynamic_numeric_matrix.h.
{ return identity(n); }
References vt::numeric_matrix_dynamic_t< T >::identity(), and vt::numeric_matrix_dynamic_t< T >::n().
Referenced by vt::numeric_matrix_dynamic_t< T >::operator^().
diagonal()
template<typename T > static numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::diagonal (size_t n, T value) inline static
Definition at line 600 of file dynamic_numeric_matrix.h.
{
            numeric_matrix_dynamic_t tmp(n);
            for (size_t i = 0; i < n; ++i) tmp[i][i] = value;
            return tmp;
        }
References vt::numeric_matrix_dynamic_t< T >::n().
Referenced by vt::numeric_matrix_dynamic_t< T >::identity().
from() [1/2]
template<typename T > template<typename... Vectors> static numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::from (const Vectors &... vectors) inline static
Definition at line 607 of file dynamic_numeric_matrix.h.
{
            numeric_matrix_dynamic_t tmp(sizeof...(vectors), 0);
            tmp.put_array(0, vectors...);
            return tmp;
        }
References vt::numeric_matrix_dynamic_t< T >::put_array().
Referenced by vt::numeric_matrix_dynamic_t< T >::from_row().
from() [2/2]
template<typename T > template<size_t N, typename... Arrays> static numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::from (const Arrays(&...arrays)[N]) inline static
Definition at line 614 of file dynamic_numeric_matrix.h.
{
            numeric_matrix_dynamic_t tmp(N, 0);
            tmp.put_array(0, arrays...);
            return tmp;
        }
References vt::numeric_matrix_dynamic_t< T >::put_array().
from_row()
template<typename T > static numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::from_row (const numeric_vector_dynamic_t< T > & vector) inline static
Definition at line 620 of file dynamic_numeric_matrix.h.
{ return numeric_matrix_dynamic_t::from(vector); }
References vt::numeric_matrix_dynamic_t< T >::from().
from_col()
template<typename T > static numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::from_col (const numeric_vector_dynamic_t< T > & vector) inline static
Definition at line 622 of file dynamic_numeric_matrix.h.
{
            numeric_matrix_dynamic_t result(vector.size_, 1);
            for (size_t i = 0; i < vector.size_; ++i) result[i][0] = vector.arr_[i];
            return result;
        }
References vt::numeric_vector_dynamic_t< T >::arr_, and vt::numeric_vector_dynamic_t< T >::size_.
quad()
template<typename T > static numeric_matrix_dynamic_t vt::numeric_matrix_dynamic_t< T >::quad (const numeric_matrix_dynamic_t< T > M) inline static
Definition at line 628 of file dynamic_numeric_matrix.h.
{ return numeric_matrix_dynamic_t(M, M, M, M); }
References vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t().
Friends And Related Symbol Documentation
numeric_vector_dynamic_t< T >
template<typename T > friend class numeric_vector_dynamic_t< T > friend
Definition at line 648 of file dynamic_numeric_matrix.h.
Referenced by vt::numeric_matrix_dynamic_t< T >::row().
Member Data Documentation
STRASSENDIMENSION
template<typename T > constexpr size_t vt::numeric_matrix_dynamic_t< T >::STRASSENDIMENSION = 1024 static constexpr private
Definition at line 26 of file dynamic_numeric_matrix.h.
STRASSENTHRESHOLD
template<typename T > constexpr size_t vt::numeric_matrix_dynamic_t< T >::STRASSENTHRESHOLD = STRASSENDIMENSION * STRASSENDIMENSION static constexpr private
Definition at line 27 of file dynamic_numeric_matrix.h.
Referenced by vt::numeric_matrix_dynamic_t< T >::imatmul().
r_
template<typename T > size_t vt::numeric_matrix_dynamic_t< T >::r_ private
Definition at line 28 of file dynamic_numeric_matrix.h.
Referenced by vt::numeric_matrix_dynamic_t< T >::allocate_fill(), vt::numeric_matrix_dynamic_t< T >::allocate_from(), vt::numeric_matrix_dynamic_t< T >::allocate_from(), vt::numeric_matrix_dynamic_t< T >::allocate_from(), vt::numeric_matrix_dynamic_t< T >::allocate_zero(), vt::numeric_matrix_dynamic_t< T >::caNmultiply_with(), vt::numeric_matrix_dynamic_t< T >::col(), vt::numeric_matrix_dynamic_t< T >::det(), vt::numeric_matrix_dynamic_t< T >::diag(), vt::numeric_matrix_dynamic_t< T >::fix_zero(), vt::numeric_matrix_dynamic_t< T >::float_equals(), vt::numeric_matrix_dynamic_t< T >::iadd(), vt::numeric_matrix_dynamic_t< T >::insert(), vt::numeric_matrix_dynamic_t< T >::insert(), vt::numeric_matrix_dynamic_t< T >::inv_lt(), vt::numeric_matrix_dynamic_t< T >::is_square(), vt::numeric_matrix_dynamic_t< T >::isub(), vt::numeric_matrix_dynamic_t< T >::LU(), vt::numeric_matrix_dynamic_t< T >::matmul_naive(), vt::numeric_matrix_dynamic_t< T >::matpow_naive(), vt::numeric_matrix_dynamic_t< T >::mm_naive(), vt::numeric_matrix_dynamic_t< T >::mm_strassen(), vt::numeric_matrix_dynamic_t< T >::n(), vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t(), vt::numeric_matrix_dynamic_t< T >::operator*(), vt::numeric_matrix_dynamic_t< T >::operator*(), vt::numeric_matrix_dynamic_t< T >::operator=(), vt::numeric_matrix_dynamic_t< T >::operator=(), vt::numeric_matrix_dynamic_t< T >::operator==(), vt::numeric_matrix_dynamic_t< T >::operator==(), vt::numeric_matrix_dynamic_t< T >::operator^(), vt::numeric_matrix_dynamic_t< T >::r(), vt::numeric_matrix_dynamic_t< T >::RRE(), vt::numeric_matrix_dynamic_t< T >::slice(), vt::numeric_matrix_dynamic_t< T >::steal(), vt::numeric_matrix_dynamic_t< T >::swap(), vt::numeric_matrix_dynamic_t< T >::tr(), and vt::numeric_matrix_dynamic_t< T >::transpose().
c_
template<typename T > size_t vt::numeric_matrix_dynamic_t< T >::c_ private
Definition at line 29 of file dynamic_numeric_matrix.h.
Referenced by vt::numeric_matrix_dynamic_t< T >::allocate_fill(), vt::numeric_matrix_dynamic_t< T >::allocate_from(), vt::numeric_matrix_dynamic_t< T >::allocate_from(), vt::numeric_matrix_dynamic_t< T >::allocate_from(), vt::numeric_matrix_dynamic_t< T >::allocate_zero(), vt::numeric_matrix_dynamic_t< T >::c(), vt::numeric_matrix_dynamic_t< T >::caNmultiply_with(), vt::numeric_matrix_dynamic_t< T >::caNmultiply_with(), vt::numeric_matrix_dynamic_t< T >::det(), vt::numeric_matrix_dynamic_t< T >::diag(), vt::numeric_matrix_dynamic_t< T >::fix_zero(), vt::numeric_matrix_dynamic_t< T >::float_equals(), vt::numeric_matrix_dynamic_t< T >::iadd(), vt::numeric_matrix_dynamic_t< T >::insert(), vt::numeric_matrix_dynamic_t< T >::insert(), vt::numeric_matrix_dynamic_t< T >::inv_lt(), vt::numeric_matrix_dynamic_t< T >::is_square(), vt::numeric_matrix_dynamic_t< T >::isub(), vt::numeric_matrix_dynamic_t< T >::LU(), vt::numeric_matrix_dynamic_t< T >::matmul_naive(), vt::numeric_matrix_dynamic_t< T >::mm_naive(), vt::numeric_matrix_dynamic_t< T >::mm_strassen(), vt::numeric_matrix_dynamic_t< T >::n(), vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t(), vt::numeric_matrix_dynamic_t< T >::operator*(), vt::numeric_matrix_dynamic_t< T >::operator=(), vt::numeric_matrix_dynamic_t< T >::operator=(), vt::numeric_matrix_dynamic_t< T >::operator==(), vt::numeric_matrix_dynamic_t< T >::operator==(), vt::numeric_matrix_dynamic_t< T >::operator^(), vt::numeric_matrix_dynamic_t< T >::put_array(), vt::numeric_matrix_dynamic_t< T >::put_array(), vt::numeric_matrix_dynamic_t< T >::RRE(), vt::numeric_matrix_dynamic_t< T >::slice(), vt::numeric_matrix_dynamic_t< T >::steal(), vt::numeric_matrix_dynamic_t< T >::swap(), vt::numeric_matrix_dynamic_t< T >::tr(), and vt::numeric_matrix_dynamic_t< T >::transpose().
vector_
template<typename T > numeric_vector_dynamic_t<numeric_vector_dynamic_t<T> > vt::numeric_matrix_dynamic_t< T >::vector_ private
Definition at line 30 of file dynamic_numeric_matrix.h.
Referenced by vt::numeric_matrix_dynamic_t< T >::allocate_fill(), vt::numeric_matrix_dynamic_t< T >::allocate_from(), vt::numeric_matrix_dynamic_t< T >::allocate_from(), vt::numeric_matrix_dynamic_t< T >::allocate_from(), vt::numeric_matrix_dynamic_t< T >::allocate_zero(), vt::numeric_matrix_dynamic_t< T >::at(), vt::numeric_matrix_dynamic_t< T >::at(), vt::numeric_matrix_dynamic_t< T >::begin(), vt::numeric_matrix_dynamic_t< T >::begin(), vt::numeric_matrix_dynamic_t< T >::col(), vt::numeric_matrix_dynamic_t< T >::diag(), vt::numeric_matrix_dynamic_t< T >::end(), vt::numeric_matrix_dynamic_t< T >::end(), vt::numeric_matrix_dynamic_t< T >::fix_zero(), vt::numeric_matrix_dynamic_t< T >::float_equals(), vt::numeric_matrix_dynamic_t< T >::insert(), vt::numeric_matrix_dynamic_t< T >::insert(), vt::numeric_matrix_dynamic_t< T >::LU(), vt::numeric_matrix_dynamic_t< T >::operator*(), vt::numeric_matrix_dynamic_t< T >::operator*=(), vt::numeric_matrix_dynamic_t< T >::operator==(), vt::numeric_matrix_dynamic_t< T >::operator==(), vt::numeric_matrix_dynamic_t< T >::operator[](), vt::numeric_matrix_dynamic_t< T >::operator[](), vt::numeric_matrix_dynamic_t< T >::put_array(), vt::numeric_matrix_dynamic_t< T >::put_array(), vt::numeric_matrix_dynamic_t< T >::put_array(), vt::numeric_matrix_dynamic_t< T >::put_array(), vt::numeric_matrix_dynamic_t< T >::slice(), vt::numeric_matrix_dynamic_t< T >::steal(), vt::numeric_matrix_dynamic_t< T >::swap(), vt::numeric_matrix_dynamic_t< T >::tr(), and vt::numeric_matrix_dynamic_t< T >::transpose().
The documentation for this class was generated from the following file:
include/dynamic_numeric_matrix.h