VT Linear Algebra Library: vt::initializer_list< T > Class Template Reference
vt::initializer_list< T > Class Template Reference
#include <initializer_list.h>
Public Member Functions
initializer_list ()
template<size_t N>
initializer_list (const T(&array)[N])
size_t size () const
const T * begin () const
const T * end () const
Private Member Functions
initializer_list (const T *array, size_t size)
Private Attributes
const T * arr_
size_t size_
Detailed Description
template<typename T>
class vt::initializer_list< T >
Mimic std::initializer_list entirely. When std::initializer_list is not available, you can use this class by putting "CUSTOM_INITIALIZER_LIST" in your code.
Template Parameters
T
Definition at line 15 of file initializer_list.h.
Constructor & Destructor Documentation
initializer_list() [1/3]
template<typename T > vt::initializer_list< T >::initializer_list (const T * array, size_t size) inline private
Definition at line 20 of file initializer_list.h.
: arr_{array}, size_{size} {}
initializer_list() [2/3]
template<typename T > vt::initializer_list< T >::initializer_list () inline
Definition at line 23 of file initializer_list.h.
: arr_(nullptr), size_(0) {}
initializer_list() [3/3]
template<typename T > template<size_t N> vt::initializer_list< T >::initializer_list (const T(&) array[N]) inline explicit
Definition at line 26 of file initializer_list.h.
: arr_(array), size_(N) {}
Member Function Documentation
size()
template<typename T > size_t vt::initializer_list< T >::size () const inline
Definition at line 28 of file initializer_list.h.
{ return size_; }
References vt::initializer_list< T >::size_.
Referenced by vt::initializer_list< T >::end().
begin()
template<typename T > const T * vt::initializer_list< T >::begin () const inline
Definition at line 30 of file initializer_list.h.
{ return arr_; }
References vt::initializer_list< T >::arr_.
Referenced by vt::initializer_list< T >::end().
end()
template<typename T > const T * vt::initializer_list< T >::end () const inline
Definition at line 32 of file initializer_list.h.
{ return begin() + size(); }
References vt::initializer_list< T >::begin(), and vt::initializer_list< T >::size().
Member Data Documentation
arr_
template<typename T > const T* vt::initializer_list< T >::arr_ private
Definition at line 17 of file initializer_list.h.
Referenced by vt::initializer_list< T >::begin().
size_
template<typename T > size_t vt::initializer_list< T >::size_ private
Definition at line 18 of file initializer_list.h.
Referenced by vt::initializer_list< T >::size().
The documentation for this class was generated from the following file:
include/initializer_list.h