VT Linear Algebra Library: vt::numeric_vector_dynamic_t< T > Class Template Reference
vt::numeric_vector_dynamic_t< T > Class Template Reference
#include <dynamic_numeric_vector.h>
Public Member Functions
numeric_vector_dynamic_t ()
numeric_vector_dynamic_t (size_t size)
numeric_vector_dynamic_t (size_t size, T fill)
numeric_vector_dynamic_t (const numeric_vector_dynamic_t &other)
numeric_vector_dynamic_t (numeric_vector_dynamic_t &&other) noexcept
template<size_t N>
numeric_vector_dynamic_t (const T(&array)[N])
numeric_vector_dynamic_t (const iterator< T > &begin, const iterator< T > &end)
numeric_vector_dynamic_t (T *begin, T *end)
~numeric_vector_dynamic_t ()
T & operator[] (size_t index)
const T & operator[] (size_t index) const
T & at (size_t index)
const T & at (size_t index) const
T & operator() (size_t index)
const T & operator() (size_t index) const
numeric_vector_dynamic_t & operator= (const numeric_vector_dynamic_t &other)
numeric_vector_dynamic_t & operator= (numeric_vector_dynamic_t &&other) noexcept
template<size_t N>
numeric_vector_dynamic_t & operator= (const T(&array)[N])
numeric_vector_dynamic_t & operator+= (const numeric_vector_dynamic_t &other)
template<size_t N>
numeric_vector_dynamic_t & operator+= (const T(&array)[N])
numeric_vector_dynamic_t operator+ (const numeric_vector_dynamic_t &other) const
template<size_t N>
numeric_vector_dynamic_t operator+ (const T(&array)[N]) const
numeric_vector_dynamic_t add (const numeric_vector_dynamic_t &other) const
template<size_t N>
numeric_vector_dynamic_t add (const T(&array)[N]) const
numeric_vector_dynamic_t & operator-= (const numeric_vector_dynamic_t &other)
template<size_t N>
numeric_vector_dynamic_t & operator-= (const T(&array)[N])
numeric_vector_dynamic_t operator- (const numeric_vector_dynamic_t &other) const
template<size_t N>
numeric_vector_dynamic_t operator- (const T(&array)[N]) const
numeric_vector_dynamic_t subtract (const numeric_vector_dynamic_t &other) const
template<size_t N>
numeric_vector_dynamic_t subtract (const T(&array)[N]) const
numeric_vector_dynamic_t & operator*= (T rhs)
numeric_vector_dynamic_t operator* (T rhs) const
numeric_vector_dynamic_t & operator/= (T rhs)
numeric_vector_dynamic_t operator/ (T rhs) const
T dot (const numeric_vector_dynamic_t &other) const
template<size_t N>
T dot (const T(&array)[N]) const
constexpr T inner (const numeric_vector_dynamic_t &other) const
template<size_t N>
constexpr T inner (const T(&array)[N]) const
numeric_matrix_dynamic_t< T > outer (const numeric_vector_dynamic_t &other) const
template<size_t N>
numeric_matrix_dynamic_t< T > outer (const T(&array)[N]) const
T norm () const
numeric_vector_dynamic_t normalize () const
bool operator== (const numeric_vector_dynamic_t &other) const
template<size_t N>
bool operator== (const T(&array)[N]) const
bool operator!= (const numeric_vector_dynamic_t &other) const
template<size_t N>
bool operator!= (const T(&array)[N]) const
bool equals (const numeric_vector_dynamic_t &other) const
bool float_equals (const numeric_vector_dynamic_t &other) const
template<size_t N>
bool equals (const T(&array)[N]) const
void swap (numeric_vector_dynamic_t &other)
iterator< T > begin ()
iterator< T > begin () const
iterator< T > end ()
iterator< T > end () const
T & front ()
T & back ()
size_t size () const
Static Public Member Functions
static numeric_vector_dynamic_t zero (size_t n)
template<typename... Ts>
static numeric_vector_dynamic_t from (Ts... values)
Private Member Functions
void put_array (size_t index, T value)
template<typename... Ts>
void put_array (size_t index, T value, Ts ...values)
void allocate_zero ()
void allocate_fill (T fill)
void allocate_from (const numeric_vector_dynamic_t &other)
template<size_t N>
void allocate_from (const T(&array)[N])
void deallocate ()
Private Attributes
size_t size_
T * arr_
Friends
class numeric_matrix_dynamic_t< T >
Detailed Description
template<typename T>
class vt::numeric_vector_dynamic_t< T >
Definition at line 19 of file dynamic_numeric_vector.h.
Constructor & Destructor Documentation
numeric_vector_dynamic_t() [1/8]
template<typename T > vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t () inline
Definition at line 28 of file dynamic_numeric_vector.h.
: size_(0), arr_(nullptr) {}
Referenced by vt::numeric_vector_dynamic_t< T >::from(), vt::numeric_vector_dynamic_t< T >::normalize(), and vt::numeric_vector_dynamic_t< T >::zero().
numeric_vector_dynamic_t() [2/8]
template<typename T > vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t (size_t size) inline explicit
Definition at line 30 of file dynamic_numeric_vector.h.
: size_(size) { allocate_zero(); }
References vt::numeric_vector_dynamic_t< T >::allocate_zero().
numeric_vector_dynamic_t() [3/8]
template<typename T > vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t (size_t size, T fill) inline
Definition at line 32 of file dynamic_numeric_vector.h.
: size_(size) { allocate_fill(fill); }
References vt::numeric_vector_dynamic_t< T >::allocate_fill(), and vt::fill().
numeric_vector_dynamic_t() [4/8]
template<typename T > vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t (const numeric_vector_dynamic_t< T > & other) inline
Definition at line 34 of file dynamic_numeric_vector.h.
: size_(other.size_) { allocate_from(other); }
References vt::numeric_vector_dynamic_t< T >::allocate_from().
numeric_vector_dynamic_t() [5/8]
template<typename T > vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t (numeric_vector_dynamic_t< T > && other) inline noexcept
Definition at line 36 of file dynamic_numeric_vector.h.
                                                                           : size_(other.size_), arr_(other.arr_) {
            other.size_ = 0;
            other.arr_ = nullptr;
        }
numeric_vector_dynamic_t() [6/8]
template<typename T > template<size_t N> vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t (const T(&) array[N]) inline explicit
Definition at line 42 of file dynamic_numeric_vector.h.
: size_(N) { allocate_from(array); }
References vt::numeric_vector_dynamic_t< T >::allocate_from().
numeric_vector_dynamic_t() [7/8]
template<typename T > vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t (const iterator< T > & begin, const iterator< T > & end) inline
Definition at line 44 of file dynamic_numeric_vector.h.
                                                                                   : size_(end - begin) {
            arr_ = new T[size_];
            static_cast<void>(vt::copy(begin, end, arr_));
        }
References vt::numeric_vector_dynamic_t< T >::arr_, vt::numeric_vector_dynamic_t< T >::begin(), vt::copy(), vt::numeric_vector_dynamic_t< T >::end(), and vt::numeric_vector_dynamic_t< T >::size_.
numeric_vector_dynamic_t() [8/8]
template<typename T > vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t (T * begin, T * end) inline
Definition at line 49 of file dynamic_numeric_vector.h.
                                                   : size_(end - begin) {
            arr_ = new T[size_];
            static_cast<void>(vt::copy(begin, end, arr_));
        }
References vt::numeric_vector_dynamic_t< T >::arr_, vt::numeric_vector_dynamic_t< T >::begin(), vt::copy(), vt::numeric_vector_dynamic_t< T >::end(), and vt::numeric_vector_dynamic_t< T >::size_.
~numeric_vector_dynamic_t()
template<typename T > vt::numeric_vector_dynamic_t< T >::~numeric_vector_dynamic_t () inline
Definition at line 54 of file dynamic_numeric_vector.h.
{ deallocate(); }
References vt::numeric_vector_dynamic_t< T >::deallocate().
Member Function Documentation
operator[]() [1/2]
template<typename T > T & vt::numeric_vector_dynamic_t< T >::operator[] (size_t index) inline
Definition at line 56 of file dynamic_numeric_vector.h.
{ return *(arr_ + index); }
References vt::numeric_vector_dynamic_t< T >::arr_.
Referenced by vt::numeric_vector_dynamic_t< T >::at(), vt::numeric_vector_dynamic_t< T >::at(), vt::numeric_vector_dynamic_t< T >::back(), and vt::numeric_vector_dynamic_t< T >::front().
operator[]() [2/2]
template<typename T > const T & vt::numeric_vector_dynamic_t< T >::operator[] (size_t index) const inline
Definition at line 58 of file dynamic_numeric_vector.h.
{ return *(arr_ + index); }
References vt::numeric_vector_dynamic_t< T >::arr_.
at() [1/2]
template<typename T > T & vt::numeric_vector_dynamic_t< T >::at (size_t index) inline
Definition at line 60 of file dynamic_numeric_vector.h.
{ return operator[](index); };
References vt::numeric_vector_dynamic_t< T >::operator[]().
Referenced by vt::numeric_vector_dynamic_t< T >::operator()(), and vt::numeric_vector_dynamic_t< T >::operator()().
at() [2/2]
template<typename T > const T & vt::numeric_vector_dynamic_t< T >::at (size_t index) const inline
Definition at line 62 of file dynamic_numeric_vector.h.
{ return operator[](index); };
References vt::numeric_vector_dynamic_t< T >::operator[]().
operator()() [1/2]
template<typename T > T & vt::numeric_vector_dynamic_t< T >::operator() (size_t index) inline
Definition at line 64 of file dynamic_numeric_vector.h.
{ return at(index); }
References vt::numeric_vector_dynamic_t< T >::at().
operator()() [2/2]
template<typename T > const T & vt::numeric_vector_dynamic_t< T >::operator() (size_t index) const inline
Definition at line 66 of file dynamic_numeric_vector.h.
{ return at(index); }
References vt::numeric_vector_dynamic_t< T >::at().
operator=() [1/3]
template<typename T > numeric_vector_dynamic_t & vt::numeric_vector_dynamic_t< T >::operator= (const numeric_vector_dynamic_t< T > & other) inline
Definition at line 68 of file dynamic_numeric_vector.h.
{
            if (this != &other) {
                deallocate();
                allocate_from(other);
            }
            return *this;
        }
References vt::numeric_vector_dynamic_t< T >::allocate_from(), and vt::numeric_vector_dynamic_t< T >::deallocate().
operator=() [2/3]
template<typename T > numeric_vector_dynamic_t & vt::numeric_vector_dynamic_t< T >::operator= (numeric_vector_dynamic_t< T > && other) inline noexcept
Definition at line 76 of file dynamic_numeric_vector.h.
{
            if (this != &other) {
                deallocate();
                size_ = other.size_;
                arr_ = other.arr_;
                other.size_ = 0;
                other.arr_ = nullptr;
            }
            return *this;
        }
References vt::numeric_vector_dynamic_t< T >::arr_, vt::numeric_vector_dynamic_t< T >::deallocate(), and vt::numeric_vector_dynamic_t< T >::size_.
operator=() [3/3]
template<typename T > template<size_t N> numeric_vector_dynamic_t & vt::numeric_vector_dynamic_t< T >::operator= (const T(&) array[N]) inline
Definition at line 88 of file dynamic_numeric_vector.h.
{
            deallocate();
            allocate_from(array);
            return *this;
        }
References vt::numeric_vector_dynamic_t< T >::allocate_from(), and vt::numeric_vector_dynamic_t< T >::deallocate().
operator+=() [1/2]
template<typename T > numeric_vector_dynamic_t & vt::numeric_vector_dynamic_t< T >::operator+= (const numeric_vector_dynamic_t< T > & other) inline
Definition at line 94 of file dynamic_numeric_vector.h.
{
            for (size_t i = 0; i < size_; ++i) arr_[i] += other.arr_[i];
            return *this;
        }
References vt::numeric_vector_dynamic_t< T >::arr_, and vt::numeric_vector_dynamic_t< T >::size_.
operator+=() [2/2]
template<typename T > template<size_t N> numeric_vector_dynamic_t & vt::numeric_vector_dynamic_t< T >::operator+= (const T(&) array[N]) inline
Definition at line 100 of file dynamic_numeric_vector.h.
{
            for (size_t i = 0; i < size_; ++i) arr_[i] += array[i];
            return *this;
        }
References vt::numeric_vector_dynamic_t< T >::arr_, and vt::numeric_vector_dynamic_t< T >::size_.
operator+() [1/2]
template<typename T > numeric_vector_dynamic_t vt::numeric_vector_dynamic_t< T >::operator+ (const numeric_vector_dynamic_t< T > & other) const inline
Definition at line 105 of file dynamic_numeric_vector.h.
{
            numeric_vector_dynamic_t tmp(*this);
            tmp.operator+=(other);
            return tmp;
        }
Referenced by vt::numeric_vector_dynamic_t< T >::add(), and vt::numeric_vector_dynamic_t< T >::add().
operator+() [2/2]
template<typename T > template<size_t N> numeric_vector_dynamic_t vt::numeric_vector_dynamic_t< T >::operator+ (const T(&) array[N]) const inline
Definition at line 112 of file dynamic_numeric_vector.h.
{
            numeric_vector_dynamic_t tmp(*this);
            tmp.operator+=(array);
            return tmp;
        }
add() [1/2]
template<typename T > numeric_vector_dynamic_t vt::numeric_vector_dynamic_t< T >::add (const numeric_vector_dynamic_t< T > & other) const inline
Definition at line 118 of file dynamic_numeric_vector.h.
{ return operator+(other); }
References vt::numeric_vector_dynamic_t< T >::operator+().
add() [2/2]
template<typename T > template<size_t N> numeric_vector_dynamic_t vt::numeric_vector_dynamic_t< T >::add (const T(&) array[N]) const inline
Definition at line 121 of file dynamic_numeric_vector.h.
{ return operator+(array); }
References vt::numeric_vector_dynamic_t< T >::operator+().
operator-=() [1/2]
template<typename T > numeric_vector_dynamic_t & vt::numeric_vector_dynamic_t< T >::operator-= (const numeric_vector_dynamic_t< T > & other) inline
Definition at line 123 of file dynamic_numeric_vector.h.
{
            for (size_t i = 0; i < size_; ++i) arr_[i] -= other.arr_[i];
            return *this;
        }
References vt::numeric_vector_dynamic_t< T >::arr_, and vt::numeric_vector_dynamic_t< T >::size_.
operator-=() [2/2]
template<typename T > template<size_t N> numeric_vector_dynamic_t & vt::numeric_vector_dynamic_t< T >::operator-= (const T(&) array[N]) inline
Definition at line 129 of file dynamic_numeric_vector.h.
{
            for (size_t i = 0; i < size_; ++i) arr_[i] -= array[i];
            return *this;
        }
References vt::numeric_vector_dynamic_t< T >::arr_, and vt::numeric_vector_dynamic_t< T >::size_.
operator-() [1/2]
template<typename T > numeric_vector_dynamic_t vt::numeric_vector_dynamic_t< T >::operator- (const numeric_vector_dynamic_t< T > & other) const inline
Definition at line 134 of file dynamic_numeric_vector.h.
{
            numeric_vector_dynamic_t tmp(*this);
            tmp.operator-=(other);
            return tmp;
        }
Referenced by vt::numeric_vector_dynamic_t< T >::subtract(), and vt::numeric_vector_dynamic_t< T >::subtract().
operator-() [2/2]
template<typename T > template<size_t N> numeric_vector_dynamic_t vt::numeric_vector_dynamic_t< T >::operator- (const T(&) array[N]) const inline
Definition at line 141 of file dynamic_numeric_vector.h.
{
            numeric_vector_dynamic_t tmp(*this);
            tmp.operator-=(array);
            return tmp;
        }
subtract() [1/2]
template<typename T > numeric_vector_dynamic_t vt::numeric_vector_dynamic_t< T >::subtract (const numeric_vector_dynamic_t< T > & other) const inline
Definition at line 147 of file dynamic_numeric_vector.h.
{ return operator-(other); }
References vt::numeric_vector_dynamic_t< T >::operator-().
subtract() [2/2]
template<typename T > template<size_t N> numeric_vector_dynamic_t vt::numeric_vector_dynamic_t< T >::subtract (const T(&) array[N]) const inline
Definition at line 150 of file dynamic_numeric_vector.h.
{ return operator-(array); }
References vt::numeric_vector_dynamic_t< T >::operator-().
operator*=()
template<typename T > numeric_vector_dynamic_t & vt::numeric_vector_dynamic_t< T >::operator*= (T rhs) inline
Definition at line 152 of file dynamic_numeric_vector.h.
{
            for (size_t i = 0; i < size_; ++i) arr_[i] *= rhs;
            return *this;
        }
References vt::numeric_vector_dynamic_t< T >::arr_, and vt::numeric_vector_dynamic_t< T >::size_.
operator*()
template<typename T > numeric_vector_dynamic_t vt::numeric_vector_dynamic_t< T >::operator* (T rhs) const inline
Definition at line 157 of file dynamic_numeric_vector.h.
{
            numeric_vector_dynamic_t tmp(*this);
            tmp.operator*=(rhs);
            return tmp;
        }
operator/=()
template<typename T > numeric_vector_dynamic_t & vt::numeric_vector_dynamic_t< T >::operator/= (T rhs) inline
Definition at line 163 of file dynamic_numeric_vector.h.
{
            for (size_t i = 0; i < size_; ++i) arr_[i] /= rhs;
            return *this;
        }
References vt::numeric_vector_dynamic_t< T >::arr_, and vt::numeric_vector_dynamic_t< T >::size_.
operator/()
template<typename T > numeric_vector_dynamic_t vt::numeric_vector_dynamic_t< T >::operator/ (T rhs) const inline
Definition at line 168 of file dynamic_numeric_vector.h.
{
            numeric_vector_dynamic_t tmp(*this);
            tmp.operator/=(rhs);
            return tmp;
        }
dot() [1/2]
template<typename T > T vt::numeric_vector_dynamic_t< T >::dot (const numeric_vector_dynamic_t< T > & other) const inline
Definition at line 174 of file dynamic_numeric_vector.h.
{
            T acc = 0;
            for (size_t i = 0; i < size_; ++i) acc += arr_[i] * other.arr_[i];
            return acc;
        }
References vt::numeric_vector_dynamic_t< T >::arr_, and vt::numeric_vector_dynamic_t< T >::size_.
Referenced by vt::numeric_vector_dynamic_t< T >::inner(), vt::numeric_vector_dynamic_t< T >::inner(), and vt::numeric_vector_dynamic_t< T >::norm().
dot() [2/2]
template<typename T > template<size_t N> T vt::numeric_vector_dynamic_t< T >::dot (const T(&) array[N]) const inline
Definition at line 181 of file dynamic_numeric_vector.h.
{
            T acc = 0;
            for (size_t i = 0; i < size_; ++i) acc += arr_[i] * array[i];
            return acc;
        }
References vt::numeric_vector_dynamic_t< T >::arr_, and vt::numeric_vector_dynamic_t< T >::size_.
inner() [1/2]
template<typename T > constexpr T vt::numeric_vector_dynamic_t< T >::inner (const numeric_vector_dynamic_t< T > & other) const inline constexpr
Definition at line 187 of file dynamic_numeric_vector.h.
{ return dot(other); }
References vt::numeric_vector_dynamic_t< T >::dot().
inner() [2/2]
template<typename T > template<size_t N> constexpr T vt::numeric_vector_dynamic_t< T >::inner (const T(&) array[N]) const inline constexpr
Definition at line 190 of file dynamic_numeric_vector.h.
{ return dot(array); }
References vt::numeric_vector_dynamic_t< T >::dot().
outer() [1/2]
template<typename T > numeric_matrix_dynamic_t< T > vt::numeric_vector_dynamic_t< T >::outer (const numeric_vector_dynamic_t< T > & other) const inline
Definition at line 192 of file dynamic_numeric_vector.h.
{
            numeric_matrix_dynamic_t<T> result(size_, other.size_);
            for (size_t i = 0; i < size_; ++i)
                for (size_t j = 0; j < other.size_; ++j)
                    result[i][j] = arr_[i] * other.arr_[j];
            return result;
        }
References vt::numeric_vector_dynamic_t< T >::arr_, and vt::numeric_vector_dynamic_t< T >::size_.
outer() [2/2]
template<typename T > template<size_t N> numeric_matrix_dynamic_t< T > vt::numeric_vector_dynamic_t< T >::outer (const T(&) array[N]) const inline
Definition at line 201 of file dynamic_numeric_vector.h.
{
            numeric_matrix_dynamic_t<T> result(size_, N);
            for (size_t i = 0; i < size_; ++i)
                for (size_t j = 0; j < N; ++j)
                    result[i][j] = arr_[i] * array[j];
            return result;
        }
References vt::numeric_vector_dynamic_t< T >::arr_, and vt::numeric_vector_dynamic_t< T >::size_.
norm()
template<typename T > T vt::numeric_vector_dynamic_t< T >::norm () const inline
Definition at line 209 of file dynamic_numeric_vector.h.
{ return pow(dot(*this), 0.5); }
References vt::numeric_vector_dynamic_t< T >::dot().
Referenced by vt::numeric_vector_dynamic_t< T >::normalize().
normalize()
template<typename T > numeric_vector_dynamic_t vt::numeric_vector_dynamic_t< T >::normalize () const inline
Definition at line 211 of file dynamic_numeric_vector.h.
{ return numeric_vector_dynamic_t(*this) / norm(); }
References vt::numeric_vector_dynamic_t< T >::norm(), and vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t().
operator==() [1/2]
template<typename T > bool vt::numeric_vector_dynamic_t< T >::operator== (const numeric_vector_dynamic_t< T > & other) const inline
Definition at line 213 of file dynamic_numeric_vector.h.
{
            if (this == &other) return true;
            if (size_ != other.size_) return false;
            for (size_t i = 0; i < size_; ++i) if (arr_[i] != other.arr_[i]) return false;
            return true;
        }
References vt::numeric_vector_dynamic_t< T >::arr_, and vt::numeric_vector_dynamic_t< T >::size_.
Referenced by vt::numeric_vector_dynamic_t< T >::equals(), vt::numeric_vector_dynamic_t< T >::equals(), vt::numeric_vector_dynamic_t< T >::operator!=(), and vt::numeric_vector_dynamic_t< T >::operator!=().
operator==() [2/2]
template<typename T > template<size_t N> bool vt::numeric_vector_dynamic_t< T >::operator== (const T(&) array[N]) const inline
Definition at line 221 of file dynamic_numeric_vector.h.
{
            if (size_ != N) return false;
            for (size_t i = 0; i < size_; ++i) if (arr_[i] != array[i]) return false;
            return true;
        }
References vt::numeric_vector_dynamic_t< T >::arr_, and vt::numeric_vector_dynamic_t< T >::size_.
operator!=() [1/2]
template<typename T > bool vt::numeric_vector_dynamic_t< T >::operator!= (const numeric_vector_dynamic_t< T > & other) const inline
Definition at line 227 of file dynamic_numeric_vector.h.
{ return !operator==(other); }
References vt::numeric_vector_dynamic_t< T >::operator==().
operator!=() [2/2]
template<typename T > template<size_t N> bool vt::numeric_vector_dynamic_t< T >::operator!= (const T(&) array[N]) const inline
Definition at line 230 of file dynamic_numeric_vector.h.
{ return !operator==(array); }
References vt::numeric_vector_dynamic_t< T >::operator==().
equals() [1/2]
template<typename T > bool vt::numeric_vector_dynamic_t< T >::equals (const numeric_vector_dynamic_t< T > & other) const inline
Definition at line 232 of file dynamic_numeric_vector.h.
{ return operator==(other); }
References vt::numeric_vector_dynamic_t< T >::operator==().
float_equals()
template<typename T > bool vt::numeric_vector_dynamic_t< T >::float_equals (const numeric_vector_dynamic_t< T > & other) const inline
Definition at line 234 of file dynamic_numeric_vector.h.
{
            if (this == &other) return true;
            if (size_ != other.size_) return false;
            for (size_t i = 0; i < size_; ++i) if (abs(arr_[i] - other.arr_[i]) > 0.001) return false;
            return true;
        }
References vt::numeric_vector_dynamic_t< T >::arr_, and vt::numeric_vector_dynamic_t< T >::size_.
equals() [2/2]
template<typename T > template<size_t N> bool vt::numeric_vector_dynamic_t< T >::equals (const T(&) array[N]) const inline
Definition at line 242 of file dynamic_numeric_vector.h.
{ return operator==(array); }
References vt::numeric_vector_dynamic_t< T >::operator==().
swap()
template<typename T > void vt::numeric_vector_dynamic_t< T >::swap (numeric_vector_dynamic_t< T > & other) inline
Definition at line 244 of file dynamic_numeric_vector.h.
{
            vt::swap(arr_, other.arr_);
            vt::swap(size_, other.size_);
        }
References vt::numeric_vector_dynamic_t< T >::arr_, vt::numeric_vector_dynamic_t< T >::size_, and vt::swap().
begin() [1/2]
template<typename T > iterator< T > vt::numeric_vector_dynamic_t< T >::begin () inline
Definition at line 249 of file dynamic_numeric_vector.h.
{ return iterator<T>(arr_); }
References vt::numeric_vector_dynamic_t< T >::arr_.
Referenced by vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t(), and vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t().
begin() [2/2]
template<typename T > iterator< T > vt::numeric_vector_dynamic_t< T >::begin () const inline
Definition at line 251 of file dynamic_numeric_vector.h.
{ return iterator<T>(arr_); }
References vt::numeric_vector_dynamic_t< T >::arr_.
end() [1/2]
template<typename T > iterator< T > vt::numeric_vector_dynamic_t< T >::end () inline
Definition at line 253 of file dynamic_numeric_vector.h.
{ return iterator<T>(arr_ + size_); }
References vt::numeric_vector_dynamic_t< T >::arr_, and vt::numeric_vector_dynamic_t< T >::size_.
Referenced by vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t(), and vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t().
end() [2/2]
template<typename T > iterator< T > vt::numeric_vector_dynamic_t< T >::end () const inline
Definition at line 255 of file dynamic_numeric_vector.h.
{ return iterator<T>(arr_ + size_); }
References vt::numeric_vector_dynamic_t< T >::arr_, and vt::numeric_vector_dynamic_t< T >::size_.
front()
template<typename T > T & vt::numeric_vector_dynamic_t< T >::front () inline
Definition at line 257 of file dynamic_numeric_vector.h.
{ return operator[](0); }
References vt::numeric_vector_dynamic_t< T >::operator[]().
back()
template<typename T > T & vt::numeric_vector_dynamic_t< T >::back () inline
Definition at line 259 of file dynamic_numeric_vector.h.
{ return operator[](size_ - 1); }
References vt::numeric_vector_dynamic_t< T >::operator[](), and vt::numeric_vector_dynamic_t< T >::size_.
size()
template<typename T > size_t vt::numeric_vector_dynamic_t< T >::size () const inline
Definition at line 261 of file dynamic_numeric_vector.h.
{ return size_; }
References vt::numeric_vector_dynamic_t< T >::size_.
Referenced by vt::numeric_matrix_dynamic_t< T >::put_array().
put_array() [1/2]
template<typename T > void vt::numeric_vector_dynamic_t< T >::put_array (size_t index, T value) inline private
Definition at line 264 of file dynamic_numeric_vector.h.
{ arr_[index] = value; }
References vt::numeric_vector_dynamic_t< T >::arr_.
Referenced by vt::numeric_vector_dynamic_t< T >::from(), and vt::numeric_vector_dynamic_t< T >::put_array().
put_array() [2/2]
template<typename T > template<typename... Ts> void vt::numeric_vector_dynamic_t< T >::put_array (size_t index, T value, Ts ... values) inline private
Definition at line 267 of file dynamic_numeric_vector.h.
{
            arr_[index] = value;
            put_array(index + 1, values...);
        }
References vt::numeric_vector_dynamic_t< T >::arr_, and vt::numeric_vector_dynamic_t< T >::put_array().
allocate_zero()
template<typename T > void vt::numeric_vector_dynamic_t< T >::allocate_zero () inline private
Definition at line 272 of file dynamic_numeric_vector.h.
{ arr_ = new T[size_](); }
References vt::numeric_vector_dynamic_t< T >::arr_, and vt::numeric_vector_dynamic_t< T >::size_.
Referenced by vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t().
allocate_fill()
template<typename T > void vt::numeric_vector_dynamic_t< T >::allocate_fill (T fill) inline private
Definition at line 274 of file dynamic_numeric_vector.h.
{
            arr_ = new T[size_];
            vt::fill(arr_, arr_ + size_, fill);
        }
References vt::numeric_vector_dynamic_t< T >::arr_, vt::fill(), and vt::numeric_vector_dynamic_t< T >::size_.
Referenced by vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t().
allocate_from() [1/2]
template<typename T > void vt::numeric_vector_dynamic_t< T >::allocate_from (const numeric_vector_dynamic_t< T > & other) inline private
Definition at line 279 of file dynamic_numeric_vector.h.
{
            size_ = other.size_;
            arr_ = new T[size_];
            static_cast<void>(vt::copy(other.arr_, other.arr_ + other.size_, arr_));
        }
References vt::numeric_vector_dynamic_t< T >::arr_, vt::copy(), and vt::numeric_vector_dynamic_t< T >::size_.
Referenced by vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t(), vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t(), vt::numeric_vector_dynamic_t< T >::operator=(), and vt::numeric_vector_dynamic_t< T >::operator=().
allocate_from() [2/2]
template<typename T > template<size_t N> void vt::numeric_vector_dynamic_t< T >::allocate_from (const T(&) array[N]) inline private
Definition at line 286 of file dynamic_numeric_vector.h.
{
            size_ = N;
            arr_ = new T[size_];
            static_cast<void>(vt::copy(array, array + N, arr_));
        }
References vt::numeric_vector_dynamic_t< T >::arr_, vt::copy(), and vt::numeric_vector_dynamic_t< T >::size_.
deallocate()
template<typename T > void vt::numeric_vector_dynamic_t< T >::deallocate () inline private
Definition at line 292 of file dynamic_numeric_vector.h.
{ delete[] arr_; }
References vt::numeric_vector_dynamic_t< T >::arr_.
Referenced by vt::numeric_vector_dynamic_t< T >::operator=(), vt::numeric_vector_dynamic_t< T >::operator=(), vt::numeric_vector_dynamic_t< T >::operator=(), and vt::numeric_vector_dynamic_t< T >::~numeric_vector_dynamic_t().
zero()
template<typename T > static numeric_vector_dynamic_t vt::numeric_vector_dynamic_t< T >::zero (size_t n) inline static
Definition at line 295 of file dynamic_numeric_vector.h.
{ return numeric_vector_dynamic_t(n); }
References vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t().
from()
template<typename T > template<typename... Ts> static numeric_vector_dynamic_t vt::numeric_vector_dynamic_t< T >::from (Ts... values) inline static
Definition at line 298 of file dynamic_numeric_vector.h.
{
            numeric_vector_dynamic_t tmp = numeric_vector_dynamic_t(sizeof...(values));
            tmp.put_array(0, values...);
            return tmp;
        }
References vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t(), and vt::numeric_vector_dynamic_t< T >::put_array().
Friends And Related Symbol Documentation
numeric_matrix_dynamic_t< T >
template<typename T > friend class numeric_matrix_dynamic_t< T > friend
Definition at line 320 of file dynamic_numeric_vector.h.
Member Data Documentation
size_
template<typename T > size_t vt::numeric_vector_dynamic_t< T >::size_ private
Definition at line 24 of file dynamic_numeric_vector.h.
Referenced by vt::numeric_vector_dynamic_t< T >::allocate_fill(), vt::numeric_vector_dynamic_t< T >::allocate_from(), vt::numeric_vector_dynamic_t< T >::allocate_from(), vt::numeric_vector_dynamic_t< T >::allocate_zero(), vt::numeric_vector_dynamic_t< T >::back(), vt::numeric_matrix_dynamic_t< T >::caNmultiply_with(), vt::numeric_vector_dynamic_t< T >::dot(), vt::numeric_vector_dynamic_t< T >::dot(), vt::numeric_vector_dynamic_t< T >::end(), vt::numeric_vector_dynamic_t< T >::end(), vt::numeric_vector_dynamic_t< T >::float_equals(), vt::numeric_matrix_dynamic_t< T >::from_col(), vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t(), vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t(), vt::numeric_vector_dynamic_t< T >::operator*=(), vt::numeric_vector_dynamic_t< T >::operator+=(), vt::numeric_vector_dynamic_t< T >::operator+=(), vt::numeric_vector_dynamic_t< T >::operator-=(), vt::numeric_vector_dynamic_t< T >::operator-=(), vt::numeric_vector_dynamic_t< T >::operator/=(), vt::numeric_vector_dynamic_t< T >::operator=(), vt::numeric_vector_dynamic_t< T >::operator==(), vt::numeric_vector_dynamic_t< T >::operator==(), vt::numeric_vector_dynamic_t< T >::outer(), vt::numeric_vector_dynamic_t< T >::outer(), vt::numeric_vector_dynamic_t< T >::size(), and vt::numeric_vector_dynamic_t< T >::swap().
arr_
template<typename T > T* vt::numeric_vector_dynamic_t< T >::arr_ private
Definition at line 25 of file dynamic_numeric_vector.h.
Referenced by vt::numeric_vector_dynamic_t< T >::allocate_fill(), vt::numeric_vector_dynamic_t< T >::allocate_from(), vt::numeric_vector_dynamic_t< T >::allocate_from(), vt::numeric_vector_dynamic_t< T >::allocate_zero(), vt::numeric_vector_dynamic_t< T >::begin(), vt::numeric_vector_dynamic_t< T >::begin(), vt::numeric_vector_dynamic_t< T >::deallocate(), vt::numeric_vector_dynamic_t< T >::dot(), vt::numeric_vector_dynamic_t< T >::dot(), vt::numeric_vector_dynamic_t< T >::end(), vt::numeric_vector_dynamic_t< T >::end(), vt::numeric_vector_dynamic_t< T >::float_equals(), vt::numeric_matrix_dynamic_t< T >::from_col(), vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t(), vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t(), vt::numeric_vector_dynamic_t< T >::operator*=(), vt::numeric_vector_dynamic_t< T >::operator+=(), vt::numeric_vector_dynamic_t< T >::operator+=(), vt::numeric_vector_dynamic_t< T >::operator-=(), vt::numeric_vector_dynamic_t< T >::operator-=(), vt::numeric_vector_dynamic_t< T >::operator/=(), vt::numeric_vector_dynamic_t< T >::operator=(), vt::numeric_vector_dynamic_t< T >::operator==(), vt::numeric_vector_dynamic_t< T >::operator==(), vt::numeric_vector_dynamic_t< T >::operator[](), vt::numeric_vector_dynamic_t< T >::operator[](), vt::numeric_vector_dynamic_t< T >::outer(), vt::numeric_vector_dynamic_t< T >::outer(), vt::numeric_vector_dynamic_t< T >::put_array(), vt::numeric_vector_dynamic_t< T >::put_array(), and vt::numeric_vector_dynamic_t< T >::swap().
The documentation for this class was generated from the following file:
include/dynamic_numeric_vector.h