VT Linear Algebra Library: vt::detail Namespace Reference
vt::detail Namespace Reference
Classes
struct always_false
struct input_assignment_chain
struct output_assignment_chain
struct size_sum
struct size_sum< Class< T, Size > >
struct size_sum< Class< T, Size >, Class< T, Sizes >... >
struct type_identity
Functions
template<typename T , size_t Size, size_t , size_t I>
void helper_assign_to (const T(&array)[Size], T &var)
template<typename T , size_t Size, size_t IMax, size_t I, typename... Ts>
void helper_assign_to (const T(&array)[Size], T &var, Ts &...vars)
template<typename T , size_t Size, size_t , size_t I>
void helper_assign_from (T(&array)[Size], const T &var)
template<typename T , size_t Size, size_t IMax, size_t I, typename... Ts>
void helper_assign_from (T(&array)[Size], const T &var, const Ts &...vars)
template<typename T , size_t Size>
constexpr numeric_vector_static_t< T, Size > make_numeric_vector_static_t ()
template<typename T , size_t Size>
constexpr numeric_vector_static_t< T, Size > make_numeric_vector_static_t (const T(&array)[Size])
template<typename T , size_t S1, size_t S2>
constexpr numeric_vector_static_t< T, S1+S2 > make_numeric_vector_static_t (const T(&a1)[S1], const T(&a2)[S2])
template<typename T , size_t S1, size_t S2, size_t... Ss>
constexpr numeric_vector_static_t< T, size_sum< numeric_vector_static_t< T, S1 >, numeric_vector_static_t< T, S2 >, numeric_vector_static_t< T, Ss >... >::value > make_numeric_vector_static_t (const T(&a1)[S1], const T(&a2)[S1], const T(&...as)[Ss])
template<typename T >
constexpr numeric_vector_static_t< T, 1 > make_numeric_vector_static_t (const T &val)
template<typename T , typename... Ts>
constexpr numeric_vector_static_t< T, 1+sizeof...(Ts)> make_numeric_vector_static_t (const T &val, const Ts &...vals)
template<typename T , size_t Row, size_t Col, size_t ... I>
constexpr numeric_vector_static_t< numeric_vector_static_t< T, Col >, Row > make_nested (const T(&array)[Row][Col], vt::index_sequence< I... >)
template<typename T , size_t Row, size_t Col>
constexpr numeric_vector_static_t< numeric_vector_static_t< T, Col >, Row > make_nested (const T(&array)[Row][Col])
template<typename T , size_t Order, size_t I, size_t ... J>
constexpr numeric_vector_static_t< T, Order > make_diagonal_minor (const T &value, vt::index_sequence< J... >)
template<typename T , size_t Order, size_t ... I>
constexpr numeric_vector_static_t< numeric_vector_static_t< T, Order >, Order > make_diagonal (const T(&array)[Order], vt::index_sequence< I... >)
template<typename T , size_t Order, size_t ... I>
constexpr numeric_vector_static_t< numeric_vector_static_t< T, Order >, Order > make_diagonal (const T(&array)[Order])
template<typename T >
auto try_add_lvalue_reference (int) -> type_identity< T & >
template<typename T >
auto try_add_lvalue_reference (...) -> type_identity< T >
template<typename T >
auto try_add_rvalue_reference (int) -> type_identity< T && >
template<typename T >
auto try_add_rvalue_reference (...) -> type_identity< T >
Detailed Description
Helper class for make_numeric_vector function. Not intended for user's usages.
Function Documentation
helper_assign_to() [1/2]
template<typename T , size_t Size, size_t , size_t I> void vt::detail::helper_assign_to (const T(&) array[Size], T & var)
Definition at line 17 of file numeric_vector.h.
{ var = array[I]; }
Referenced by vt::impl::numeric_vector_static_t< T, Size >::assign_to().
helper_assign_to() [2/2]
template<typename T , size_t Size, size_t IMax, size_t I, typename... Ts> void vt::detail::helper_assign_to (const T(&) array[Size], T & var, Ts &... vars)
Definition at line 20 of file numeric_vector.h.
{
            helper_assign_to<T, Size, IMax, I>(array, var);
            if (I < IMax) helper_assign_to<T, Size, IMax, I + 1>(array, vars...);
        }
helper_assign_from() [1/2]
template<typename T , size_t Size, size_t , size_t I> void vt::detail::helper_assign_from (T(&) array[Size], const T & var)
Definition at line 26 of file numeric_vector.h.
{ array[I] = var; }
Referenced by vt::impl::numeric_vector_static_t< T, Size >::assign_from().
helper_assign_from() [2/2]
template<typename T , size_t Size, size_t IMax, size_t I, typename... Ts> void vt::detail::helper_assign_from (T(&) array[Size], const T & var, const Ts &... vars)
Definition at line 29 of file numeric_vector.h.
{
            helper_assign_from<T, Size, IMax, I>(array, var);
            if (I < IMax) helper_assign_from<T, Size, IMax, I + 1>(array, vars...);
        }
make_numeric_vector_static_t() [1/6]
template<typename T , size_t Size> constexpr numeric_vector_static_t< T, Size > vt::detail::make_numeric_vector_static_t () constexpr
Definition at line 737 of file numeric_vector.h.
{
            return numeric_vector_static_t<T, Size>();
        }
Referenced by make_diagonal(), make_diagonal_minor(), make_nested(), make_numeric_vector_static_t(), and make_numeric_vector_static_t().
make_numeric_vector_static_t() [2/6]
template<typename T , size_t Size> constexpr numeric_vector_static_t< T, Size > vt::detail::make_numeric_vector_static_t (const T(&) array[Size]) constexpr
Definition at line 742 of file numeric_vector.h.
{
            return numeric_vector_static_t<T, Size>(array);
        }
make_numeric_vector_static_t() [3/6]
template<typename T , size_t S1, size_t S2> constexpr numeric_vector_static_t< T, S1+S2 > vt::detail::make_numeric_vector_static_t (const T(&) a1[S1], const T(&) a2[S2]) constexpr
Definition at line 748 of file numeric_vector.h.
{
            return numeric_vector_static_t<T, S1 + S2>(a1, a2);
        }
make_numeric_vector_static_t() [4/6]
template<typename T , size_t S1, size_t S2, size_t... Ss> constexpr numeric_vector_static_t< T, size_sum< numeric_vector_static_t< T, S1 >, numeric_vector_static_t< T, S2 >, numeric_vector_static_t< T, Ss >... >::value > vt::detail::make_numeric_vector_static_t (const T(&) a1[S1], const T(&) a2[S1], const T(&...as)[Ss]) constexpr
Definition at line 757 of file numeric_vector.h.
{
            return make_numeric_vector_static_t(make_numeric_vector_static_t(a1, a2), as...);
        }
References make_numeric_vector_static_t().
make_numeric_vector_static_t() [5/6]
template<typename T > constexpr numeric_vector_static_t< T, 1 > vt::detail::make_numeric_vector_static_t (const T & val) constexpr
Definition at line 762 of file numeric_vector.h.
{
            return numeric_vector_static_t<T, 1>(val);
        }
make_numeric_vector_static_t() [6/6]
template<typename T , typename... Ts> constexpr numeric_vector_static_t< T, 1+sizeof...(Ts)> vt::detail::make_numeric_vector_static_t (const T & val, const Ts &... vals) constexpr
Definition at line 768 of file numeric_vector.h.
{
            return make_numeric_vector_static_t({val, vals...});
        }
References make_numeric_vector_static_t().
make_nested() [1/2]
template<typename T , size_t Row, size_t Col, size_t ... I> constexpr numeric_vector_static_t< numeric_vector_static_t< T, Col >, Row > vt::detail::make_nested (const T(&) array[Row][Col], vt::index_sequence< I... >) constexpr
Definition at line 774 of file numeric_vector.h.
{
            return make_numeric_vector_static_t(make_numeric_vector_static_t(array[I])...);
        }
References make_numeric_vector_static_t().
Referenced by make_nested().
make_nested() [2/2]
template<typename T , size_t Row, size_t Col> constexpr numeric_vector_static_t< numeric_vector_static_t< T, Col >, Row > vt::detail::make_nested (const T(&) array[Row][Col]) constexpr
Definition at line 780 of file numeric_vector.h.
{
            return make_nested(array, vt::make_index_sequence<Row>());
        }
References make_nested().
make_diagonal_minor()
template<typename T , size_t Order, size_t I, size_t ... J> constexpr numeric_vector_static_t< T, Order > vt::detail::make_diagonal_minor (const T & value, vt::index_sequence< J... >) constexpr
Definition at line 786 of file numeric_vector.h.
{
            return make_numeric_vector_static_t(choose_if<(I == J)>(value, T())...);
        }
References vt::choose_if(), and make_numeric_vector_static_t().
make_diagonal() [1/2]
template<typename T , size_t Order, size_t ... I> constexpr numeric_vector_static_t< numeric_vector_static_t< T, Order >, Order > vt::detail::make_diagonal (const T(&) array[Order], vt::index_sequence< I... >) constexpr
Definition at line 792 of file numeric_vector.h.
{
            return make_numeric_vector_static_t(
                    make_diagonal_minor<T, Order, I>(array[I], vt::make_index_sequence<Order>())...
            );
        }
References make_numeric_vector_static_t().
Referenced by vt::impl::numeric_matrix_static_t< T, Row, Col >::diagonals(), vt::impl::numeric_matrix_static_t< T, Row, Col >::diagonals(), and make_diagonal().
make_diagonal() [2/2]
template<typename T , size_t Order, size_t ... I> constexpr numeric_vector_static_t< numeric_vector_static_t< T, Order >, Order > vt::detail::make_diagonal (const T(&) array[Order]) constexpr
Definition at line 800 of file numeric_vector.h.
{
            return make_diagonal(array, vt::make_index_sequence<Order>());
        }
References make_diagonal().
try_add_lvalue_reference() [1/2]
template<typename T > auto vt::detail::try_add_lvalue_reference (int) -> type_identity< T & >
try_add_lvalue_reference() [2/2]
template<typename T > auto vt::detail::try_add_lvalue_reference (...) -> type_identity< T >
try_add_rvalue_reference() [1/2]
template<typename T > auto vt::detail::try_add_rvalue_reference (int) -> type_identity< T && >
try_add_rvalue_reference() [2/2]
template<typename T > auto vt::detail::try_add_rvalue_reference (...) -> type_identity< T >