VT Linear Algebra Library: vt Namespace Reference
vt Namespace Reference
Namespaces
namespace detail
namespace impl
namespace imu_tools
namespace kalman
Classes
struct add_lvalue_reference
struct add_rvalue_reference
class circular_buffer_dynamic_t
class circular_buffer_static_t
class complex_t
struct enable_if
struct enable_if< true, T >
struct euler_t
class extended_kalman_filter_t
struct if_constexpr
struct if_constexpr< false >
struct if_constexpr< true >
struct index_sequence
class initializer_list
struct is_same
struct is_same< T, T >
class iterator
struct make_index_sequence
struct make_index_sequence< 0, Is... >
class numeric_matrix_dynamic_lu_t
class numeric_matrix_dynamic_t
class numeric_vector_dynamic_t
class pair
struct quaternion_t
struct remove_reference
struct remove_reference< T & >
struct remove_reference< T && >
class simple_kalman_filter_t
Typedefs
template<typename T , size_t Capacity>
using buffer_t = circular_buffer_static_t< T, Capacity >
using numeric_matrix = numeric_matrix_dynamic_t< double >
using numeric_vector = numeric_vector_dynamic_t< double >
template<typename T >
using const_iterator = iterator< const T >
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension>
using kalman_filter_t = simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension>
using KF = simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension>
using EKF = extended_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >
template<size_t OSize>
using numeric_matrix_lu = impl::numeric_matrix_static_lu_t< real_t, OSize >
using real_t = double
template<typename T >
using remove_reference_t = typename vt::remove_reference< T >::type
template<bool B, typename T = void>
using enable_if_t = typename enable_if< B, T >::type
Functions
template<typename T , size_t Capacity>
constexpr buffer_t< T, Capacity > make_buffer ()
complex_t operator+ (real_t lhs, const complex_t &rhs)
complex_t operator- (real_t lhs, const complex_t &rhs)
complex_t operator* (real_t lhs, const complex_t &rhs)
complex_t operator/ (real_t lhs, const complex_t &rhs)
template<typename T >
numeric_matrix_dynamic_t< T > operator* (T lhs, const numeric_matrix_dynamic_t< T > &rhs)
template<typename T >
T det (const numeric_matrix_dynamic_t< T > &A)
template<typename T >
T tr (const numeric_matrix_dynamic_t< T > &A)
template<typename T >
numeric_matrix_dynamic_t< T > inv (const numeric_matrix_dynamic_t< T > &A)
template<typename T >
numeric_matrix_dynamic_t< T > RRE (const numeric_matrix_dynamic_t< T > &A)
template<typename T >
numeric_vector_dynamic_t< T > operator* (T lhs, const numeric_vector_dynamic_t< T > &rhs)
template<typename T , size_t N>
numeric_vector_dynamic_t< T > operator+ (const T(&lhs)[N], const numeric_vector_dynamic_t< T > &rhs)
template<typename T , size_t N>
numeric_vector_dynamic_t< T > operator- (const T(&lhs)[N], const numeric_vector_dynamic_t< T > &rhs)
template<typename T >
constexpr bool operator== (T *ptr, const iterator< T > &iterator)
template<typename T >
constexpr bool operator!= (T *ptr, const iterator< T > &iterator)
template<typename T , size_t Row, size_t Col>
T det (const impl::numeric_matrix_static_t< T, Row, Col > &A)
template<typename T , size_t Row, size_t Col>
T tr (const impl::numeric_matrix_static_t< T, Row, Col > &A)
template<typename T , size_t Row, size_t Col>
impl::numeric_matrix_static_t< T, Row, Col > inv (const impl::numeric_matrix_static_t< T, Row, Col > &A)
template<typename T , size_t Row, size_t Col>
impl::numeric_matrix_static_t< T, Row, Col > RRE (const impl::numeric_matrix_static_t< T, Row, Col > &A)
template<size_t Row, size_t Col = Row>
constexpr numeric_matrix< Row, Col > make_numeric_matrix (const real_t(&array)[Row][Col])
template<size_t Row, size_t Col = Row>
constexpr numeric_matrix< Row, Col > make_numeric_matrix (const numeric_matrix< Row, Col > &M)
template<size_t R1, size_t R2, size_t C1, size_t C2>
constexpr numeric_matrix< R1+R2, C1+C2 > make_quad_matrix (const numeric_matrix< R1, C1 > &M11, const numeric_matrix< R1, C2 > &M12, const numeric_matrix< R2, C1 > &M21, const numeric_matrix< R2, C2 > &M22)
template<size_t ORow, size_t OCol, size_t M, size_t N>
constexpr numeric_matrix<(ORow *M),(OCol *N)> make_block_matrix (const numeric_matrix< ORow, OCol >(&blocks)[M][N])
template<size_t Order>
constexpr numeric_matrix< Order, Order > make_diagonal_matrix (const real_t(&array)[Order])
template<size_t Order>
constexpr numeric_matrix< Order, Order > make_diagonal_matrix (real_t value)
template<size_t Size>
constexpr numeric_vector< Size > make_numeric_vector (const real_t(&array)[Size])
template<size_t Size>
constexpr numeric_vector< Size > make_numeric_vector (const numeric_vector< Size > &vector)
template<size_t S1, size_t S2>
constexpr numeric_vector< S1+S2 > make_numeric_vector (const numeric_vector< S1 > &v1, const numeric_vector< S2 > &v2)
template<size_t S1, size_t S2, size_t... Ss>
constexpr numeric_vector< vt::detail::size_sum< numeric_vector< S1 >, numeric_vector< S2 >, numeric_vector< Ss >... >::value > make_numeric_vector (const numeric_vector< S1 > &v1, const numeric_vector< S2 > &v2, const numeric_vector< Ss > &... vs)
template<typename T1 , typename T2 >
constexpr pair< T1, T2 > make_pair (const T1 &t1, const T2 &t2)
template<typename T1 , typename T2 >
constexpr pair< T1, T2 > make_pair (T1 &&t1, T2 &&t2)
template<typename T >
__attribute__ ((always_inline)) const expr const T &min(const T &a
template<typename T , typename... Ts>
__attribute__ ((always_inline)) const expr const T &min(const T &a
template<typename T >
__attribute__ ((always_inline)) const expr remove_reference_t< T > &&move(T &&t) noexcept
template<typename T >
void swap (T &a, T &b)
template<typename ForwardIt , typename T >
void fill (ForwardIt first, ForwardIt last, const T &value)
template<typename InputIt , typename OutputIt >
OutputIt copy (InputIt first, InputIt last, OutputIt d_first)
template<typename T >
vt::add_rvalue_reference< T >::type declval () noexcept
template<bool condition, typename T >
constexpr T choose_if (const T &value_if_true, const T &value_if_false)
Variables
const T & b { return (a < b) ? a : b
const T const Ts & args
Typedef Documentation
buffer_t
template<typename T , size_t Capacity> using vt::buffer_t = typedef circular_buffer_static_t<T, Capacity>
Definition at line 86 of file circular_buffer.h.
numeric_matrix
using vt::numeric_matrix = typedef impl::numeric_matrix_static_t<real_t, Row, Col>
Numeric matrix where the dimension must be known at compile-time and can't be changed by any ways during runtime to prevent unexpected behavior or errors. This avoid heap usages for safety-critical and performance-critical systems.
This numeric matrix uses real type (real_t), defined as double).
Template Parameters
T Data type
Row Row dimension
Col Column dimension
Definition at line 675 of file dynamic_numeric_matrix.h.
numeric_vector
using vt::numeric_vector = typedef impl::numeric_vector_static_t<real_t, Size>
Numeric vector where the dimension must be known at compile-time and can't be changed by any ways during runtime to prevent unexpected behavior or errors. This avoid heap usages for safety-critical and performance-critical systems.
This numeric vector uses real type (real_t), defined as double).
Template Parameters
Size Vector dimension
Definition at line 326 of file dynamic_numeric_vector.h.
const_iterator
template<typename T > using vt::const_iterator = typedef iterator<const T>
Definition at line 65 of file iterator.h.
kalman_filter_t
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension> using vt::kalman_filter_t = typedef simple_kalman_filter_t<StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension>
Definition at line 166 of file kalman.h.
KF
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension> using vt::KF = typedef simple_kalman_filter_t<StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension>
Definition at line 170 of file kalman.h.
EKF
template<size_t StateVectorDimension, size_t MeasurementVectorDimension, size_t ControlVectorDimension> using vt::EKF = typedef extended_kalman_filter_t<StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension>
Definition at line 174 of file kalman.h.
numeric_matrix_lu
template<size_t OSize> using vt::numeric_matrix_lu = typedef impl::numeric_matrix_static_lu_t<real_t, OSize>
Definition at line 1141 of file numeric_matrix.h.
real_t
using vt::real_t = typedef double
Definition at line 16 of file standard_utility.h.
remove_reference_t
template<typename T > using vt::remove_reference_t = typedef typename vt::remove_reference<T>::type
Definition at line 50 of file standard_utility.h.
enable_if_t
template<bool B, typename T = void> using vt::enable_if_t = typedef typename enable_if<B, T>::type
Definition at line 202 of file standard_utility.h.
Function Documentation
make_buffer()
template<typename T , size_t Capacity> constexpr buffer_t< T, Capacity > vt::make_buffer () constexpr
Definition at line 89 of file circular_buffer.h.
{ return buffer_t<T, Capacity>(); }
operator+() [1/2]
complex_t vt::operator+ (real_t lhs, const complex_t & rhs)
Definition at line 168 of file complex_number.h.
{ return rhs.operator+(lhs); }
operator-() [1/2]
complex_t vt::operator- (real_t lhs, const complex_t & rhs)
Definition at line 170 of file complex_number.h.
{ return complex_t(lhs).operator-(rhs); }
operator*() [1/3]
complex_t vt::operator* (real_t lhs, const complex_t & rhs)
Definition at line 172 of file complex_number.h.
{ return rhs.operator*(lhs); }
operator/()
complex_t vt::operator/ (real_t lhs, const complex_t & rhs)
Definition at line 174 of file complex_number.h.
{ return complex_t(lhs).operator/(rhs); }
operator*() [2/3]
template<typename T > numeric_matrix_dynamic_t< T > vt::operator* (T lhs, const numeric_matrix_dynamic_t< T > & rhs)
Definition at line 632 of file dynamic_numeric_matrix.h.
{
        numeric_matrix_dynamic_t < T > tmp(rhs);
        tmp.operator*=(lhs);
        return tmp;
    }
det() [1/2]
template<typename T > T vt::det (const numeric_matrix_dynamic_t< T > & A)
Definition at line 639 of file dynamic_numeric_matrix.h.
{ return A.det(); }
References vt::numeric_matrix_dynamic_t< T >::det().
tr() [1/2]
template<typename T > T vt::tr (const numeric_matrix_dynamic_t< T > & A)
Definition at line 642 of file dynamic_numeric_matrix.h.
{ return A.tr(); }
References vt::numeric_matrix_dynamic_t< T >::tr().
inv() [1/2]
template<typename T > numeric_matrix_dynamic_t< T > vt::inv (const numeric_matrix_dynamic_t< T > & A)
Definition at line 645 of file dynamic_numeric_matrix.h.
{ return A.inv(); }
References vt::numeric_matrix_dynamic_t< T >::inv().
RRE() [1/2]
template<typename T > numeric_matrix_dynamic_t< T > vt::RRE (const numeric_matrix_dynamic_t< T > & A)
Definition at line 648 of file dynamic_numeric_matrix.h.
{ return A.RRE(); }
operator*() [3/3]
template<typename T > numeric_vector_dynamic_t< T > vt::operator* (T lhs, const numeric_vector_dynamic_t< T > & rhs)
Definition at line 306 of file dynamic_numeric_vector.h.
{
        numeric_vector_dynamic_t<T> tmp(rhs);
        tmp.operator*=(lhs);
        return tmp;
    }
operator+() [2/2]
template<typename T , size_t N> numeric_vector_dynamic_t< T > vt::operator+ (const T(&) lhs[N], const numeric_vector_dynamic_t< T > & rhs)
Definition at line 313 of file dynamic_numeric_vector.h.
{
        numeric_vector_dynamic_t<T> tmp(rhs);
        tmp.operator+=(lhs);
        return tmp;
    }
operator-() [2/2]
template<typename T , size_t N> numeric_vector_dynamic_t< T > vt::operator- (const T(&) lhs[N], const numeric_vector_dynamic_t< T > & rhs)
Definition at line 320 of file dynamic_numeric_vector.h.
{
        numeric_vector_dynamic_t<T> tmp(rhs);
        tmp.operator-=(lhs);
        return tmp;
    }
operator==()
template<typename T > constexpr bool vt::operator== (T * ptr, const iterator< T > & iterator) constexpr
Definition at line 59 of file iterator.h.
{ return iterator.operator==(ptr); }
Referenced by operator!=().
operator!=()
template<typename T > constexpr bool vt::operator!= (T * ptr, const iterator< T > & iterator) constexpr
Definition at line 62 of file iterator.h.
{ return !operator==(ptr, iterator); }
References operator==().
det() [2/2]
template<typename T , size_t Row, size_t Col> T vt::det (const impl::numeric_matrix_static_t< T, Row, Col > & A)
Finds determinant of this matrix.
If this matrix is not square, the compile-time error is thrown.
Template Parameters
T
Row
Col
Parameters
A
Returns
Determinant
Definition at line 1026 of file numeric_matrix.h.
{ return A.det(); }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::det().
tr() [2/2]
template<typename T , size_t Row, size_t Col> T vt::tr (const impl::numeric_matrix_static_t< T, Row, Col > & A)
Finds trace of this matrix.
If this matrix is not square, the compile-time error is thrown.
Template Parameters
T
Row
Col
Parameters
A
Returns
Trace
Definition at line 1039 of file numeric_matrix.h.
{ return A.tr(); }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::tr().
inv() [2/2]
template<typename T , size_t Row, size_t Col> impl::numeric_matrix_static_t< T, Row, Col > vt::inv (const impl::numeric_matrix_static_t< T, Row, Col > & A)
Finds inverse of this matrix.
If this matrix is not square, the compile-time error is thrown.
Template Parameters
T
Row
Col
Parameters
A
Returns
Inverse
Definition at line 1052 of file numeric_matrix.h.
{
        return A.inv();
    }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::inv().
RRE() [2/2]
template<typename T , size_t Row, size_t Col> impl::numeric_matrix_static_t< T, Row, Col > vt::RRE (const impl::numeric_matrix_static_t< T, Row, Col > & A)
Finds RRE form of this matrix.
Template Parameters
T
Row
Col
Parameters
A
Returns
RRE form of this matrix
Definition at line 1066 of file numeric_matrix.h.
{
        return A.RRE();
    }
References vt::impl::numeric_matrix_static_t< T, Row, Col >::RRE().
make_numeric_matrix() [1/2]
template<size_t Row, size_t Col = Row> constexpr numeric_matrix< Row, Col > vt::make_numeric_matrix (const real_t(&) array[Row][Col]) constexpr
Creates a numeric matrix.
Template Parameters
Row Row dimension
Col Column dimension
Parameters
array Array of data
Returns
Numeric matrix
Definition at line 1152 of file numeric_matrix.h.
{
        return numeric_matrix<Row, Col>(array);
    }
make_numeric_matrix() [2/2]
template<size_t Row, size_t Col = Row> constexpr numeric_matrix< Row, Col > vt::make_numeric_matrix (const numeric_matrix< Row, Col > & M) constexpr
Creates a numeric matrix (copy).
Template Parameters
Row Row dimension
Col Column dimension
Parameters
M Input numeric matrix
Returns
Numeric matrix
Definition at line 1164 of file numeric_matrix.h.
{
        return numeric_matrix<Row, Col>(M);
    }
make_quad_matrix()
template<size_t R1, size_t R2, size_t C1, size_t C2> constexpr numeric_matrix< R1+R2, C1+C2 > vt::make_quad_matrix (const numeric_matrix< R1, C1 > & M11, const numeric_matrix< R1, C2 > & M12, const numeric_matrix< R2, C1 > & M21, const numeric_matrix< R2, C2 > & M22) constexpr
Creates a quad matrix.
Template Parameters
Row
Col
R1
R2
C1
C2
Parameters
M11
M12
M21
M22
Returns
Numeric matrix
Definition at line 1184 of file numeric_matrix.h.
{
        return numeric_matrix<R1 + R2, C1 + C2>(M11, M12, M21, M22);
    }
make_block_matrix()
template<size_t ORow, size_t OCol, size_t M, size_t N> constexpr numeric_matrix<(ORow *M),(OCol *N)> vt::make_block_matrix (const numeric_matrix< ORow, OCol >(&) blocks[M][N]) constexpr
Creates a block matrix.
Template Parameters
ORow
OCol
M
N
Parameters
blocks Array of matrices
Returns
Numeric matrix
Definition at line 1203 of file numeric_matrix.h.
{
        return numeric_matrix<(ORow * M), (OCol * N)>(blocks);
    }
make_diagonal_matrix() [1/2]
template<size_t Order> constexpr numeric_matrix< Order, Order > vt::make_diagonal_matrix (const real_t(&) array[Order]) constexpr
Creates a diagonal matrix filled with array of values.
Template Parameters
Order
Parameters
array Array of diagonal's values
Returns
Numeric matrix
Definition at line 1216 of file numeric_matrix.h.
{
        return numeric_matrix<Order, Order>::diagonals(array);
    }
make_diagonal_matrix() [2/2]
template<size_t Order> constexpr numeric_matrix< Order, Order > vt::make_diagonal_matrix (real_t value) constexpr
Creates a diagonal matrix filled with value.
Template Parameters
Order
Parameters
value Value to fill the diagonal
Returns
Numeric matrix
Definition at line 1229 of file numeric_matrix.h.
{
        return numeric_matrix<Order, Order>::diagonals(value);
    }
make_numeric_vector() [1/4]
template<size_t Size> constexpr numeric_vector< Size > vt::make_numeric_vector (const real_t(&) array[Size]) constexpr
Creates a numeric vector.
Template Parameters
Size Vector dimension
Parameters
array Array of data
Returns
Numeric vector
Definition at line 685 of file numeric_vector.h.
{
        return numeric_vector<Size>(array);
    }
Referenced by make_numeric_vector(), and vt::simple_kalman_filter_t< StateVectorDimension, MeasurementVectorDimension, ControlVectorDimension >::update().
make_numeric_vector() [2/4]
template<size_t Size> constexpr numeric_vector< Size > vt::make_numeric_vector (const numeric_vector< Size > & vector) constexpr
Creates a numeric vector (copy).
Template Parameters
Size Vector dimension
Parameters
vector Vector to copy from
Returns
Numeric vector
Definition at line 697 of file numeric_vector.h.
{
        return numeric_vector<Size>(vector);
    }
make_numeric_vector() [3/4]
template<size_t S1, size_t S2> constexpr numeric_vector< S1+S2 > vt::make_numeric_vector (const numeric_vector< S1 > & v1, const numeric_vector< S2 > & v2) constexpr
Creates a numeric vector by extending multiple numeric vectors.
Template Parameters
S1
S2
Parameters
v1 Vector 1
v2 Vector 2
Returns
Numeric vector
Definition at line 712 of file numeric_vector.h.
{
        return numeric_vector<S1 + S2>(v1, v2);
    }
make_numeric_vector() [4/4]
template<size_t S1, size_t S2, size_t... Ss> constexpr numeric_vector< vt::detail::size_sum< numeric_vector< S1 >, numeric_vector< S2 >, numeric_vector< Ss >... >::value > vt::make_numeric_vector (const numeric_vector< S1 > & v1, const numeric_vector< S2 > & v2, const numeric_vector< Ss > &... vs) constexpr
Creates a numeric vector by extending multiple numeric vectors.
Template Parameters
S1
S2
Ss
Parameters
v1 Vector 1
v2 Vector 2
vs Vectors
Returns
Numeric vector
Definition at line 729 of file numeric_vector.h.
{
        return make_numeric_vector(make_numeric_vector(v1, v2), vs...);
    }
References make_numeric_vector().
make_pair() [1/2]
template<typename T1 , typename T2 > constexpr pair< T1, T2 > vt::make_pair (const T1 & t1, const T2 & t2) constexpr
Definition at line 34 of file pair.h.
{ return pair<T1, T2>(t1, t2); }
make_pair() [2/2]
template<typename T1 , typename T2 > constexpr pair< T1, T2 > vt::make_pair (T1 && t1, T2 && t2) constexpr
Definition at line 37 of file pair.h.
{ return pair<T1, T2>(t1, t2); }
__attribute__() [1/3]
template<typename T > vt::__attribute__ ((always_inline)) const &
References b.
__attribute__() [2/3]
template<typename T , typename... Ts> vt::__attribute__ ((always_inline)) const &
References args, and b.
__attribute__() [3/3]
template<typename T > vt::__attribute__ ((always_inline)) const && noexcept
Mimic std::move.
Template Parameters
T
Parameters
t
Returns
Definition at line 60 of file standard_utility.h.
                                                 { return static_cast<remove_reference_t<T> &&>(t); }
swap()
template<typename T > void vt::swap (T & a, T & b)
Mimic std::swap
Template Parameters
T
Parameters
a
b
Definition at line 71 of file standard_utility.h.
{
        T tmp = vt::move(a);
        a = vt::move(b);
        b = vt::move(tmp);
    }
References b.
Referenced by vt::complex_t::operator=(), vt::numeric_matrix_dynamic_t< T >::slice(), vt::numeric_matrix_dynamic_t< T >::swap(), vt::numeric_vector_dynamic_t< T >::swap(), and vt::impl::numeric_vector_static_t< T, Size >::swap().
fill()
template<typename ForwardIt , typename T > void vt::fill (ForwardIt first, ForwardIt last, const T & value)
Mimic std::fill
Template Parameters
ForwardIt
T
Parameters
first
last
value
Definition at line 108 of file standard_utility.h.
{
        for (; first != last; static_cast<void>(++first)) *first = value;
    }
Referenced by vt::impl::numeric_vector_static_t< T, Size >::allocate_fill(), vt::numeric_matrix_dynamic_t< T >::allocate_fill(), vt::numeric_vector_dynamic_t< T >::allocate_fill(), vt::impl::numeric_matrix_static_t< T, Row, Col >::allocate_fill(), vt::numeric_matrix_dynamic_t< T >::numeric_matrix_dynamic_t(), and vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t().
copy()
template<typename InputIt , typename OutputIt > OutputIt vt::copy (InputIt first, InputIt last, OutputIt d_first)
Mimic std::copy
Template Parameters
InputIt
OutputIt
Parameters
first
last
d_first
Returns
Definition at line 123 of file standard_utility.h.
{
        for (; first != last; static_cast<void>(++first), static_cast<void>(++d_first)) *d_first = *first;
        return d_first;
    }
Referenced by vt::numeric_vector_dynamic_t< T >::allocate_from(), vt::impl::numeric_vector_static_t< T, Size >::allocate_from(), vt::numeric_vector_dynamic_t< T >::allocate_from(), vt::impl::numeric_vector_static_t< T, Size >::allocate_from(), vt::circular_buffer_static_t< T, Capacity >::circular_buffer_static_t(), vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t(), and vt::numeric_vector_dynamic_t< T >::numeric_vector_dynamic_t().
declval()
template<typename T > vt::add_rvalue_reference< T >::type vt::declval () noexcept
Definition at line 161 of file standard_utility.h.
{
        static_assert(vt::detail::always_false<T>::value, "declval is not allowed in an evaluated context.");
    }
choose_if()
template<bool condition, typename T > constexpr T vt::choose_if (const T & value_if_true, const T & value_if_false) constexpr
Definition at line 205 of file standard_utility.h.
{
        return condition ? value_if_true : value_if_false;
    }
Referenced by vt::detail::make_diagonal_minor().
Variable Documentation
b
const T & vt::b { return (a < b) ? a : b
Definition at line 19 of file standard_utility.h.
Referenced by __attribute__(), and swap().
args
const T const Ts & vt::args
Initial value:
{
        return min(min(a, b), args...)
Definition at line 22 of file standard_utility.h.
Referenced by __attribute__(), and vt::if_constexpr< true >::run().